### ISSUE TITLE
User events are triggered in subsequent tests

### ISSUE THREAD

**Issue by nickmaddren** [testing-library/user-event#1001]
### Reproduction example

https://codesandbox.io/s/upbeat-keller-7f3c6s?file=/src/App.test.js

### Prerequisites

Perform user events across a sequence of tests.

I've found that the more performance-heavy the component I test, the more chance this will occur. I'm not sure if there is something more specific that causes this though.

In the code sandbox example, I have used the MUI autocomplete component as this was one of many components that flagged up in our project. It's not just specific to MUI though, this is occurring across some of our custom components as well.

### Expected behavior

User events should not bleed into subsequential tests.

### Actual behavior

Since upgrading to `user-event` v14 we've noticed many of our React Testing Library tests are failing.

As you can see in the code sandbox example I have provided, `userEvent.type` seems to bleed into subsequent test cases:

![Screenshot 2022-07-27 at 10 11 55](https://user-images.githubusercontent.com/7794072/181213807-19c251e5-d788-4d55-bd9a-6ab3a35e4c02.png)

It should type "A New Option", but instead it conflicts with the previous test.

### User-event version

14.3.0

### Environment

Testing Library framework: 

JS framework: 

Test environment: 

DOM implementation:

**Comment by ph-fritsche** [comment]
You should `await` the `Promise` returned by the `user-event` APIs.
https://codesandbox.io/s/amazing-tdd-tzwvr3?file=/src/App.test.js

I recommend [`@typescript-eslint/no-floating-promises`](https://typescript-eslint.io/rules/no-floating-promises).
