### ISSUE TITLE
event.keyCode / which not filled

### ISSUE THREAD

**Issue by fragsalat** [testing-library/user-event#1006]
### Reproduction example

https://github.com/fragsalat/userEvent14Bug

run `yarn install` and `yarn test` to see the log (test will be green, just the log is important) and see the required fields are 0.

### Prerequisites

1. render component with onKeyDown listender
2. type something using `await userEvent.type(input, 'a{enter}');
3. check the event received in the listener has event.keyCode or event.which (will be 0)

### Expected behavior

I expect fields like keyCode and which still to be filled as it is still used by a lot of libraries. In the version 13.5.0 the log inside the onKeyDown was looking like this
```
console.log
    Writing `b`
  console.log
    synthetic { which: 98, charCode: 0, keyCode: 98, key: 'b' } nativeEvent { which: 0, charCode: 0, keyCode: 98, key: 'b' }
  console.log
    Writing `{enter}`
  console.log
    synthetic { which: 13, charCode: 0, keyCode: 13, key: 'Enter' } nativeEvent { which: 0, charCode: 0, keyCode: 13, key: 'Enter' }
  console.log
    Sending fireEvent.keyDown
  console.log
    synthetic { which: 13, charCode: 0, keyCode: 13, key: 'Enter' } nativeEvent { which: 13, charCode: 0, keyCode: 13, key: 'Enter' }
```

### Actual behavior

With userEvent@14 which and keyCode are always 0

```
  console.log
    Writing `b`
  console.log
    synthetic { which: 0, charCode: 0, keyCode: 0, key: 'b' } native { which: 0, charCode: 0, keyCode: 0, key: 'b' }
  console.log
    Writing `{enter}`
  console.log
    synthetic { which: 0, charCode: 0, keyCode: 0, key: 'Enter' } native { which: 0, charCode: 0, keyCode: 0, key: 'Enter' }
  console.log
    Sending fireEvent.keyDown
  console.log
    synthetic { which: 13, charCode: 0, keyCode: 13, key: 'Enter' } native { which: 13, charCode: 0, keyCode: 13, key: 'Enter' }
```

### User-event version

14.3.0

### Environment

Testing Library framework: `@testing-library/react@12.1.5` and tested also on `@testing-library/react@13.3.0`

JS framework: `react@17.0.2`  and tested also with `react@18`

Test environment: `jest@28.1.3`

DOM implementation: `jsdom@19.0.0`

For more info please check the linked repo.

### Additional context

I tested it with react@17 + @testing-library/react@12 and react@18 + @testing-library/react@13
Tested userEvent@13 which seem to work ok and then userEvent@14 which is broken. I also went down to 14.0.0 which also contains the issue.

**Comment by ph-fritsche** [comment]
>## [14.0.0](https://github.com/testing-library/user-event/compare/v13.5.0...v14.0.0) (2022-03-29)
> 
> ### ⚠ BREAKING CHANGES
> 
> * Support for `keyCode` property on keyboard events has been removed.

See https://github.com/testing-library/user-event/issues/842#issuecomment-1019528148

If you need this to deal with third-party code, you should file an issue there.
Until their code is fixed, you can patch the event:
https://github.com/testing-library/user-event/issues/946#issuecomment-1117043577

**Comment by ph-fritsche** [comment]
> [`UIEvent.which`](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which) is non-standard. You should use `KeyboardEvent.key`, `KeyboardEvent.code` or [`MouseEvent.button`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button).

**Comment by fragsalat** [comment]
Hmkay. I'll file a bug report in antd then. Thx for the fast response
