### ISSUE TITLE
The upgrade from 14.3.0 to 14.4.0 of @testing-library/user-event no longer supports node 14

### ISSUE THREAD

**Issue by sesam** [testing-library/user-event#1014]
### Reproduction example

Not a website

### Prerequisites

Reproduce
1. Run with node 14, so e.g. `nvm use 14`
2. run any test that imports this library

### Expected behavior

With no major version bump this package should still be possible to load.

### Actual behavior

It fails, saying `??=` isn't supported.

### User-event version

14.4.0

### Environment

~Testing Library framework:~

~JS framework:~

~DOM implementation:~

### Additional context

Suggest to either make this a major version bump,

or look into what went wrong with the build pipeline change in this version -> https://github.com/testing-library/user-event/commit/fd8f2194b28848923858a0404b09044a89af0781

**Comment by ph-fritsche** [comment]
Thanks for the report. :heart:

**Comment by ph-fritsche** [comment]
@all-contributors add @sesam bug
