### ISSUE TITLE
userEvent.click doesn't check checkboxes but fireEvent.click does

### ISSUE THREAD

**Issue by ioulios1** [testing-library/user-event#1028]
### Reproduction example

https://codesandbox.io/s/amazing-beaver-s6zyuo?file=/src/App.spec.js

### Prerequisites

1. Go to the codesandbox link and press the "Test" tab

### Expected behavior

expected checkbox to be true after clicking it with userEvent

### Actual behavior

checkbox remained false after clicking it with userEvent

### User-event version

14.4.2

### Environment

    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^14.4.2",
    "react": "^18.0.0",

### Additional context

if i use fireEvent, the test works fine.
I tried older versions of 14.* aslo
I can't try with versions before 14 because they wont support other things in my code like destructuring assignment

**Comment by ph-fritsche** [comment]
https://testing-library.com/docs/user-event/intro/#writing-tests-with-userevent

I recommend [@typescript-eslint/no-floating-promises](https://typescript-eslint.io/rules/no-floating-promises).
