### ISSUE TITLE
userEvent.click on <label htmlFor="test"> element doesn't change "checked" attribute in corresponded <input type="checkbox"  id="test"/>

### ISSUE THREAD

**Issue by Anton2501** [testing-library/user-event#1031]
### Reproduction example

https://codesandbox.io/s/inspiring-hugle-74w64e?from-embed=&file=/src/App.test.js

### Prerequisites

1. Render "App" component
2. Get <label> element by  const label = screen.getByTestId('#label');
3. expect(screen.getByTestId('#checkbox-input')).not.toBeChecked() (I'm using  '@testing-library/jest-dom/extend-expect' for toBeChecked func)
4. userEvent.click(label)
5. expect(screen.getByTestId('#checkbox-input')).toBeChecked()

### Expected behavior

I would like that it works the same as through fireEvent.click or better

### Actual behavior

I've got an error, test fails, no matter how exactly I check this, whether I use .toBeChecked() or  expect(cb.checked).toBe(true), the result fails

### User-event version

14.4.2

### Environment

Testing Library framework: 

JS framework: 

Test environment: 

DOM implementation: 

### Additional context

Hope you can repropduce it in Codesandbox

**Comment by ph-fritsche** [comment]
https://testing-library.com/docs/user-event/intro/#writing-tests-with-userevent

I recommend [@typescript-eslint/no-floating-promises](https://typescript-eslint.io/rules/no-floating-promises).
