### ISSUE TITLE
`userEvent.click` on `<button type="submit" />` does not trigger form submission.

### ISSUE THREAD

**Issue by ImLuze** [testing-library/user-event#1032]
### Reproduction example

https://codesandbox.io/s/click-on-button-submits-form-forked-j1gtzp

### Prerequisites

1. Render a `<form />` with a `<button type="submit />` inside.
2. Attempt to submit the form using `userEvent.click(submitButton)`.

### Expected behavior

Expected the form to be submitted and it's onSubmit handle to be called.

### Actual behavior

Nothing happens, the form does not get submitted.

### User-event version

14.4.3

### Environment

Testing Library framework: 

JS framework: react@18.2.0 

Test environment: jest@28.1.6

DOM implementation: jsdom@16.7.0 

### Additional context

This issue has been reported before in #616 
I believe this issue is back in V14.

My CodeSandbox reproduction is a fork of the CodeSandbox mentioned in that previous issue, but with the versions in `package.json` bumped to latest:

> @chrys-exaucet It looks like the error is in your implementation. But it is a guessing game without the code of the component under test.
> 
> Submit works fine:
> https://codesandbox.io/s/click-on-button-submits-form-l9f4j?file=/src/App.test.js
> 
> Try to reproduce your bug in the codesandbox. Most likely you will find your bug just by isolating it that way.
> Should you require help, I can have a look at it once your sandbox yields your result. Most likely finding the error will take a lot less time than already spent on this issue.
> 
> Should we stumble over a bug that is reproducible in codesandbox, I'll gladly reopen this. But for now this is just a guessing game.

_Originally posted by @ph-fritsche in https://github.com/testing-library/user-event/issues/616#issuecomment-805690981_

**Comment by ph-fritsche** [comment]
https://testing-library.com/docs/user-event/intro/#writing-tests-with-userevent

I recommend [@typescript-eslint/no-floating-promises](https://typescript-eslint.io/rules/no-floating-promises).

**Comment by imnasnainaec** [comment]
@ph-fritsche I'm also dealing with this issue. Here's another codesandbox of the issue with newer `@testing-library` versions:
https://codesandbox.io/s/react-typescript-testing-library-form-button-ygt7vx

**Comment by emmalivingstone** [comment]
I'm also dealing with this issue. Had to downgrade to 14.3.0

**Comment by nikosrossolatos** [comment]
> I'm also dealing with this issue. Had to downgrade to 14.3.0

Thanks @emmalivingstone . Had the same issue, downgraded to 14.3.0 and it worked. I don't know why this issue is marked as "Closed" since v14.5.0 has this issue yet?

**Comment by bgalek** [comment]
Is this a regression?

**Comment by jachamberlain86** [comment]
I was having the same issue. Downgrading to 14.3.0 also resolved it.

I was running vite@4.4.5 with react@18.2.0 and testing with vitest@0.34.6, vitest-dom@0.1.1, @vitest/ui@0.34.6, @testing-library/react@14.1.0, @testing-library/user-event@14.5.1, jsdom@22.1.0, and global-jsdom@9.1.0. The form elements that weren't triggering were imported from react-router-dom@6.16.0

**Comment by zaunermax** [comment]
Still does not work... Downgrading to 14.3.0 also worked for me.

**Comment by Pacheco95** [comment]
Same.

```
"@testing-library/jest-dom": "^6.4.5",
"@testing-library/react": "^15.0.7",
```

I'm using this workaround solution

```ts
fireEvent.submit(screen.getByRole("form"));
```

**Comment by Pacheco95** [comment]
Oh! I just figured out that my submit button was in a disabled state. I fixed the rendering with according props and now everything is working as I intended to

```ts
fireEvent.click(screen.getByText(submitButton.label))
```

**Comment by simonnepomuk** [comment]
> @ph-fritsche Have the same problem, still not resolved! **Not working:**
> 
> ```
> const user = userEvent.setup();
> await user.click(getByText("Next"));
> ```
> 
> **Works for me:**
> 
> ```
> await waitFor(() => {
>    fireEvent.submit(getByText("Next"))
> })
> ```
> 
> package.json "@testing-library/jest-dom": "6.4.2", "@testing-library/react": "14.2.1", "@testing-library/user-event": "14.5.2", "@vitejs/plugin-react": "4.2.1", "@vitest/coverage-v8": "1.2.2", "jsdom": "24.0.0", "vite": "5.1.0", "vitest": "1.2.2"
> 
> Project to reproduce: [fe.zip](https://github.com/testing-library/user-event/files/14224218/fe.zip)

Currently on 14.5.2 and this is still the only way I got this working.

**Comment by imnasnainaec** [comment]
@ph-fritsche Can this issue please be re-opened?

I've updated the CodeSandbox that demos the issue with the most recent versions of `@testing-library`: https://codesandbox.io/p/sandbox/react-typescript-testing-library-form-button-forked-z2mynq

To see the failure, click on the "Run tests" button in the upper-right of the Preview window.

**Comment by ph-fritsche** [comment]
@imnasnainaec https://codesandbox.io/p/sandbox/react-typescript-testing-library-form-button-forked-z2mynq

**Comment by imnasnainaec** [comment]
Ah, the `userEvent.click` needs to be awaited. Makes sense.

**Comment by GWellerGMSL** [comment]
Still broken in 14.6.1
