### ISSUE TITLE
Cannot "upload" file that does not match `accept` pattern

### ISSUE THREAD

**Issue by khitrenovich** [testing-library/user-event#1046]
### Reproduction example

https://codesandbox.io/s/white-wood-jnes8g

### Prerequisites

A user can select a file that does not match the `accept` type of the `input` element. We (as programmers) are expected to handle this flow in our code and thus should be able to test this flow with unit tests. However, currently it is impossible to select a file that that does not match the `accept` type with `userEvent.upload()` helper - the selection is being silently ignored.

1. Click on "Choose File"
2. In the dialog, toggle file type selector from "*.json" to "all files"
3. Select a non-JSON file
4. Observe filename as it appears in the output field

Unfortunately, steps 2 and 3 were not captured on the video below, but you can observe the result.

https://user-images.githubusercontent.com/3424762/186747539-fe6d15d9-9460-4bf8-b938-61788f6a0269.mp4

### Expected behavior

I expect the unit test in the reproduction example to pass.

### Actual behavior

The unit test fails. 
As a result, we cannot unit-test a flow where user selects an invalid file.

### User-event version

14.4.3

### Environment

Testing Library framework: 

JS framework: 

Test environment: 

DOM implementation:

**Comment by ph-fritsche** [comment]
https://testing-library.com/docs/user-event/options#applyaccept

**Comment by khitrenovich** [comment]
Frankly, I would expect such king of configuration to apply to `upload` call itself... but having a way to tweak it works for me too.

**Comment by ph-fritsche** [comment]
We're trying to remove option parameters from the APIs.

You can chain setup calls to get an instance that shares the device state but tweaks configuration.
```js
const user = userEvent.setup()
await user.upload(myInput, myFile) // default with applyAccept
await user.setup({applyAccept: false}).upload(myInput, myFile)
```

**Comment by khitrenovich** [comment]
I see, with chainable nested objects it makes more sense indeed.

Meanwhile, maybe it is possible to link https://testing-library.com/docs/user-event/options#applyaccept from https://testing-library.com/docs/user-event/utility#upload section as "see also" or something similar? It would have saved me a couple of hours today...

**Comment by ph-fritsche** [comment]
Good point. PRs to the [docs](https://github.com/testing-library/testing-library-docs) are always welcome :)

**Comment by khitrenovich** [comment]
Here it goes - https://github.com/testing-library/testing-library-docs/pull/1144.
