### ISSUE TITLE
`await user.click()` as suggested by the docs doesn't work

### ISSUE THREAD

**Issue by targumon** [testing-library/user-event#1054]
### Reproduction example

https://codesandbox.io/s/intelligent-maria-lqp7d9?file=/src/Button.test.tsx

### Prerequisites

In codesandbox just switch to the 'Tests' tab.

### Expected behavior

Based on the example in the docs (https://testing-library.com/docs/user-event/intro/)
I expected this will make the test pass:
```javascript
await user.click(screen.getByRole('button'))
```

### Actual behavior

The test fails.

- In CSB the error is "The provided value is not of type 'Element'"
- In my original project (before reducing to smallest example) the test runner is jest and it throws "Exceeded timeout of 5000 ms for a test".

In both cases solved by:
```javascript
await waitFor(() => user.click(screen.getByRole('button')))
```

So either the docs are right and there's a bug or the docs are wrong.

### User-event version

14.4.3

### Additional context

This is just the tip of my frustration iceberg following the upgrade to @TL/react 13 + @TL/user-event 14
See my comment here: https://github.com/testing-library/react-testing-library/issues/1061#issuecomment-1238733591

**Comment by ph-fritsche** [comment]
In Codesandbox the `document` in the `test` is not `globalThis.document`.
You need to call `userEvent.setup({document})` inside the test.
https://codesandbox.io/s/userevent-react-vbcvs?file=/src/testEnv.js
https://testing-library.com/docs/user-event/options/#document

For the timeout issue in jest:
If you use fake timers, see https://testing-library.com/docs/user-event/options/#advancetimers .

**Comment by nathanhannig** [comment]
This just fixed my issue that I have been troubleshooting for many hours.

This does not work.
```await userEvent.click(options[0]);```

These work:
```fireEvent.click(options[0]);```
```await waitFor(() => userEvent.click(options[0]));```

Why is this?

**Comment by targumon** [comment]
The difference with CSB is because of being run in an iframe? Good to know!

And I indeed `useFakeTimers` - thank you for helping! 🙏
