### ISSUE TITLE
Unable to type when there are multiple input elements under a <label> tag

### ISSUE THREAD

**Issue by yongzhihuang** [testing-library/user-event#1055]
### Reproduction example

https://codesandbox.io/s/react-testing-library-demo-forked-204es0?file=/src/hello.js

### Prerequisites

1. Render the following via React
```
import React, { useState } from "react";

export default () => {
  const [text, setText] = useState("");

  return (
    <div>
      <label>
        {/* Comment out next line to make the test pass */}
        <input type="radio" value="foo" onChange={() => {}} />
        Radio choice
        <textarea
          aria-label="dummy text"
          value={text}
          onChange={(e) => setText(e.target.value)}
        />
      </label>
    </div>
  );
};

```

```
test("Test!", () => {
  const { getByLabelText } = render(<Hello />);
  const textArea = getByLabelText("dummy text");
  userEvent.type(textArea, "foo bar baz");
  expect(getByLabelText("dummy text")).toHaveValue("foo bar baz");
});

```

Test fails even when I specify to type the input into the textArea. 

2. Remove `        <input type="radio" value="foo" onChange={() => {}} />` from the render and test will pass

### Expected behavior

I expect the test to properly select the `textArea` element and type in the text.

### Actual behavior

Nothing was typed in to the textArea

### User-event version

13.5.0

### Environment

Testing Library framework: 

JS framework: 

Test environment: 

DOM implementation: 

### Additional context

I have a hunch that's because <label> doesn't accept multiple input elements (not semantic HTML)?

**Comment by ph-fritsche** [comment]
[![image](https://user-images.githubusercontent.com/39068198/190251996-5f0a0218-4834-4b3d-97ca-d5e3cdbf4e55.png)](https://testing-library.com/docs/ecosystem-user-event)


No issue with the latest version. https://codesandbox.io/s/react-testing-library-demo-forked-ky4gcc?file=/src/__tests__/hello.test.js
