### ISSUE TITLE
Click event not fired in React 18.

### ISSUE THREAD

**Issue by messaooudi** [testing-library/user-event#1059]
### Reproduction example

https://codesandbox.io/s/react-18-and-testing-library-user-event-bug-8kh10i?file=/src/App.test.js

### Prerequisites

1. Render a `<button onClick={props.onClick}>button</button>` element.
2. Fire a `user.click(screen.getByRole("button"))` event.
3. Expect `props.onClick` to be called.

### Expected behavior

The `props.onClick` function should be called.

### Actual behavior

The `props.onClick` function is not called.

### User-event version

14.4.3

**Comment by ph-fritsche** [comment]
https://testing-library.com/docs/user-event/intro/#writing-tests-with-userevent

I recommend [@typescript-eslint/no-floating-promises](https://typescript-eslint.io/rules/no-floating-promises).
