### ISSUE TITLE
Invitation to move to testing-library org

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/user-event#108]
It's up to you, but if you'd like, you're welcome to transfer this repository to the [testing-library organization on GitHub](https://github.com/testing-library). This will give your project more credibility as part of the testing-library family of projects with a unified mission of tools which help people avoid testing implementation details.

Again, totally up to you. I just want you to know we appreciate all you've done and you're welcome to join us if you like.

**Comment by Gpx** [comment]
It looks like, I've decided to go on vacation on the wrong week 😂

I don't feel too confident moving the repo from my phone with my hotel WiFi but I will definitely do so as soon as I'm back. 

I'm really happy with the latest development in testing-library and can't wait to see new frameworks adopting the same philosophy. 

Thank you for all the hard work Kent and all the other contributors!

**Comment by kentcdodds** [comment]
Sounds good! Enjoy your vacation!

**Comment by Gpx** [comment]
Done 🎉
