### ISSUE TITLE
Add skipFocus option to click events

### ISSUE THREAD

**Issue by WesleyKapow** [testing-library/user-event#1080]
### Problem description

Right now `userEvent.click` will trigger both a click and a focus event to fire. This can cause issues when trying to open dropdowns that are dismissed when elements outside are clicked OR focused. What happens is, the click on a button triggers the dropdown to appear, and then the focus on the button triggers it to close.

### Suggested solution

Add a `skipFocus` option to click events so that focus events can be skipped.

### Additional context

Ran into this when using https://www.radix-ui.com/docs/primitives/components/dropdown-menu

Current work around for me is to provide `onFocusOutside={(event) => event.preventDefault()}` to the Radix dropdown component. I imagine other libraries have similar behavior.

**Comment by ph-fritsche** [comment]
A user cannot click a button without moving focus unless the author prevents default behavior on the `mousedown` which we account for.
We won't add new options to create workflows that cannot be performed by a real user.

Also the `click` event is fired after the `focus` event. There might be an issue with the component.
If you can create a minimal example without third-party code, we can reopen.
