### ISSUE TITLE
Export UserEvent type

### ISSUE THREAD

**Issue by brandon-leapyear** [testing-library/user-event#1085]
### Problem description

The docs mention that one can wrap `userEvent.setup()` in a `setup` function and return it alongside the render result. But adding a type signature to `setup` is difficult because there's no easy way to reference the return type of `userEvent.setup()`.

### Suggested solution

Ideally, I'd like to be able to do
```ts
import { render, RenderOptions, RenderResult } from '@testing-library/react'
import userEvent, { UserEvent } from '@testing-library/user-event'

const setup = (options: RenderOptions): RenderResult & { user: UserEvent } => ({
  ...render(options),
  user: userEvent.setup(),
})
```

### Additional context

Current workaround:
```ts
type UserEvent = ReturnType<typeof userEvent.setup>
```

**Comment by mattrunyon** [comment]
Another use case is if I want to create a test util for certain series of events (like control clicking)

```ts
async function controlClick(user: UserEvent, element: HTMLElement) {
  await user.keyboard('[Control>]');
  await user.click(element);
  await user.keyboard('[/Control]');
}
```

**Comment by Moto42** [comment]
I've been importing it as...    
`import { UserEvent } from "@testing-library/user-event/dist/types/setup/setup";`

Which allows for  
`let user:UserEvent;`

**Comment by joshuajaco** [comment]
@kentcdodds this one can also be closed.
Was fixed in https://github.com/testing-library/user-event/pull/1112
