### ISSUE TITLE
.toHaveFocus does output the whole rendered dom instead of the active element with React 18.2.0

### ISSUE THREAD

**Issue by LingVuDev** [testing-library/user-event#1086]
### Reproduction example

https://codesandbox.io/s/spring-fire-53eqzw?file=/src/App.test.js

### Prerequisites

```js
  it('should focus', async () => {
    render(<input data-test-id="search-input" value="hello" />);

    userEvent.click(screen.getByTestId('search-input'));
    expect(screen.getByTestId('search-input')).toHaveFocus();
  });
  ```

### Expected behavior

It should focus and assertion should not throwing an error

### Actual behavior

<SearchInput /> › should focus

    expect(element).toHaveFocus()

    Expected element with focus:
      <input data-test-id="search-input" value="hello" />
    Received element with focus:
      <body><div><input data-test-id="search-input" value="hello" /></div></body>

      56 |
      57 |     userEvent.click(screen.getByTestId('search-input'));
    > 58 |     expect(screen.getByTestId('search-input')).toHaveFocus();
         |                                                ^
      59 |   });
      60 | });
      61 |

### User-event version

14.4.3

### Environment

Testing Library framework: `@testing-library/react@13.4.0`

JS framework: `react@18.2.0`

Test environment: `jest@27.4.3`

**Comment by ph-fritsche** [comment]
https://testing-library.com/docs/user-event/intro/#writing-tests-with-userevent

I recommend [@typescript-eslint/no-floating-promises](https://typescript-eslint.io/rules/no-floating-promises).
