### ISSUE TITLE
Peer Dependency specification can cause random test breaks

### ISSUE THREAD

**Issue by Ltchoc221** [testing-library/user-event#1101]
### Reproduction example

 https://codesandbox.io/s/vbcvs?file=/src/App.js

### Prerequisites

1. Install application dependencies from above base codeSandbox (@testing-library/user-event@14.x and @testing-library/react@13.x)
2. Run 'npm ls @testing-library/dom'
3. See conflicting versions of @testing-library/dom in the dependency tree

### Expected behavior

All Tests pass when running the versions mentioned in the pre-requisites and using Nodejs18.

### Actual behavior

User-event actions throw 'Act()' console errors across projects that use the two versions mentioned, even though they should be compatible. 

### User-event version

14.4.1

### Environment

Using Nodejs18, @testing-library/user-event@14.x,. @testing-library/react@13.x

### Additional context

https://github.com/testing-library/user-event/blob/main/package.json#L70 -> This pulls in v9 of @testing-library/dom

https://github.com/testing-library/react-testing-library/blob/v13.4.0/package.json#L49 -> This pulls in v8 of @testing-library/dom

This created an unnecessary number of act() warnings being thrown in applications using these two compatible versions when v9 of the dom was released last week.  This peer-dependency should be pinned to a compatible major version for each release line.

**Comment by ph-fritsche** [comment]
This is not a bug with `@testing-library/user-event` but with the project configuration or the package manager.

If `@testing-library/react-testing-library@13.4.0` is used, `@testing-library/dom@^8.5.0` should be installed.
The version constraint for `@testing-library/dom@>=7.21.4` does not create a conflict. It is satisfied by the dependency of the framework library.

Please make sure that you don't list `@testing-library/dom` in your project dependencies.

**Comment by Ltchoc221** [comment]
I understand this is a relatively complex interaction between between the two packages, but when the instructions for neither package tell you that you have to install the DOM package, then closing this and saying "just install it" doesn't really feel like a solution.

**Comment by ph-fritsche** [comment]
You usually don't need to install it, unless you use `@testing-library/dom` directly.
In fact, you usually should not add it yourself if you use one of the framework libraries.

The package manager is supposed to install `@testing-library/dom` as a dependency of the framework library.
If your package manager does not work this way, you need to consult the docs of your package manager on how to resolve this.

https://testing-library.com/docs/user-event/install:
> Note that `@testing-library/user-event` requires `@testing-library/dom`.

> If you use one of the [framework wrappers](https://testing-library.com/docs/dom-testing-library/install#wrappers), it is
important that `@testing-library/dom` is resolved to the same installation
required by the framework wrapper of your choice.  
Usually this means that if you use one of the framework wrappers, you should not
add `@testing-library/dom` to your project dependencies.

**Comment by Ltchoc221** [comment]
You're not understanding the problem - npm (v8) *is* installing `@testing-library/dom`, in fact it's installing two conflicting versions of it: an 8.x version from `@testing-library/react` and a 9.x version from `@testing-library/user-event`.  

It's pretty clear and obvious from your responses that this is not the expected behavior. 

Take this super simple package.json:
```
{
  "name": "sample-npm-library",
  "version": "2.1.8-7",
  "description": "Sample npm Library",
  "main": "index.js",
  "repository": "<OMITTED>",
  "author": "<OMITTED>",
  "license": "SEE LICENSE IN LICENSE.txt",
  "dependencies": {
    "@testing-library/jest-dom": "5.16.3",
    "@testing-library/react": "13.4.0",
    "@testing-library/user-event": "14.1.1",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "peerDependencies": {
    "react": "^18.2.0"
  }
}
```

When you execute `npm ls @testing-library/dom`, you get the following output:

```
$ npm ls @testing-library/dom
sample-npm-library@2.1.8-7 I:\ds\projects\sample-js-projects\sample-npm-library
+-- @testing-library/react@13.4.0
| `-- @testing-library/dom@8.20.0
`-- @testing-library/user-event@14.1.1
  `-- @testing-library/dom@9.0.0
```

It's this conflicting dependency issue that's causing the problem, and it's stemming from the peer-dependency specification within user-event, since `@testing-library/react` installs v8 as a direct dependency.  

Even if it's strongly felt the peer-dependency specification is accurate, this behavior clearly isn't what's intended, otherwise there would be a stronger documentation call out somewhere.

**Comment by ph-fritsche** [comment]
You need to run `npm dedup` on recent versions of npm. (Or just use e.g. yarn.)
```
$ npm ls @testing-library/dom
user-event-consumer@ /workspaces/testing-library/user-event-consumer
├─┬ @testing-library/react@13.4.0
│ └── @testing-library/dom@8.20.0
└─┬ @testing-library/user-event@14.4.3
  └── @testing-library/dom@8.20.0 deduped
```
