### ISSUE TITLE
userEvent.setup parameter types

### ISSUE THREAD

**Issue by steven-prybylynskyi** [testing-library/user-event#1102]
### Reproduction example

Unfortunately there's no TypeScript template in Codesandbox

### Prerequisites

```ts
const user = userEvent.setup();
user.type([ intellisense ])
```

### Expected behavior

First argument is an `element: Element`
![image](https://user-images.githubusercontent.com/3078595/222448582-94ee8e9b-b10c-486b-96d7-1bd656827f70.png)

That is a screenshot of using `userEvent` directly

### Actual behavior

Typescript intellisense lists `...args` which is not very helpful
![image](https://user-images.githubusercontent.com/3078595/222448799-fdf3f1ae-ca92-48c7-bbaf-a8debf912567.png)

### User-event version

14.4.3

### Additional context

> Note that, while directly invoking APIs such as userEvent.click() (which will trigger setup internally) is [still supported in v14], this option exists to ease the migration from v13 to v14, and for simple tests. We recommend using the methods on the instances returned by userEvent.setup().

At this point the type of `user.[function]` returned from `userEvent.setup()` is unexpected and not useful in IDE

**Comment by ph-fritsche** [comment]
![image](https://user-images.githubusercontent.com/39068198/222453421-2505c943-7691-459d-b3aa-6fc284fadb56.png)
