### ISSUE TITLE
Angular@15: await for userEvent does not wait for the re-rendering of the component

### ISSUE THREAD

**Issue by enolive** [testing-library/user-event#1103]
### Reproduction example

https://codesandbox.io/p/github/enolive/angular-user-events/main?file=%2Fsrc%2Fapp%2Fapp.component.html

### Prerequisites

```ts
describe('AppComponent', () => {
  it('works', async () => {
    const view = await render(AppComponent)

    const button = screen.getByRole('button')
    await userEvent.click(button)
    // workaround option 3: trigger detectChanges
    // view.detectChanges()

    // workaround option 1: using fireEvent instead of userEvent fixes the test
    // fireEvent.click(button)

    // workaround option 2: waitFor fixes the test
    // await waitFor(() => {
    expect(screen.getByRole('status')).toHaveTextContent('You pressed the button!')
    // })
  })
})
```

Component code:

```html
<button (click)="onClick()">Click Me</button>

<p role="status">
  {{status}}
</p>
```

```ts
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  status: string = ''

  onClick() {
    console.log('clicked!')
    this.status = 'You pressed the button!'
  }
}
```

### Expected behavior

awaiting for the click on the button should give me an already re-rendered component. 

### Actual behavior

while the button click is triggered, the component DOM seems to remain unchanged so the expectation fails.

actual DOM after the click looks like this:

```html
<body>
      <div
        id="root0"
        ng-version="15.2.1"
      >
        <button>
          Click Me
        </button>
        <p
          role="status"
        >
           
    
        </p>
      </div>
    </body>
```

### User-event version

14.4.3

### Environment

Testing Library framework: `@testing-library/angular@13.3.0`

JS framework: `angular@15.2.0`

Test environment: `jest@29.4.0`

DOM implementation:  `jsdom@20.0.0`

### Additional context

The code above worked fine with Angular@14 without any tweaks. 

The click event is triggered without problems, but no re-rendering takes place unless I explicitly wait for it in a `waitFor` block. 

I find it also strange that fireEvent works without any problems.

I encountered the same problem in many other userEvents such as `type` and `hover` so I guess it is a general problem in this environment.

**Comment by pablorivassanchez** [comment]
Hello I'm using just these two libraries:

"@testing-library/angular": "13.0.2",
"@testing-library/dom": "9.3.1",
"@testing-library/user-event": "14.4.3",

Also with angular 15 and it happen the same to me i need to put the same workarounds for make it works. 

PD: if i don't add @testing-library/dom it does not work.

Regards,
