### ISSUE TITLE
Update of the @testing-library/react version to 14.0.0 throws "act" warnings

### ISSUE THREAD

**Issue by maive1** [testing-library/user-event#1104]
- `@testing-library/react` version: 14.0.0
- Testing Framework and version: jest 29.4.2
  
- DOM Environment: @testing-library/jest-dom: 5.16.5
  

### Relevant code or config:

```js
   const saveButton = screen.getByRole('button', { name: /save/i });
    await waitFor(() => expect(saveButton).toBeEnabled());
    await testUser.click(saveButton);
```

### What you did:

I upgraded the version of @testing-library/react from 13.4.0 to 14.0.0. And I started having problems in all the tests of my application. Before this update this did not happen.

### What happened:

I'm getting more act warnings now with @testing-library@14.0.0.
Tested with await waitFor, and still throwing act warnings with userEvent that triggers a state change.
![Captura de Pantalla 2023-02-20 a la(s) 18 29 41](https://user-images.githubusercontent.com/51271219/220201728-34c1147f-2ef5-4fd6-83ef-81a814fd3ed9.png)
![Captura de Pantalla 2023-02-20 a la(s) 18 29 13](https://user-images.githubusercontent.com/51271219/220201738-430adcc5-6be1-4abc-91fa-9a1587487ec9.png)

### Reproduction:

You can fork to reproduce the issue:
here: https://codesandbox.io/s/act-warning-wait-for-react-18-forked-6jurf2

### Problem description:

The state update (setState()) seems to make the test library think that act is incomplete, even though it is. This happens for every unit test where an event is fired, such as userEvent.click() or userEvent.upload().

**Comment by ph-fritsche** [comment]
I see different issues being mixed up here.

1. If you use e.g. `@testing-library/react` and `@testing-library/user-event`, those need to resolve `@testing-library/dom` to the same copy.

    See https://testing-library.com/docs/user-event/install:
    > Note that `@testing-library/user-event` requires `@testing-library/dom`.
    >
    > If you use one of the [framework wrappers](https://testing-library.com/docs/dom-testing-library/install#wrappers), it is
    important that `@testing-library/dom` is resolved to the same installation
    required by the framework wrapper of your choice.  
    Usually this means that if you use one of the framework wrappers, you should not
    add `@testing-library/dom` to your project dependencies.

    With recent versions of `npm` you need to run `npm dedup`.

2. If you use fake timers, you need to tell `@testing-library/user-event` how to wind the timer.

    See https://testing-library.com/docs/user-event/options#advancetimers:
    > If you are using fake timers, you need to advance your timers when we internally
    [delay](https://testing-library.com/docs/user-event/options#delay) subsequent code.
    >
    > ```ts
    >  (delay: number) => Promise<void> | void
    >  ```
    >
    >  `default`: `() => Promise.resolve()`

    With Jest's fake timers you need to setup `user-event` with `{advanceTimers: jest.advanceTimersByTime}`.

3. If you get `act` warnings after updating React, you might have brittle test code that expects an undefined order of execution to be the same on every test run.

    See https://twitter.com/ph_fritsche/status/1626279438496280576:
    > Do not just add act() calls until React shuts up!  
    > [https://ph-fritsche.github.io/blog/post/react-act](https://t.co/NLep8XnELe)

**Comment by artursvonda** [comment]
Indeed, for my case the issue seems like was with multiple `@testing-library/dom` versions. Forcing v9 solved it. Thanks!

**Comment by ph-fritsche** [comment]
@thepuzzlemaster Your issue is explained in the blog post linked above.
```js
    onInitiate().then((result) => { // This delays for at least one microtask...
      setId(result); // ...and then updates state.
```
```js
await act(() => {
  jest.advanceTimersByTime(1000)
  return Promise.resolve() // This hides the issue in the codesandbox environment.
    // Might need any other number of microtasks in another environment though, so don't do this.
    // .then(() => void 0)
    // .then(() => void 0)
})
```

**Comment by thepuzzlemaster** [comment]
@ph-fritsche thanks for the added context. I read through that blog post, and [this thread](https://github.com/testing-library/react-testing-library/issues/1061) was also fairly helpful. 

I can see how the nested `onInitiate()` promise adds a delay to my source code.

And as you suggest, changing my code to this:
`await act(async () => jest.advanceTimersByTime(1000))` does make my act warning go away.

I wasn't entirely sure if your comments meant this was the right thing to do, or should be avoided?
When you say `"// This hides the issue in the codesandbox environment"`, is it just masking the issue, or actually addressing the warning correctly?

And when you say `"// Might need any other number of microtasks in another environment though, so don't do this"`, is that about returning a resolved promise in my act() call, or is that just about adding the extra promise resolutions beyond the first one.

I guess the thing I'm still not entirely clear on, is should I be adjusting my product code to make this more testable? Or is the approach here of adding a promise resolution inside my act() call the appropriate way to address this warning? Based on my (potentially incorrect) understanding, making my act an `async` function just pushes the warning one step down the road. And if I had another promise resolution in my source code, I'd be back in the same place?

In your blog post, you fix the issue by adding `waitFor()`s around your expectations, to allow the state updates to occur within those. Is that expected that me adding `waitFor()`s around my expectations about my spies returning does *not* address the state-updates in the same way?

**Comment by ph-fritsche** [comment]
Just returning any promise is just masking the issue. It works with pushing it to the next microtask here, but it might fail when you run the same test in a slightly different environment. There you might need to await any other number of additional microtasks, which makes this a randomly working workaround™.

The correct way to fix with is to create a promise that resolves when the state update is applied.
Fake timers complicate this a little bit.

```js
await waitFor(() => expect(screen.getByRole('checkbox')).toBeChecked(), {
  timeout: 10000, // Allow the callback to run ten times
  interval: 1000, // Increase the interval
})
```

**Comment by louis-young** [comment]
I think @ph-fritsche hit the nail on the head [here](https://github.com/testing-library/user-event/issues/1104#issuecomment-1460005394) 🚀 

I experienced _lots_ of erroneous `act` warnings after updating `@testing-library/react` to version 14.

```json
  "@testing-library/react": "^14.0.0",
  "@testing-library/user-event": "^14.4.3",
 ```
 
I'm assuming this is due to `@testing-library/react` depending on `@testing-library/dom` version ^9.0.0, and `@testing-library/user-event` having a peer dependency on `@testing-library/dom` version >=7.21.4. This lead to `@testing-library/dom` resolving to version 8.11.1.

```json
  "node_modules/@testing-library/react": {
    "version": "14.0.0",
    "resolved": "https://registry.npmjs.org/@testing-library/react/-/react-14.0.0.tgz",
    "integrity": "sha512-S04gSNJbYE30TlIMLTzv6QCTzt9AqIF5y6s6SzVFILNcNvbV/jU96GeiTPillGQo+Ny64M/5PV7klNYYgv5Dfg==",
    "dev": true,
    "dependencies": {
      "@babel/runtime": "^7.12.5",
      "@testing-library/dom": "^9.0.0",
      "@types/react-dom": "^18.0.0"
    },
    "engines": {
      "node": ">=14"
    },
    "peerDependencies": {
      "react": "^18.0.0",
      "react-dom": "^18.0.0"
    }
  },
  "node_modules/@testing-library/user-event": {
    "version": "14.4.3",
    "dev": true,
    "license": "MIT",
    "engines": {
      "node": ">=12",
      "npm": ">=6"
    },
    "peerDependencies": {
      "@testing-library/dom": ">=7.21.4"
    }
  }
```

Overriding `@testing-library/dom` to version ^9.0.1 fixed all of the erroneous `act` warnings I was experiencing as mentioned [here](https://github.com/testing-library/user-event/issues/1104#issuecomment-1460026163).

```json  
  "overrides": {
    "@testing-library/dom": "^9.0.1"
   }
 ```
 
 Thanks for the awesome library. Hopefully this helps someone else.

**Comment by Chrissmith1991** [comment]
I think this may not be resolved for User Event.
``` typescript
// Temporary workaround for testing library's act() not working with userEvent
export async function actWrappedUserEvent(event: Promise<void>): Promise<void> {
  return await act(async () => {
    await event;
  });
}
await actWrappedUserEvent(user.click(submitButton));
```
the error isnt causing any tests to fail but the only way ive keep the error from bubbling up is to wrap it in an act

**Comment by robinelvin** [comment]
I suddenly started getting this issue in a previously clean project. I'm using Yarn v3 PnP with node_modules on disk.
I checked for duplicate versions of `@testing-library/dom` being installed and found 2 versions. I upgraded the package that was pulling in the older version and verified I now only had a single version. I was still getting warnings about using `act(...)` on every single test.

A clue was my CI server was not showing these warnings. In the end I had to do:

```shell
$ rm -rf node_modules yarn.lock
$ yarn install
```

And now my tests are working without warnings again. So I can only assume that even though Yarn thought it had cleaned everything up I still had conflicting versions on disk being referenced.

**Comment by Swappea** [comment]
> Overriding `@testing-library/dom` to version ^9.0.1 fixed all of the erroneous `act` warnings I was experiencing as mentioned [here](https://github.com/testing-library/user-event/issues/1104#issuecomment-1460026163).
> 
> ```json
>   "overrides": {
>     "@testing-library/dom": "^9.0.1"
>    }
> ```

This worked for me, we are using yarn and we had to add resolutions instead of overrides.

Thank you @louis-young 

```json
"resolutions": {
    "postcss": "^8.3.6",
    "@testing-library/dom": "^9.0.1"
  }
```
