### ISSUE TITLE
userEvent.click doesn't trigger the onPressIn event

### ISSUE THREAD

**Issue by marioviana** [testing-library/user-event#1105]
### Problem description

```js
test('Component can be clicked', async () => {
    const onPress = jest.fn();
    const {getByTestId} = render(
      <TouchableOpacity onPressIn={onPress} testID="myPressable">
        <span>HEY</span>
      </TouchableOpacity>,
    );
    const pressable = getByTestId('myPressable');
    await userEvent.click(pressable);
    expect(onPress).toHaveBeenCalled();
  });
```

Using `onPress` with `TouchableOpacity` would pass as it's called, but using `onPressIn` would cause this test to fail.

### Suggested solution

Should be possible to simulate the `onPressIn`, that would be possible by having another event like `userEvent.press` or an event argument tied to the click event such as `pressIn` and `pressOn` (`userEvent.click(element, 'pressIn')`)

### Additional context

Is there any way to achieve this currently?

**Comment by marioviana** [comment]
For those who are struggling with this issue, I ended up mocking the component to always use onPress on tests.

The library should support the `onPressIn` event to be fired anyway, but this a possible workaround:
```js
jest.mock('react-native', () => {
  const ReactNative = jest.requireActual('react-native');
  return {
    ...ReactNative,
    TouchableOpacity: ({onPress, onPressIn, ...props}: TouchableOpacityProps) => {
      const handlePress = onPressIn || onPress;
      return <ReactNative.TouchableOpacity onPress={handlePress} {...props} />;
    },
    TouchableWithoutFeedback: ({onPress, onPressIn, ...props}: TouchableWithoutFeedbackProps) => {
      const handlePress = onPressIn || onPress;
      return <ReactNative.TouchableWithoutFeedback onPress={handlePress} {...props} />;
    },
  };
});
```

**Comment by ph-fritsche** [comment]
`@testing-library/user-event` only supports [DOM events](https://developer.mozilla.org/en-US/docs/Web/Events?retiredLocale=de#event_listing).
