### ISSUE TITLE
Is userEvent.click asynchronous or not?

### ISSUE THREAD

**Issue by SaavanNanavati** [testing-library/user-event#1117]
### Expected behavior

The TS definition for userEvent.click is the following:
```
declare function click(element: Element, init?: MouseEventInit, { skipHover, clickCount, skipPointerEventsCheck, }?: clickOptions & PointerOptions): void;
```

indicating it's synchronous

### Actual behavior

The actual code seems to be async:
https://github.com/testing-library/user-event/blob/main/src/convenience/click.ts

```
export async function click(this: Instance, element: Element): Promise<void> {
  const pointerIn: PointerInput = []
  if (!this.config.skipHover) {
    pointerIn.push({target: element})
  }
  pointerIn.push({keys: '[MouseLeft]', target: element})

  return this.pointer(pointerIn)
}
```

So is it async or synchronous?

**Comment by eostrom** [comment]
Where did you find the synchronous TS definition?

In the package I have installed (14.4.3), the declaration is:

```ts
export declare function click(this: Instance, element: Element): Promise<void>;
```

The TS declaration you quoted kind of looks like [the one from v13.](https://testing-library.com/docs/ecosystem-user-event/) Maybe you have two versions installed?

**Comment by FrozenFury** [comment]
Hmm, that is certainly possible. But I'm still wondering whether the code is actually async? There is no `await` being used inside the function so why bother returning a void Promise at all?

**Comment by eostrom** [comment]
Looks like `click` calls [`pointer`](https://github.com/testing-library/user-event/blob/main/src/pointer/index.ts#L36) and returns its result. `pointer` uses `await` and therefore returns a promise, so `click` returns a promise too. I'd say `async` here isn't enabling direct use of `await` *within* `click`. It's just a way of declaring that this function returns a promise and can (and probably should) be awaited by the caller.

(Is it the best way? That's a code style question for the project, I'm just a guy who stumbled into this issue while he was looking for the answer to a different question.)

But I think the answer to your question is yes, it's asynchronous, in that it returns a promise and callers should wait for it to be resolved.
