### ISSUE TITLE
.type doesn't work with vue-testing-library

### ISSUE THREAD

**Issue by afontcu** [testing-library/user-event#119]
Hi! First of all, thank you for your work on this repo!

I wanted to highlight that the current implementation of `.type()` isn't working when used with `vue-testing-library`.

Not quite sure why yet thou, I believe it has something to do with using `fireEvent.change` instead of `fireEvent.input` [here](https://github.com/testing-library/user-event/blob/master/src/index.js#L166). I have passing tests using `fireEvent.input`, and the minute I change them to use `.change`, they start failing. Is there any reason to prefer change event over input?

Thanks!

**Comment by Gpx** [comment]
Hi, `user-event` is only tested with React at the moment for the simple reason that it's what I use at work. I would be keen to add tests that cover other frameworks.

I think the difference between `input` and `change` is that in React you have two separate handlers for them: `onInput` and `onChange`. I also never seen anyone using `onInput`.

I don't really know how it works in Vue-land. Is it possible that you have this distinction too?

**Comment by afontcu** [comment]
Hi! Thanks for answering.

Vue also maps native events such as Input and Change. However, `input` is the most widely used in Vue world. It is even used in the built-in [v-model](https://vuejs.org/v2/guide/forms.html) feature, which is just syntax sugar to create a two-way binding of an input value.

Main difference (AFAIK) is that change event triggers when the element has finished changing (when it loses focus), while input event triggers every time a value is modified. You can see it in [this Codesandbox](https://codesandbox.io/s/o1j015y5p5).

**Comment by Gpx** [comment]
Since we're trying to simulate a browser I think we should fire both events instead of replacing it.
Right now `type` is firing `keydown -> change -> keyup`. We should change it to be `keydown -> input -> change -> keyup`

**Comment by afontcu** [comment]
AFAIK (and correct me if I'm wrong), `change` should only be emitted _after_ moving away from the input.


> Note: The input event is fired every time the value of the element changes. This is unlike the change event, which only fires when the value is committed, such as by pressing the enter key, selecting a value from a list of options, and the like. ([source](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event))


If that's the case, would it make sense send an `input` event for every char, and then send a `change` event with the whole string?

`keydown`
`input "h"`
`keyup`
`keydown`
`input "i"`
`keyup`
`change "hi"`

**Comment by Gpx** [comment]
> AFAIK (and correct me if I'm wrong), change should only be emitted after moving away from the input.

That's what happens for native HTML but not in React. I think in React `change` and `input` are behaving the same except React will fire both of them

**Comment by afontcu** [comment]
Oh wow you're right, I didn't know that, thanks.

I feel Vue works similary to native HTML (see [demo](https://codesandbox.io/embed/o1j015y5p5)) so yeah, so a `input` event would do the trick :)

I'll happily submit a PR if you feel that that's the apropiate change (no pun intended).

**Comment by Gpx** [comment]
You man a PR to replace the vent or to add it?

**Comment by afontcu** [comment]
_(sorry for the late response!)_

Whatever works best in both frameworks. I guess we could add it, so the workflow would be `keydown -> input -> change -> keyup`.

**Comment by Gpx** [comment]
Do you think you could add tests for Vue? Basically, porting the ones we have but render Vue components instead of React. I think we need to have those in place before we start thinking about cross-library support

**Comment by afontcu** [comment]
Makes total sense! Will work on that :)

**Comment by Gpx** [comment]
Thank you 👍

**Comment by calebeby** [comment]
> Whatever works best in both frameworks. I guess we could add it, so the workflow would be `keydown -> input -> change -> keyup`.

Can I open a PR to add this? It doesn't look like anyone else got to it yet :eyes:

**Comment by afontcu** [comment]
Hi @calebeby! As @Gpx suggested, I opened a (draft) PR to add Vue tests #129 to `user-event`, which will create a solid starting point to develop cross-library features :)

**Comment by calebeby** [comment]
@afontcu Awesome! I have local changes that make the `input` and `change` events fire like they do when a user types, so I'll pull in your new tests soon!

I might also add tests for vanilla JS. I'm using Preact, which, unlike React, actually adds a `change` event listener when you use `onChange`. So AFAIK Preact will work the same as Vue does :heavy_check_mark: 

> I think we need to have those in place before we start thinking about cross-library support

LOL I missed this line while I was skimming through this issue :see_no_evil:

I was able to modify this library locally to make `onInput` work correctly in Preact (tests on `master` still pass :white_check_mark:):
- Replace `fireEvent.change` references with `fireEvent.input` within the `type` function
- At the end of the `type` method after all the letters are typed in, attach a `blur` listener to the element. When that fires, call `fireEvent.change`. This _slightly_ differs from native browser behavior because it fires regardless of whether the contents are different.

**Comment by mxstbr** [comment]
@calebeby I am also using Preact, any chance that PR is somewhere? :pray:

**Comment by calebeby** [comment]
@Gpx do you think you could review [my 4 open PR's](https://github.com/testing-library/user-event/pulls?utf8=%E2%9C%93&q=is%3Aboth+is%3Apr+author%3Acalebeby+sort%3Aupdated-desc) pretty soon? I'd love to continue moving forward with making `user-event` compatible with all libraries :tada: 

@mxstbr Opened PR for that just now :heavy_check_mark: https://github.com/testing-library/user-event/pull/141

**Comment by afontcu** [comment]
I guess this can be closed now :)

**Comment by dilraj-vidyard** [comment]
I am still having issues typing things into `input`s and `editiblecontent`s.

I made a comment here: https://github.com/testing-library/user-event/pull/141#issuecomment-2508613218

These are the packages I'm using to do typing and to render my component:

```js
import userEvent from '@testing-library/user-event';
import { mount } from '@vue/test-utils';
```
