### ISSUE TITLE
userEvent.click on <button type="submit" /> does not trigger form onSubmit() method

### ISSUE THREAD

**Issue by cjOne7** [testing-library/user-event#1196]
### Reproduction example

https://codesandbox.io/p/devbox/uservent-click-test-showcase-qdnhsg?file=%2Fsrc%2F__tests__%2FMultistemForm.test.tsx%3A29%2C1

### Prerequisites

1. Render a `<form />` with a `<button type="submit />` inside.
2. Attempt to submit the form using `userEvent.click()`.
3. Forbid to pass onSubmit method as props.

### Expected behavior

Expected the form to be submitted, its onSubmit() handle method will be called, button with text `Previous` will be appeared and test passed.
To run test just type `npm run test` in the console
![image](https://github.com/testing-library/user-event/assets/61429321/926683e4-9c66-4218-982b-856f613decec)

### Actual behavior

Test failed, button with text `Previous` didn't find, because form has not been submitted. But this example works perfectly:
```
    await waitFor(() => {
      fireEvent.submit(getByText("Previous"));
    });
```

### User-event version

14.5.2

### Environment

"react-dom": "18.2.0",
"react": "18.2.0",

"@testing-library/jest-dom": "6.4.2",
"@testing-library/react": "14.2.1",
"@testing-library/user-event": "14.5.2",
"@types/react-dom": "18.2.19",
"@types/react": "18.2.55",
"@vitejs/plugin-react": "4.2.1",
"@vitest/coverage-v8": "1.2.2",
"jsdom": "24.0.0",
"typescript": "5.3.3",
"vite": "5.1.0",
"vitest": "1.2.2"

### Additional context

This issue has been reported before https://github.com/testing-library/user-event/issues/1032

**Comment by cjOne7** [comment]
Still waiting for fix...

**Comment by aKaradzhov97** [comment]
I also faced this issue. And for some reason, `fireEvent.submit()` doesn't help in my case.

**Comment by ph-fritsche** [comment]
![image](https://github.com/testing-library/user-event/assets/39068198/2b3c08a2-a22b-4aa3-a053-79e2567acfb8)
The test in the reproduction example passes :thinking:

**Comment by cjOne7** [comment]
![image](https://github.com/testing-library/user-event/assets/61429321/138dfc26-20b0-4090-bc6f-51e881cb6a7d)
![image](https://github.com/testing-library/user-event/assets/61429321/50d2e3b4-888a-47f5-9663-34f9e775a737)
![image](https://github.com/testing-library/user-event/assets/61429321/356f4da1-53a2-48c4-a231-8891b23516c3)

it's weird, but it really passed
