### ISSUE TITLE
Ability to interact with <select multiple> tags

### ISSUE THREAD

**Issue by michaellasky** [testing-library/user-event#123]
Moving https://github.com/testing-library/react-testing-library/issues/375 over to the proper place.  

I still plan to take a crack at an implementation.  Will submit a pull request for review when I can, unless someone else gets to it first.

**Comment by michaellasky** [comment]
#126 

Added Draft Pull request with a basic proposed implementation

**Comment by Gpx** [comment]
Thanks!

**Comment by afontcu** [comment]
I believe this issue can be closed thanks to #130?

**Comment by Gpx** [comment]
Yep, thanks @michaellasky and @afontcu
