### ISSUE TITLE
Allow for non-fixed version of @testing-library/dom

### ISSUE THREAD

**Issue by calebeby** [testing-library/user-event#135]
Hi, thanks for this package, it's pretty awesome :eyes: :tada: 

I was wondering if the `package.json` could be updated to have a semver _range_ for the `@testing-library/dom` dependency, rather than a fixed version: https://github.com/testing-library/user-event/blob/master/package.json#L56

Suggestion:

```diff
-    "@testing-library/dom": "5.1.1"
+    "@testing-library/dom": "^5.1.1"
```

This way I don't have to have multiple versions of `@testing-library/dom` installed, and you don't have to constantly update the version in your `package.json` :smile: 

Happy to submit a PR if you want

**Comment by Gpx** [comment]
I wonder if peer dependencies would fix this. @kentcdodds any idea?

**Comment by kentcdodds** [comment]
I think that would make a lot of sense.

**Comment by Gpx** [comment]
Ok, I've never done it so I need to take a look at the documentation first. Unless @calebeby wants to give it a try

**Comment by calebeby** [comment]
Happy to!
