### ISSUE TITLE
Include typings folder in npm publish.

### ISSUE THREAD

**Issue by parkerziegler** [testing-library/user-event#140]
Thanks for a helpful lib! It appears that the typings folder is not actually making it to `npm`, so the TS support isn't working. You can see that the `typings` folder isn't there by checking it out on `runpkg`: https://runpkg.com/?@testing-library/user-event@4.1.0/dist/index.js. Compare this to say, `@testing-library/react`, whose `typings` folder _is_ published to `npm`: https://runpkg.com/?@testing-library/react@8.0.5/dist/index.js. Since there's no `.npmignore` nor a `files` field in the `package.json`, I believe everything that's on GitHub is ending up published to `npm` (which is strange that `typings` wouldn't also make it in this case), which even means your tests and source are getting bundled in folks' `node_modules` 😬 Finally, it appears the `package.json` version is out of lockstep with the `npm` published version. Happy to make a PR to help with these things if you like! Thanks again for a helpful lib.

**Comment by Gpx** [comment]
Hi there. I'm actually not the one maintaining the types. They are published from https://github.com/DefinitelyTyped/DefinitelyTyped. I have nothing against migrating the code to TS and export types directly from here.

Would you be interested in doing the porting?

**Comment by calebeby** [comment]
@Gpx Why are the typings both in this folder in this repo: https://github.com/testing-library/user-event/blob/master/typings/index.d.ts as well as on DefinitelyTyped?
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__user-event

**Comment by parkerziegler** [comment]
@Gpx I agree with @calebeby above. It's totally fine if the types are maintained on DefinitelyTyped! There's also no need to port the entire lib to TS. It's more that folks' tend to _either_ ship types directly with their lib _or_ rely on the types on DefinitelyTyped. In this case, you have the types in source here, but don't ship them along with the lib, and _also_ rely on DefinitelyTyped. It'd be great to have one place where they were located so it was clear to end users where we should expect to get our types.

I'm happy to make a PR w/ a sample `.npmignore` you could use to ship types with the repo (and that would exclude your tests from being published) if that sounds useful.

**Comment by calebeby** [comment]
> There's also no need to port the entire lib to TS

You are right that there is no need, but if @Gpx is onboard with this I'm willing to do it

**Comment by Gpx** [comment]
😆 I actually forgot we added types in here.
I think it makes more sense if we maintain the types in here, it's probably going to be easier to maintain.

I would start with exporting the file we currently have and making sure it's up-to-date.

Does it make sense?

**Comment by weyert** [comment]
I think you changed on this opinion? After noticing the change in the react / dom package? Where are removing it?

**Comment by Gpx** [comment]
Let's see how the discussion on https://github.com/testing-library/react-testing-library/pull/437 goes

**Comment by calebeby** [comment]
@Gpx I think this issue can be closed. The typings folder _is_ being published to npm:
https://unpkg.com/browse/@testing-library/user-event@4.2.0/typings/index.d.ts

@parkerziegler you were looking at 4.1.0 which was before the typings were added to this repo. The typings were published in 4.2.0: https://github.com/testing-library/user-event/pull/134
