### ISSUE TITLE
React onChange handler not called when type is used

### ISSUE THREAD

**Issue by jackgeek** [testing-library/user-event#149]
Problem:
The type method does not cause the React onChange handler to be called.

This can be seen in this sandbox: https://codesandbox.io/s/zealous-sanderson-zqrg5?fontsize=14&module=%2Fsrc%2F__tests__%2FtypeTestThatFails.test.js&previewwindow=tests

Expected behaviour:
The onChange handler on the element being typed into is fired.

Potential solution:
I have managed to work around this using the react-trigger-change module.  See this sandbox: https://codesandbox.io/s/zealous-sanderson-zqrg5?fontsize=14&module=%2Fsrc%2F__tests__%2FtypeTestWithWorkaround.test.js&previewwindow=tests

**Comment by jackgeek** [comment]
Happy to do a PR to add the react-trigger-change module but that module is quite old and hasn't been updated.  Not sure if you want to introduce it to your project?

**Comment by Gpx** [comment]
I think you might have another error. I tried your exact code in my machine and it works. We actually have a very similar test in our codebase too https://github.com/testing-library/user-event/blob/master/__tests__/react/type.js#L9-L21

I know codesandbox sometimes doesn't play nicely with RTL, could that be the issue?

**Comment by jackgeek** [comment]
I originally encountered the problem in testing my company's app.  I re-created the issue on code-sandbox.

I'll take a look at that test to see if I can see anything different.

**Comment by jackgeek** [comment]
I should say that we are using React 15.4.1.  We are in the process of upgrading to React 16.  I will upgrade the code sandbox and see if it still occurs with latest React

**Comment by jackgeek** [comment]
OK I can confirm it is working with the latest version of React:

https://codesandbox.io/s/youthful-wiles-r3ybv

Appears to be just an issue with React 15.4.1.

We have a working work around and we are upgrading soon so please feel free to close this ticket.

Sorry to bother!
