### ISSUE TITLE
userEvent.type should provide valueAsNumber and valueAsDate properties.

### ISSUE THREAD

**Issue by pietmichal** [testing-library/user-event#157]
When using `userEvent.type` on any input, it receives `value` property but `valueAsNumber` and `valueAsDate` are undefined while accessed.

When running the code in the browser, these properties are defined.

spec: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

**Comment by weyert** [comment]
Hmm, never even knew these properties exist. I assume they got introduced when the new special input types got added to the spec? 

More details: https://html.spec.whatwg.org/multipage/input.html#dom-input-valueasnumber

Feel free to make a PR for it :)

**Comment by Gpx** [comment]
Not sure that's the responsibility of `user-event`. If I understand it correctly you read those from the `input`. I think it's something jsdom should implement.

**Comment by weyert** [comment]
Well, aren't we creating our own events in the `type`-method via `fireEvent` so we would need to populate not only `value` but also these two? 

See: https://github.com/testing-library/user-event/blob/e1c4c1a51cc76fb78f3f3f1f5cf62f9d082b86d1/src/index.js#L211

**Comment by Gpx** [comment]
Yeah, but what I'm saying—unless I got it wrong—those properties are coming from the `<input>` not from the event. Am I wrong?

**Comment by weyert** [comment]
Yes, you might be right. Looks like it’s not supported by Jason. Can’t find it in the IDL files

**Comment by weyert** [comment]
Not sure, how to progress. Raise a ticket with jsdom?
