### ISSUE TITLE
should type be constrained by maxLength?

### ISSUE THREAD

**Issue by afontcu** [testing-library/user-event#161]
Is `maxLength` an attribute `user-event` should take into account?

If so, the following test should pass:

```js
// __tests__/vue/type.js

test("maxlength", () => {
  const input = jest.fn();

  const maxlength = 10;

  const { getByTestId } = renderComponent('input',
    { input },
    { maxlength }
  );

  const text = "Hello, world!";
  userEvent.type(getByTestId("input"), text);

  expect(input).toHaveBeenCalledTimes(maxlength);
  expect(getByTestId("input")).toHaveProperty("value", text.slice(0, maxlength));
});
```

I'll be happy to implement it if you think it makes sense.

**Comment by afontcu** [comment]
As far as I can tell, both are failing ("hello world!" is 13 characters long, so event is being fired 13 times).

**Comment by weyert** [comment]
Yes, the type-helper method doesn't check the `maxLength`-attribute this time. Personally, I have more issues with the lack of diacritics support or special characters like {tab} or {shift} etc. I hope I need this requirement soon at work so I can work on it. Only it is a bit problematic because of all the different keyboard layouts available throughout the world.

**Comment by weyert** [comment]
Sounds good to me. I can work on something tomorrow at work

**Comment by weyert** [comment]
Woops, got sidetracked by a hackaton at work. I will pick this up on Monday :)

**Comment by carlos-cne** [comment]
Here still not working.
```javascript
it('Should input have a 60 max length even try to add more', async () => {
    render(<CreateBanner />);

    const inputValue = screen.getByPlaceholderText(/Título do banner/);

    await userEvent.type(
      inputValue,
      'A text that has more than sixty characters to test input limit'
    );

    expect(inputValue.value).toHaveLength(60);
  });
});
``` 
If I'm doing wrong, please let me know the right way.

**Comment by gautamkrishnar** [comment]
Working fine for me. I am using the version 8.1.0 of the user-event library.

**Comment by kentcdodds** [comment]
This should be working properly now.
