### ISSUE TITLE
click sequence of events is different than browsers

### ISSUE THREAD

**Issue by patricklafrance** [testing-library/user-event#176]
I believe the sequence of events for click (and dblClick) is different that the one in browsers.

With this jsfiddle: https://jsfiddle.net/3r9oczkg/

We can see by:

1- focusing in the input
2- click on item 2

That after clicking on item 2 the blur / focus sequence is:

1- input blur
2- item 2 focus
3- item 2 click

Which means that the focusedElement blur event should happen BEFORE the item 2 focus and click events.

Fixing this would be very convenient for Components that rely on the right focus / blur order!

Thank you

Patrick

**Comment by Gpx** [comment]
This should be fixed in the latest version, please give it a try
