### ISSUE TITLE
click should also trigger focusin and focusout

### ISSUE THREAD

**Issue by patricklafrance** [testing-library/user-event#177]
It would be awesome if click (and dblClick) also support `focusin` and `focusout`.

Event if they are not currently part of React: https://github.com/facebook/react/issues/6410

You can still use it with document.addEventListener.

Calling `focusin` right after `element.focus()` and `focusout` right after `fireEvent.blur(focusedElement)` seems to work well.

Thank you,

Patrick

**Comment by Gpx** [comment]
This should be fixed in the latest version, please give it a try
