### ISSUE TITLE
Support "enter" keydown on button

### ISSUE THREAD

**Issue by patricklafrance** [testing-library/user-event#179]
In a browser, enter keydown trigger the click event of the button.

It would be nice if the user-event library support this behavior.

You can test the browser behavior here: https://codesandbox.io/s/jovial-glitter-jy883?from-embed

A naive implementation would be to add a `keyDown` function to user-event:

```
    keyDown(element, options) {
        fireEvent.keyDown(element, options);

        if (element.tagName === "BUTTON") {
            fireEvent.click(element);
        }
    }
```

Thank you,

Patrick

**Comment by weyert** [comment]
Hmm, but here you aren't testing for the `enter`-key but now everything can trigger the click event?

**Comment by nickmccurdy** [comment]
Does that work on all elements though? Or just form controls?

**Comment by weyert** [comment]
Good question, I would assume it's a typical button behaviour?

**Comment by nickmccurdy** [comment]
I wrote a test and got some interesting results: https://codepen.io/nickmccurdy/pen/RwweGxG?editors=1010

To summarize, all buttons (using `<button>` or `<input type="some button type">`) except radio buttons fire click events when return is hit. Radio buttons only fire click events when space is hit.

**Comment by weyert** [comment]
Okay, thanks for testing this @nickmccurdy!
Thinking now how to best way to implement this 🤔

**Comment by jamesonhill** [comment]
This would be super helpful for me as well, due to this issue w/ fireEvent. https://github.com/testing-library/react-testing-library/issues/551

In my case, I have to support a submit-like event for textarea's onKeyPress for "Enter".

**Comment by kentcdodds** [comment]
This is now supported with `userEvent.type(button, '{enter}')`

**Comment by jamesonhill** [comment]
@kentcdodds Awesome! Thanks so much :)

**Comment by neaumusic** [comment]
Regarding `'{enter}'` it looks like they're still just using `fireEvent.keyDown` internally:

https://github.com/testing-library/user-event/blob/4bbb4b9a6e33641bb2bec3830b6f97e373e29541/src/type.js#L109

**Comment by Phebonacci** [comment]
> This is now supported with `userEvent.type(button, '{enter}')`

It appears that this will also trigger the onClick event of the button before the keypress is triggered. So if we pass the same callback for both onClick and onKeydown, it will be called twice.

**Comment by ahayes91** [comment]
Feel free to correct me if there's another way to do it, but I found `userEvent.type(button, '{enter}')` didn't work for me today to fire the onClick event on a button (maybe this has changed since this ticket was implemented). 

I stripped it down to a regular old `button` and found focusing the button and using `userEvent.keyboard('{enter}')` was the way to do it (still on user-event v 13.5, FYI):

```javascript
  it("Using Enter key on regular button should fire onClick event", async () => {
    const mockOnClick = jest.fn();
    render(<button onClick={mockOnClick}>Button</button>);
    const button = screen.getByRole("button");
    button.focus();
    userEvent.keyboard("{enter}");
    await waitFor(() => expect(mockOnClick).toHaveBeenCalledTimes(1));
  });
```

**Comment by chrisspadanuta** [comment]
Where is userEvent imported from?

**Comment by jamesonhill** [comment]
> Where is userEvent imported from?

It's the default export from `@testing-library/user-event`

**Comment by Illutax** [comment]
> 

FYI: `.focus()` is not necessary when you interacted with the input before e.g. typed something into a text input.

**Comment by neaumusic** [comment]
There's something fishy about user-event enter keypress, `which` is still `0` and I noticed `charCode` is assigned in a one-off line, somewhere around `dispatchUIEvent` for `keydown`
