### ISSUE TITLE
Support for unselect options?

### ISSUE THREAD

**Issue by malcolm-kee** [testing-library/user-event#180]
`selectOptions` currently force `selected` to `true` as per coded at [here](https://github.com/testing-library/user-event/blob/master/src/index.js#L90).

Does it make sense to support `toggleOptions` so we can test for unselect as well?

Let me know if you need a hand.

**Comment by Gpx** [comment]
This sounds like a reasonable use case. Do you want to take a stab at it?

**Comment by malcolm-kee** [comment]
@Gpx  Sure. Will work on it.

**Comment by malcolm-kee** [comment]
@Gpx I have some doubt on the desired behavior. 

As a user, single-option select is not something that we can "unselect". Should `toggleOptions` used only for multiple select?

**Comment by Gpx** [comment]
I would say yes
