### ISSUE TITLE
Feat request: Add blur

### ISSUE THREAD

**Issue by yuritoledo** [testing-library/user-event#189]
Just to add the `fireEvent.blur()`

:)

**Comment by babramczyk** [comment]
Just to add onto this, here's a codesandbox that I would expect to work with this library, but doesn't because of lack of blur:

https://codesandbox.io/embed/headless-cloud-o3obp?fontsize=14&hidenavigation=1&previewwindow=tests&theme=dark

**Comment by Gpx** [comment]
Why do you need this if `fireEvent.blur()` exists?

I'm closing the issue but feel free to comment and we can reopen it we can come up with a good use case.

**Comment by yuritoledo** [comment]
Hi,

I think should be good, all kind of interaction in only one package.
To avoid multiple imports

**Comment by Gpx** [comment]
We might move user-event to the main package at some point but for now, it's better to keep the separated

**Comment by yuritoledo** [comment]
great.

**Comment by j-u-p-iter** [comment]
Hey, hey guys :) Hope you're doing well!

Why not just to move everything related to interactions to the user-event package and after it's ready to be merged with the main library - do it. IMO it's always great to have one common thing for one concrete purpose in terms of consistency.

**Comment by ph-fritsche** [comment]
Please keep issues separate so we can find and reference them easily.
@j-u-p-iter I moved your comment to https://github.com/testing-library/user-event/discussions/669

**Comment by ErlanBazarov** [comment]
fireEvent.blur() only triggers onBlur event, right? It doesn't actually remove focus from the element. We need userEvent.focus that would actually behave realistically

**Comment by ph-fritsche** [comment]
@ErlanBazarov `userEvent` is all about simulating user interaction. The occurring `blur` is just something that happens along the way.
Try "clicking somewhere else" like a user would do. :smiley:

**Comment by ph-fritsche** [comment]
Why not?
```js
userEvent.click(document.body) // move the focus away
```

**Comment by yuritoledo** [comment]
Is it not semantic.

Maybe it can be clear for who wrote it, but not for other developer or yourself in future.

**Comment by ph-fritsche** [comment]
I'm sorry, but I fail to understand the issue or the proposed solution here.
If you want to simulate that a user moves the focus away by clicking somewhere what could possibly be semantically closer than clicking somewhere?

If you want to test against an implementation detail, i.e. the `blur` event, there is already `fireEvent.blur(element)` for this.
If you want to just perform the blur, you could also keep it even simpler and just go:
```js
element.blur()
```

So which abstraction should a `userEvent.blur` API provide?
All our APIs strive to be readable as "simulate that a user does...", but a user can not perform `blur` on a specific element.

**Comment by yuritoledo** [comment]
I disagree. The user can perform the blur event pressing tab for instance.

I think should be nice to have the `.blur()` in this library just to group all the user behavior in one package, just for the DX.

If I do `userEvent.click()` or `userEvent.type()`, why not `userEvent.blur()` ? instead of `fireEvent.blur()`
In other words: "If I use useEvent for clicking, typing, and whatever, why not using it for blur too?"

**Comment by ph-fritsche** [comment]
That is exactly the problem with such an API in this package. The user can trigger a `blur` e.g. by pressing `[Tab]`.

So should your proposed `userEvent.blur()` API trigger a `keydown` event for the Tab key on the element and a `keyup` event for the Tab key on the next element in tab order?
Where should the focus be moved?

The user could also press `[Alt]+[Tab]` and the active element would stay the same, but a `blur` event would occur as well as a `focus` event when the user switches back.

How do we determine the correct behavior? Currently our standard is to perform the action described by the API call in the browser. But I fail to see what the reference action in the browser should be, that I would perform to determine if our implementation is correct.

**Comment by RachitSharmaHS** [comment]
If `userEvent.click(document.body)` is not semantic enough, how about `userEvent.keyboard('{esc}')`. It is a direct user action (unlike `blur`) and you wouldn't use to to shift focus explicitly to something else.

**Comment by Saddage** [comment]
Hey, I've just stumbled upon this issue. What was the fix for me, without using `fireEvent` was to call `userEvent.tab()`. I think it is ok, as the focused element uses its focus due to the user clicking the `Tab` button on their keyboard.

**Comment by ScubaDaniel** [comment]
> Why not?
> 
> ```js
> userEvent.click(document.body) // move the focus away
> ```

This doesn't work for me. It just times out with user-event version 14.

**Comment by ph-fritsche** [comment]
@ScubaDaniel In `v14` all interaction APIs return a promise that you should `await`.

If you use fake timers in your test suits, have a look at https://testing-library.com/docs/user-event/options/#advancetimers
