### ISSUE TITLE
Type function isn’t awaiting

### ISSUE THREAD

**Issue by renanmav** [testing-library/user-event#195]
Hi! 

I'm trying to simulate a user typing with `userEvent.type` as follows:
```ts
const startDateInput = getByTestId('startdate-input');

const ticketData = {
  startDate: '12/12/2020',
};

await userEvent.type(startDateInput, ticketData.startDate);

expect(await waitForElement(() => startDateInput)).toHaveValue(ticketData.startDate);
```

but I'm getting this:

```
expect(element).toHaveValue(12/12/2020)

Expected the element to have value:
      12/12/2020
Received:
      02/2_/____

> 49 |     expect(await waitForElement(() => startDateInput)).toHaveValue(ticketData.startDate);
                                                              ^
```

Any hints?

| Package                     | Version |
|-----------------------------|---------|
| @testing-library/jest-dom   | ^4.2.4  |
| @testing-library/react      | ^9.3.3  |
| @testing-library/user-event | 7.1.2   |

**Comment by renanmav** [comment]
Doing the assertion this way solved the problem, so the `type` function isn’t awaiting.

```ts
setTimeout(async () => {
  expect(await waitForElement(() => startDateInput)).toHaveValue(ticketData.startDate);
}, 300);
```

**Comment by weyert** [comment]
Try the following: 
`await userEvent.type(startDateInput, ticketData.startDate, { allAtOnce: false});`

We are only doing an await when the `allAtOnce`-flag is set. I guess we could add faux wait(0) when this parameter is `true` to ensure a await is happening.
