### ISSUE TITLE
README needs to be updated for user-event

### ISSUE THREAD

**Issue by maheshjag** [testing-library/user-event#198]
The [`type`](https://github.com/testing-library/user-event#typeelement-text-options) method is [async](https://github.com/testing-library/user-event/blob/master/src/index.js#L176), but the documentation doesn't reflect it.

**Comment by kentcdodds** [comment]
Thanks for the tip! Would you like to [make a pull request](http://makeapullrequest.com)?

**Comment by maheshjag** [comment]
I tried to, but it looks like I don't have enough permissions on this project

**Comment by kentcdodds** [comment]
You need to fork the project. You can watch that free video course I linked to to learn how to do that 👍

**Comment by maheshjag** [comment]
Ah, okay! I usually branch off and then push the branch. Will do so when I get some time to spare.

**Comment by weyert** [comment]
It's only async when you have set a delay though

**Comment by maheshjag** [comment]
@weyert The function is defined as async, so will always return a promise irrespective of whether or not a delay is specified.
