### ISSUE TITLE
userEvent.type() breaks with a number

### ISSUE THREAD

**Issue by wesbos** [testing-library/user-event#215]
Not sure if this is a bug, or as intended, so feel free to close :) 

I I just tried to do this:

```js
await userEvent.type(screen.getByPlaceholderText('Price'), item.price);
```

Where price is a number. That throws the error `TypeError: text.slice is not a function`

running with toString() fixes that:

```js
await userEvent.type(screen.getByPlaceholderText('Price'), item.price.toString());
```

Since the browser would coerce to a string if we were setting a value, should this too? Or should I just always coerce it myself?

**Comment by wesbos** [comment]
I also noticed getBy*() methods expect a string and break similarity - so maybe it's intended? A nicer error message would be good

**Comment by Gpx** [comment]
I'm not sure about this one, I think `type` should only accept a string. If you enter a number it's easy to convert it into a string if it's an integer but with floats it becomes more complex. Should `0.3` become `'0.3'` or `'0,3'`? The same problem applies to decimal separators.
I think it's better to leave these decisions to the person writing the tests.

I'm going to close the issue for now but feel free to comment with your ideas on the topic.

**Comment by wesbos** [comment]
Makes sense! Thanks a lot

**Comment by gap777** [comment]
We're seeing a situation where `type` with a string on a number input doesn't work... the browser wants a number to be entered, *not* a string. Any way to do this?

**Comment by ph-fritsche** [comment]
@gap777 could you please file a new issue with a reproduction example at [codesandbox](https://codesandbox.io)?
