### ISSUE TITLE
Issue with `.type` when maxlength property is not defined on input

### ISSUE THREAD

**Issue by galkn** [testing-library/user-event#217]
It seems that when the maxlength property is not defined on an input component, JS returns a value of -1 for it, which causes `computedText` to be incorrect (specifically the last character is consistently missing). Wondering if anyone else has observed this behavior?

**Comment by Gpx** [comment]
Can you provide a minimal reproducible example for this bug, please? That would help figure out the problem.
I'm going to close the issue meanwhile, feel free to comment
