### ISSUE TITLE
Click event should not blur prevElement if it is parent of current element

### ISSUE THREAD

**Issue by jamesonhill** [testing-library/user-event#225]
I have a basic menu/dropdown use-case where clicking a button toggles showing & hiding a list of elements. If you click outside of the menu, the dropdown should also be hidden. In the contrived repro example below, I use the blur event to accomplish this.

Issue: Since userEvent blurs the previous element before clicking the current element, this causes a false negative in the test case when attempting to close the dropdown by clicking the current element.

Below is a repro example in codesandbox. In the test case, if you open the menu then attempt to re-close it, the blur event will close the menu then the subsequent click event will re-open it. The test case fails, however if you replace the last `userEvent.click` line with `fireEvent.click`, the test passes.

The blur event is not fired w/ a native browser click.

https://codesandbox.io/s/epic-banzai-dlboc

**Comment by Gpx** [comment]
I think we should not fire a blur event if the clicked element has already focus. It shouldn't be hard to fix

**Comment by jamesonhill** [comment]
Thanks!
