### ISSUE TITLE
Document how to delete text with type method

### ISSUE THREAD

**Issue by MattyBalaam** [testing-library/user-event#226]
The change to the type event to append to existing values has broken our tests which are written expecting to replace existing values.

Is it possible to document how to clear/delete existing values? I tried using the `\b` character but this resulted in some very strange behavior (I imagine this is not being translated until the test reporting.)

**Comment by MattyBalaam** [comment]
The only reliable way I have at the moment is to clear using fireEvent. 

One other thing I tried was to use `userEvent.dblClick`to attempt to select all text.

**Comment by bartgryszko** [comment]
A way this library is using in its own test files is by calling `input.value = '';`

https://github.com/testing-library/user-event/blob/38e3c227dd228c6ccc7624683eca3fae119a66e3/__tests__/react/type.js#L194

By calling that, you can basically simulate previous behavior.

If it's really important to test full user interaction, it would require writing custom `selectAll`/`clear` method I guess.

**Comment by ivarprudnikov** [comment]
Slightly related #232

**Comment by kentcdodds** [comment]
🎉 https://github.com/testing-library/user-event/issues/232#issuecomment-640791105
