### ISSUE TITLE
Using babel in a library is super annoying

### ISSUE THREAD

**Issue by Raynos** [testing-library/user-event#229]
Trying to contribute / fork to this library, I ended up deleting all the babel and then doing a tiny replace on `import` and `export` to move it into commonJS.

Since this library is distributed on npm with normal commonJS in `dist/index.js` you could just change `import` / `export` to `require` and `module.exports` and remove the entire build step from this library.

This would make the life of your users a lot simpler.

**Comment by Gpx** [comment]
I'm not sure why babel makes it harder to use this library. The tests are already configured to use babel and the publishing step transipiles automatically.
Can you provide some more details?

**Comment by Raynos** [comment]
I can't remember exactly what issues I was having when trying to contribute to this library and run the tests or publish a fork ( http://npmjs.org/raynos-user-event ).

Either I could not publish working code or I could not get the tests to run.

But replacing import / export with `require` fixed all my issues and removed a lot of code / dependencies / build steps.
