### ISSUE TITLE
[feature request] type should support replacing the current input 

### ISSUE THREAD

**Issue by CodingDive** [testing-library/user-event#232]
An option like `replaceExisting: boolean` for the `type` event would be neat. It should mimic selecting all the content of the input field (sort of like `ctrl+a`) and only then start inserting the input into the text field.

**Comment by kentcdodds** [comment]
This is now supported. You can either first call `clear()` or (probably better), do this:

```javascript
// select all:
input.setSelectionRange(0, input.value.length)
await userEvent.type(input, 'whatever new thing you want')
```

**Comment by smriti-spotnana** [comment]
Why do we need an await before userEvent.type above, if there is no delay passed?

**Comment by kentcdodds** [comment]
@smriti-spotnana you don't. My comment was made before that API change was made. The correct way to do this now is:

```js
// select all:
input.setSelectionRange(0, input.value.length)
userEvent.type(input, 'whatever new thing you want')
```

**Comment by smriti-spotnana** [comment]
ok, thanks for the reply @kentcdodds 

my tests fail intermittently, if I don't use await when typing and then await waitFor(), waiting for a popup to show up. will you be able to comment on this? Thank You
