### ISSUE TITLE
userEvent.click does not work on Material Table

### ISSUE THREAD

**Issue by kkateli** [testing-library/user-event#237]
When I try to use userEvent.click to simulate click event on Material Table(https://github.com/mbrn/material-table), it gives me an error of "document.createRange is not a function". Please help.

**Comment by kentcdodds** [comment]
Hi @kkateli,

Could you please make a minimal reproduction? Once we have something then we can re-open this issue :) Thanks!

**Comment by ogenodisho** [comment]
This should fix the issue assuming you're not on Jest 26 or over: https://github.com/mui-org/material-ui/issues/15726#issuecomment-493124813
