### ISSUE TITLE
Should probably use label.control

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/user-event#241]
This logic here: https://github.com/testing-library/user-event/blob/1af67066f57377c5ab758a1215711dddabad2d83/src/index.js#L15-L31

Should probably first check `label.control` first and rely on the browser's ability to associate labels to form controls and then only do the fallback logic if necessary.

**Comment by weyert** [comment]
Seems like a good idea to me!

**Comment by kentcdodds** [comment]
I think this has been done
