### ISSUE TITLE
window.getSelection is not a function

### ISSUE THREAD

**Issue by emepyc** [testing-library/user-event#242]
### Versions
- node: v10.16.3
- react: 16.13.1
- create-react-app / react-scripts: 3.4.1
- testing-library/react: 9.5.0
- testing-library/user-event: 7.2.1
- testing-library/dom: 7.2.1

### Observed:
When testing a component that contains `window.getSelection` the test fails with
```
TypeError: window.getSelection is not a function
```
Test only fails when using `user-event` on the test, using `fireEvent` instead, the test passes

### Expected:
The test passes

### How to reproduce:
https://github.com/emepyc/get-selection-test

**Comment by kentcdodds** [comment]
This seems to pass with the latest version now :) https://codesandbox.io/s/github/emepyc/get-selection-test

**Comment by ayepRahman** [comment]
Iam facing the same issue, iam using slatejs and tried running test.  

`TypeError: window.getSelection is not a function
`

**Comment by kpounds81** [comment]
Running into the same issue as @ayepRahman using slateJS in my tests.

**Comment by rttmoa** [comment]
l am so
