### ISSUE TITLE
click, dblclick and selectOptions fails when activeElement is null

### ISSUE THREAD

**Issue by rbusquet** [testing-library/user-event#245]
`document.activeElement` can be null as declared in documentation https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/activeElement

I'm having an issue where document.activeElement becomes null due to some async code and then clicks using this library fails with:

```
Error: Unable to fire a "mouseMove" event - please provide a DOM element.
```
This only happens on jest 25.

The check that verifies the element to click is the one currently on focus only checks if activeElement is `body` but doesn't check if it's null. I'm doing more investigation to understand why activeElement is null at the time I'm calling `userEvents.click(element)`, but I think it makes sense to add the extra null verification. Happy to open a PR for this.

**Comment by rbusquet** [comment]
Closing this issue. I got more details while investigating. Still think this is an issue with user-events, but because it currently is not fully compatible with jest 25, I'll do more investigation.

**Comment by mfrachet** [comment]
Can you share your details please? It looks that I'm facing the same right now 😅

**Comment by rbusquet** [comment]
> Can you share your details please? It looks that I'm facing the same right now 😅

@mfrachet it was related to elements that would be rendered conditionally, and when unmounted asynchronously some elements would maintain focus. It caused `document.activeElement` to be null because JSDOM couldn't track them back to the document.

I can't tell if it's an issue with JSDOM itself, or testing-library/react... I have a PR here but I'm having a hard time reproducing the issue: #253
