### ISSUE TITLE
Can you please work on the bundle size?

### ISSUE THREAD

**Issue by hiredgunhouse** [testing-library/user-event#266]
The whole @testing-library inside node_modules is really too big IMHO (almost 20MB), 
user-event is over 12MB and there is this 'cc-test-reporter' ELF executable even though I'm on windows. I know it's not a lot for a single project, but it accumulates quickly even for a single machine.
I'm sure something can be done to make this awesome library smaller :)

**Comment by kentcdodds** [comment]
Fixed in #273 273
