### ISSUE TITLE
File uploading API

### ISSUE THREAD

**Issue by vadimshvetsov** [testing-library/user-event#267]
I'm not sure that this is in the scope but would be great to have an API for uploading file like this:
```ts
function upload(element: TargetElement, file: File | File[]): void

await userEvent.upload(element, file)
await userEvent.upload(element, files)
```

At now I'm doing this:

```ts
fireEvent.change(input as HTMLInputElement, {
  target: { files: [file] },
})
```
What do you think?

**Comment by kentcdodds** [comment]
Hi @vadimshvetsov!

Seems pretty light-weight, but I think it makes more sense to call a function called `upload` rather than `change`. I'd be open for a PR for this :+1: Thanks!

**Comment by vadimshvetsov** [comment]
@kentcdodds That's would be nice to have. I would like to do it if you didn't start implementing this feature.

**Comment by kentcdodds** [comment]
Sure, go for it 👍
