### ISSUE TITLE
userEvent.type does not respect maxlength when appending to existing text

### ISSUE THREAD

**Issue by 9still** [testing-library/user-event#281]
When https://github.com/testing-library/user-event/commit/1e8d140b0e67aa9da089c832deb997c2a15d5a33 introduced a change to the way `.type()` behaves, it did not update `maxLength` handling to take previous text into account.

As a result, if you have an element like this:

```jsx
<textarea aria-label="input" rows="3" maxlength="10" />
```

doing the following
```js
const inputField = screen.getByLabelText('input');
await userEvent.type(inputField, '123456');
await userEvent.type(inputField, '123456789101112');
screen.debug();
```

ends up producing:

```jsx
<textarea aria-label="input" maxlength="10" rows="3" >
    1234561234567891
</textarea>
```

rather than what you would expect from the browser, namely:
```jsx
<textarea aria-label="input" maxlength="10" rows="3" >
    1234561234
</textarea>
```

**Comment by kentcdodds** [comment]
Thanks for the report. Would you be interested in fixing that?

**Comment by 9still** [comment]
@kentcdodds sure - took a stab at it.  Thanks!
