### ISSUE TITLE
userEvent.clear() does not work for input types w/o setSelectionRange support  

### ISSUE THREAD

**Issue by 9still** [testing-library/user-event#282]
`userEvent.clear()` uses `setSelectionRange` to clear the input, but `setSelectionRange` is only supported by a subset of input elements

Per https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange

> Note that accordingly to the WHATWG forms spec selectionStart, selectionEnd properties and setSelectionRange method apply only to inputs of types text, search, URL, tel and password. Chrome, starting from version 33, throws an exception while accessing those properties and method on the rest of input types. For example, on input of type number: "Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection".

This implies that `userEvent.clear()` is not actually supported for `email` and `number` input types, amongst others.

To make matters worse, `jsdom` (tested on 16.2.2) throws a cryptic exception (`InvalidStateError: The object is in an invalid state.`) when you try to use `.clear()` on an unsupported input element, and `jest` does not print out a call stack, making the problem a bit more painful to find.

**Comment by kentcdodds** [comment]
This was recently fixed via a workaround: https://github.com/testing-library/user-event/pull/262

Please update to the latest version. Thanks!

**Comment by 9still** [comment]
Awesome, the new version works great, thanks!
