### ISSUE TITLE
userEvent.clear() missing from published typings

### ISSUE THREAD

**Issue by ianwremmel** [testing-library/user-event#287]
It looks like `userEvent.clear()` got added to typings just a few days ago, but the last release was three weeks ago. Could we get a new release with the updated typings?

Thanks!

**Comment by vadimshvetsov** [comment]
Hi @ianwremmel. I have no issues with using types from in-library typings and [`clear`](https://github.com/testing-library/user-event/blob/master/typings/index.d.ts#L22).

![image](https://user-images.githubusercontent.com/16336572/82394882-d634c600-9a52-11ea-81cd-c13b17df90af.png)

I'm not sure where is the most maintainable source of types in this library, but removing `@types/user-event` package might solve the issue.

**Comment by ianwremmel** [comment]
Strange. The repo in question has the latest version, but the types don't match up with what's apparently published.

![Screen Shot 2020-05-20 at 9 40 24 AM](https://user-images.githubusercontent.com/1182361/82473133-fcbc2680-9a7d-11ea-90e6-140888b375a5.png)

**Comment by ianwremmel** [comment]
oh, interesting. My computer isn't seeing the same `latest` version as npm.com.

```
❯ npm info @testing-library/user-event

@testing-library/user-event@10.1.0 
```

**Comment by ianwremmel** [comment]
`npm cache clean --force` seems to have convinced it to find the latest versions. Please accept my apologies for the confusion.
