### ISSUE TITLE
userEvent.type does not replace selected input value

### ISSUE THREAD

**Issue by wKovacs64** [testing-library/user-event#301]
- `@testing-library/user-event` version: 10.4.0
- Testing Framework and version: jest 24.9.0
- DOM Environment: jsdom 14.1.0, 16.2.2

Relevant code or config

```javascript
test('click, auto-focus, type-to-replace', async () => {
  render(<InputThatSelectsOwnValueOnFocus initialValue="whatever" />);
  const input = screen.getByLabelText(/input/i);

  input.focus();
  await user.type(input, 'works'); // should replace selected text

  expect(input).toHaveValue('works'); // but it doesn't, it appends
});
```

```
Expected the element to have value:
  works
Received:
  whateverworks
```

What you did:

I'm trying to test behavior of an input that automatically selects its contents on focus (so the user can immediately start typing to replace the value, rather than having to clear it manually).

What happened:

Typing after focusing the input is appending to the value rather than replacing it (while actual behavior is working as intended).

Reproduction repository:

https://codesandbox.io/s/user-event-type-to-replace-issue-9wu97?file=/src/__tests__/App.test.js

> Note: it's unclear if CSB is properly using `jest-environment-jsdom-sixteen`, but the error is the same locally for jsdom v14 and v16.

Problem description:

Calling `input.focus()` on an "auto-select-value-on-focus" input followed by `await userEvent.type(input, 'whatever')` just appends `whatever` to the existing input value rather than replacing it.

Suggested solution:

Not sure. Is this just a slightly different manifestation of #236?

**Comment by TransmissionsDev** [comment]
Pretty sure this is intentional, you can clear the field manually.

**Comment by wKovacs64** [comment]
> Pretty sure this is intentional, you can clear the field manually.

As the goal of `user-event` is to "fire events the same way the user does", I wouldn't expect to have to manually clear the field when the existing content has already been selected automatically. The user doesn't clear the field manually, the user simply starts typing.

**Comment by kentcdodds** [comment]
Yes, this should be supported. Would you be interested in opening a PR?

**Comment by wKovacs64** [comment]
Might be a little out of my zone, but I could give it a shot.

**Comment by wKovacs64** [comment]
Well... I had something going for this, but #299 totally wrecked it, haha... 😅
