### ISSUE TITLE
userEvent.type generating "not a function" error

### ISSUE THREAD

**Issue by cwbuecheler** [testing-library/user-event#304]
- `@testing-library/user-event` version: ^11.0.0
- Testing Framework and version: Jest ^26.0.1
  
- DOM Environment: Rendering with `render` from  @testing-library/react ^10.0.4
  

Relevant code or config

```javascript
import React from 'react';
import 'mobx-react-lite/batchingForReactDom';
import '@testing-library/jest-dom';
import {
  fireEvent,
  render,
  screen,
  waitFor,
} from '@testing-library/react';
import userEvent from '@testing-library/user-event';

// A bunch of other code and tests

test('Adding text to the filter box works', async () => {
  const state = AppState.create({ curriculum, gradingSession });
  render(
    <ToastsProvider>
      <GradingSessionBuilder
        addNewGradingSession={() => null}
        curriculum={state.curriculum}
        gradingSession={GradingSession.create({})}
      />
    </ToastsProvider>,
  );

  // PRT and Run buttons in doc
  const prtButton = screen.queryByRole('button', { name: /PRT \(Week 2\)/i });
  expect(prtButton).toBeInTheDocument();
  const runButton = screen.getByRole('button', { name: /4-mile run \(Week 2\)/i });
  expect(runButton).toBeInTheDocument();

  // Filter so there are only run buttons
  await userEvent.type(screen.getByRole('textbox'), '4-mile');
  expect(prtButton).toBeNull();
  expect(runButton).toBeInTheDocument();
});
```

What you did: Executed the above code via the command line (OSX, Node v. 12.16.3)

What happened: I received the following error:

```
✕ Adding text to the filter box works (811 ms)

  ● Adding text to the filter box works

    TypeError: (0 , _dom.getConfig) is not a function

      134 |
      135 |   // Filter so there are only run buttons
    > 136 |   await userEvent.type(screen.getByRole('textbox'), '4-mile');
          |                   ^
      137 |   expect(prtButton).toBeNull();
      138 |   expect(runButton).toBeInTheDocument();
      139 | });

      at Object.type (node_modules/@testing-library/user-event/dist/index.js:356:28)
      at _callee2$ (app/javascript/new_assessments/__tests__/GradingSessionBuilder.test.jsx:136:19)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
      at Object.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
```

I have checked and `screen.getByRole('textbox'), '4-mile');` does definitely find the correct textbox. Also, `userEvent` exists and has the `async type` method on it. Several other tests in the same file work - this error only shows up for the one instance where I'm using `userEvent.type`. 

Even if I comment out all the expects, that one line still throws the same error.

The component is a very large parent with a bunch of children, and I'm under NDA so I can't really make the whole thing available, but I haven't been able to fix anything by tweaking the <input> tag itself on the React side of things.

Reproduction repository: n/a 

Problem description: I'm willing to concede I may be using `userEvent.type` incorrectly, but ... it doesn't seem like it?

Suggested solution: Your guess is as good as mine.

**Comment by TransmissionsDev** [comment]
Having this as well!

**Comment by kentcdodds** [comment]
As mentioned in [the release notes](https://github.com/testing-library/user-event/releases/tag/v11.0.0) the latest version of `user-event` requires `@testing-library/dom` v7.9.0.

This was a breaking change and was released as a major version.

Upgrade your version of `@testing-library/dom` and you should be fine.

One note is that `@testing-library/react` (which is probably where you're getting `@testing-library/dom`) currently lists `^7.8.0` as it's version for `@testing-library/dom`. This should resolve to `7.9.0`, but since that doesn't always seem to work thanks to people's lock files and the general mess of npm clients in the world, I'll go ahead and release a patch version of `@testing-library/react` to update that.

**Comment by cwbuecheler** [comment]
Awesome, thanks @kentcdodds - apologies for not checking the versions. It's hard sometimes to keep up with all the changes in this ecosystem. :)

**Comment by ctoppel** [comment]
This might be project related, but any reason someone could think of that the latest version of @testing-library/dom is not being installed with @testing-library/react?

**Comment by kentcdodds** [comment]
That can happen when your lockfile keeps the older version

**Comment by ctoppel** [comment]
Ya, that was it. Thanks. Deleted the lockfile, removed node modules, and installed modules fresh (which created and new lockfile) and all was good.

**Comment by herecydev** [comment]
@kentcdodds are the versions correct? I've just been spinning my wheels with the same error.

I think the minimum dependency is not `^7.9.0` **but actually** `^7.16.0`. The change to createEvent occurred here: https://github.com/testing-library/dom-testing-library/commit/df57d7b86c7523f49b5b2d0909baa2b2ca9000d0

Which was released in 7.16.0. So I'm pretty sure this needs bumping: https://github.com/testing-library/user-event/blob/master/package.json#L51

**Comment by kentcdodds** [comment]
Ah yeah, that was a mistake in the latest release. That should be updated. Want to fix that?

**Comment by herecydev** [comment]
Yep I'll send a PR in a bit

**Comment by prescottbreeden** [comment]
I know this is closed, 99% sure I'm simply not seeing something here...

error:
`TypeError: _userEvent.default.keyboard is not a function`

package.json
```
  "dependencies": {
    "@testing-library/dom": "^7.30.4",
    "@testing-library/jest-dom": "^5.12.0",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^12.1.10",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
  },
```
import
`import userEvent from '@testing-library/user-event';`

code
`    userEvent.keyboard('{Enter}');`

**Comment by thompson4822** [comment]
I'm using @testing-library/svelte and seeing this issue as well. In package-lock.json, it shows a dependency on @testing-library/dom of ^7.0.3

**Comment by sesamemaki** [comment]
still having same issues :S

**Comment by paulodiovani** [comment]
I was having the same issues, but due to a race condition between `react-dom` checks and `jsdom` init.

- React Dom will check for the environment on import time, not execution time: https://github.com/facebook/react/blob/cae635054e17a6f107a39d328649137b83f25972/packages/shared/ExecutionEnvironment.js#L10-L14
- So, the `jsdom` initialization must be done before any import from `react` or `react-dom`
- If you use `babel/register`, must also initialize `jsdom` before it
- The cause of issue may be similar when using `jest-dom`, my current project uses `mocha`
