### ISSUE TITLE
User Event breaks typing with controlled inputs on v11.0.1

### ISSUE THREAD

**Issue by TransmissionsDev** [testing-library/user-event#307]
- `@testing-library/user-event` version: v11.0.1
- Testing Framework and version: React Testing Lib Latest

- DOM Environment: jsdom

Relevant code or config

```
import React from "react";
import { ThemeProvider, Input } from "@chakra-ui/core";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";

test("THE BUGGED TEST", async () => {
  let formValue = "";
  const setFormValue = jest.fn((newFormValue) => {
    formValue = newFormValue;
  });

  render(
    <input
      data-testid="thisinput"
      type="text"
      value={formValue}
      onChange={(event) => setFormValue(event.target.value)}
    />
  );

  await userEvent.type(screen.getByTestId("thisinput"), "Ben Mayer");

  expect(setFormValue).toHaveBeenCalledWith("Ben Mayer");

  expect(screen.getByTestId("thisinput")).toHaveDisplayValue("Ben Mayer");
});
```

What you did:

After updating to v11.0.1, my tests that tested my controlled inputs are now failing. 

Reproduction repository:

To reproduce run `npm run unit-test` in the `demo-testing-lib-bug` branch of this repo: https://github.com/TransmissionsDev/meridian/tree/demo-testing-lib-bug

Look for the test titled `THE BUGGED TEST` which will fail with this error:

```
● THE BUGGED TEST

    expect(element).toHaveValue(Ben Mayer)

    Expected the element to have value:
      Ben Mayer
    Received:

      29 |   await userEvent.type(screen.getByTestId("thisinput"), "Ben Mayer");
      30 | 
    > 31 |   expect(screen.getByTestId("thisinput")).toHaveValue("Ben Mayer");
         |                                           ^
      32 | 
      33 |   expect(setFormValue).toHaveBeenCalledWith("Ben Mayer");
      34 | });

      at Object.<anonymous> (src/components/shared/FormInput.test.js:31:43)
```

Problem description:

Typing seems to clear the entire input field on each character typed, which breaks my test. I observed this by adding a console.log in the onChange handler, and it logs each character of the input one by one, instead of appending each character to the previous set.

```
  console.log src/components/shared/FormInput.test.js:22
      B
    console.log src/components/shared/FormInput.test.js:22
      e
    console.log src/components/shared/FormInput.test.js:22
      n
    console.log src/components/shared/FormInput.test.js:22
       
    console.log src/components/shared/FormInput.test.js:22
      M
    console.log src/components/shared/FormInput.test.js:22
      a
    console.log src/components/shared/FormInput.test.js:22
      y
    console.log src/components/shared/FormInput.test.js:22
      e
    console.log src/components/shared/FormInput.test.js:22
      r
```

**Comment by kentcdodds** [comment]
Could you try this with the latest version? We made a bunch of improvements and this is probably fixed.

**Comment by kelvinlzhang** [comment]
Not sure if this is related, but I ran into something similar yesterday as well.
```
"@testing-library/jest-dom": "^5.1.1",
"@testing-library/react": "^10.0.6",
"@testing-library/user-event": "^11.0.0",

// render
const emailInput = screen.getByRole("textbox", { name: "Email" });

await user.type(emailInput, "123@123.123");
expect(emailInput).toHaveValue("123@123.123");

received: "3"
expected: "123@123.123"
```
If I wrap the assertion in `setTimeout` it works, so it seems like `type` isn't awaiting properly. `allAtOnce` still works as expected. 

After updating to latest
```
"@testing-library/jest-dom": "^5.9.0",
"@testing-library/react": "^10.2.0",
"@testing-library/user-event": "^11.1.0",
```

I immediately got an `InvalidStateError` once it hit `user.type`, had to reinstall my dom environment package and switch back to `fireEvent.change` to get everything working again.

**Comment by kentcdodds** [comment]
That sounds like an error from the fact that the email address that was typed is invalid. Could you try with a valid email address?

**Comment by kelvinlzhang** [comment]
Sorry, I should've clarified - it's just a normal text input element with a label called email. I get the same behavior with something like foo@bar.com

**Comment by TransmissionsDev** [comment]
@kentcdodds Still failing on 11.1.0 after I purged package-lock.json and node_modules and reinstalled.

**Comment by kentcdodds** [comment]
@kelvinlzhang, that's a different issue. Could you make an isolated running reproduction and open a new issue?

**Comment by kelvinlzhang** [comment]
@kentcdodds I will try to reproduce with a fresh CRA repo tomorrow and open another issue if I'm able to. In the meantime, I retraced my steps in yarn. It did not reproduce the "last character" error that's similar to this issue, but I did run into the `InvalidStateError` on `user.type` again. At least on my machine, there seems to be an issue with this upgrade in particular:

```
"@testing-library/jest-dom": "5.9.0",
"@testing-library/react": "^10.2.0",
"@testing-library/user-event": "^11.0.0", ----> "11.1.0" // here
"jest-environment-jsdom-sixteen": "^1.0.3",
```

 Sorry for cluttering this ticket, and thank you for your help.

**Comment by kentcdodds** [comment]
@TransmissionsDev, could you make a running and isolated reproduction of the issue you're experiencing?

**Comment by TransmissionsDev** [comment]
@kentcdodds If you look at the file I linked you, it is a reproducible runnable reproduction case. I stripped it down to just the input component.

**Comment by TransmissionsDev** [comment]
I think this could be because of testing-library selecting the existing text in the input, and overriding it as per this change: https://github.com/testing-library/user-event/issues/301 ?

**Comment by TransmissionsDev** [comment]
Yeah, this is not an issue with Chakra UI, it's just an issue with testing controlled inputs, because my FormInput is just an abstraction of a controlled input, and before v11.0.1 somehow I was able to get by not re-rendering on each state change, but some bug has been fixed and now I cannot. 

**This isn't a bug with testing-library, just a fix of a bug that broke my ignorance is bliss approach.**

**Comment by kentcdodds** [comment]
Ah, thank you for reporting back on that @TransmissionsDev :)

**Comment by dwjohnston** [comment]
Sorry, is the example given at the top meant to work? 

If you copy the code as it is: 

```
import React from "react";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";

test("THE BUGGED TEST", async () => {
  let formValue = "";
  const setFormValue = jest.fn((newFormValue) => {
    formValue = newFormValue;
  });

  render(
    <input
      data-testid="thisinput"
      type="text"
      value={formValue}
      onChange={(event) => setFormValue(event.target.value)}
    />
  );

  await userEvent.type(screen.getByTestId("thisinput"), "Ben Mayer");

  expect(setFormValue).toHaveBeenCalledWith("Ben Mayer");

  expect(screen.getByTestId("thisinput")).toHaveDisplayValue("Ben Mayer");
});
```


The output I get is: 


```
 FAIL  src/TestSandbox.test.tsx
  ✕ THE BUGGED TEST (55 ms)

  ● THE BUGGED TEST

    expect(jest.fn()).toHaveBeenCalledWith(...expected)

    Expected: "Ben Mayer"
    Received
           1: "B"
           2: "e"
           3: "n"

    Number of calls: 9

      20 |   await userEvent.type(screen.getByTestId("thisinput"), "Ben Mayer");
      21 |
    > 22 |   expect(setFormValue).toHaveBeenCalledWith("Ben Mayer");
         |                        ^
      23 |
      24 |   expect(screen.getByTestId("thisinput")).toHaveDisplayValue("Ben Mayer");
      25 | });

      at Object.<anonymous>.test (src/TestSandbox.test.tsx:22:24)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        4.103 s
```


Is this expected behaviour for userEvent and RTL? - How are we meant to test controlled components?

**Comment by ph-fritsche** [comment]
As [mentioned](https://github.com/testing-library/user-event/issues/307#issuecomment-639621756) [above](https://github.com/testing-library/user-event/issues/307#issuecomment-639633628) this is not expected to work.
