### ISSUE TITLE
Upgrade to v11.1.0 causes type method to fill Input incorrectly

### ISSUE THREAD

**Issue by kelvinlzhang** [testing-library/user-event#309]
- `@testing-library/user-event` version: 11.1.0
- Testing Framework and version: jest on fresh react-scripts@3.4.1 app 
  
- DOM Environment: jest-environment-jsdom-sixteen@1.0.3
  

STR:
1. Use CRA to create new app
2. Make the following upgrades:
```
"@testing-library/jest-dom": "5.9.0",
"@testing-library/react": "^10.2.0",
"@testing-library/user-event": "^11.0.0", ----> "11.1.0" // breaking
"jest-environment-jsdom-sixteen": "^1.0.3",
```
3. Create a component with textbox input, I just pasted in the input event example from https://testing-library.com/docs/example-input-event
4. Use `user.type` instead of `fireEvent` to fill the input
5. Run test with `--env=jest-environment-jsdom-sixteen` and observe that it fails

What happened:
```
test('It should keep a $ in front of the input', async () => {
  const { input } = setup()
  await user.type(input, "23")
  expect(input.value).toBe('$23')
})

Expected: "$23"
Received: "$32"
```

Reproduction repository: https://github.com/kelvinlzhang/user-event-test

Problem description: `type` fails to fill the input correctly. If you downgrade to 11.0.0 the test will pass. On another repo this exact upgrade causes an `InvalidStateError` and I had to reinstall  jest-environment-jsdom-sixteen. This comment, https://github.com/testing-library/user-event/issues/307#issuecomment-639222058, also explains another issue I have been unable to reproduce on a fresh app but occurred with the same dependencies.

**Comment by kentcdodds** [comment]
I think I know what's going on here, I'll probably be able to fix it this morning, but if you'd like to beat me to it you're more than welcome! Even providing me with a failing test case as a PR would be helpful and welcome 😁

**Comment by krzysztof-hellostudio** [comment]
i can confirm that 11.2 still acts differently than old version, seems to be working like you had replace mode enabled in typing and occasionally loosing some letters? very strange

**Comment by krzysztof-hellostudio** [comment]
10.4.1 seems to be last version that was working more like i would expect typing to work, so appending text correctly at the end

**Comment by kentcdodds** [comment]
I figured it out. Pushing a fix in a moment.

**Comment by kentcdodds** [comment]
@all-contributors please add @kelvinlzhang for bugs

**Comment by kentcdodds** [comment]
@all-contributors please add @krzysztof-hellostudio for bugs

**Comment by tpict** [comment]
Really appreciate the quick turnaround on this 😄

**Comment by kelvinlzhang** [comment]
What tpict said, thanks @kentcdodds! 🚀
