### ISSUE TITLE
type causes InvalidStateError with <input type="email">

### ISSUE THREAD

**Issue by kelvinlzhang** [testing-library/user-event#316]
Occurs in master of `@testing-library/user-event` version: 11.2.1

Here's an example failing test, not really up to this library's standards but I wanted to get as close to the source as possible.

STR:

1. Add the following block to src/\_\_tests\_\_/type.js
```
const create = () => {
    const utils = render(<input aria-label="input" type="email"/>)
    const input = utils.getByLabelText('input')
    return {
        input,
        ...utils,
    }
}

it('types text in email input', async () => {
    const { input } = create()
    await userEvent.type(input, 'testing@gmail.com')
    expect(input.value).toBe('testing@gmail.com')
})
```
2. Run test
3. `InvalidStateError`

What happened: I wanted to follow up on this comment and reproduce: https://github.com/testing-library/user-event/issues/307#issuecomment-639226751. Sorry @kentcdodds, the `type=` was abstracted away and it was pretty silly of me to assume it was text. Seems like I ran into 2 completely different issues now, but hopefully I'm just missing something obvious.

Test fails on `InvalidStateError`, adding an `onChange` handler with a `console.log(event.target.value)` shows that `type` only enters in the first char before breaking.

**Comment by kelvinlzhang** [comment]
Yeah, something funky going on with validated text input types.

**Comment by kentcdodds** [comment]
Thanks for this @kelvinlzhang! Would you be interested in digging in and figuring out the issue?

**Comment by kentcdodds** [comment]
@tpict you're welcome to try as well 😁

**Comment by kelvinlzhang** [comment]
@kentcdodds see https://stackoverflow.com/questions/21177489/selectionstart-selectionend-on-input-type-number-no-longer-allowed-in-chrome

Seems like a lot of people aren't too happy about this :(

**Comment by tpict** [comment]
Looks like `user-event` handles this elsewhere by simply [switching out the `type` of the input for the function's lifetime](https://github.com/testing-library/user-event/blob/5c11411b2564603c4a28673dbe089516364f26ec/src/index.js#L217-L229). Would that be a reasonable fix here, or is it off the table on account of `type` being asynchronous?

**Comment by kentcdodds** [comment]
That's what I was thinking. Want to give it a try?

**Comment by Meemaw** [comment]
This is the same problem as https://github.com/testing-library/user-event/pull/262 -- setSelectionRange issue. That function should probably be extracted and reused.

**Comment by nvh95** [comment]
While making the dev tools to automate some tasks for my application, I'm seeing the same problem while trying to use `userEvent.type` on an `input` with `type="email"`.
Bellow is my element
```js
<div>
  <label>Email</label>
  <input
    type="email"
    data-testid="input-email"
  />
</div>
```
And my script to fill the email
```js
await userEvent.type(
  await screen.findByTestId('input-email'),
  'myemail@example.com',
);
```
Only one character is inserted
![image](https://user-images.githubusercontent.com/8603085/83967272-09e46c80-a8ea-11ea-86fa-abcac13a7e22.png)

And in Chrome Console I get this error
![image](https://user-images.githubusercontent.com/8603085/83967172-53808780-a8e9-11ea-98d8-d4d5be5ef2ab.png)

The problem faded away when I switch `type` from `'email'` to `'text'`

**Comment by kentcdodds** [comment]
@all-contributors please add @kelvinlzhang for bugs

**Comment by kentcdodds** [comment]
@all-contributors please add @tpict for bugs, code, and tests

**Comment by kentcdodds** [comment]
@all-contributors please add @nvh95 for bugs
