### ISSUE TITLE
Cannot use type() to type  a "-" (minus) into a numeric input (type="number")

### ISSUE THREAD

**Issue by tadger** [testing-library/user-event#336]
- `@testing-library/user-event` version: `11.3.2`
- Testing Framework and version: `jest 26.0.1`
- DOM Environment: jsdom `16.2.2`

**What you did:**
I am testing an input with `type="number"`

**What happened:**
`-` minus key press is not registering when testing a numeric input

**Reproduction sandbox:**
https://codesandbox.io/s/intelligent-ishizaka-c2zv6?file=/src/App.test.js

**Problem description:**
Invoking `userEvent.type` is yielding unexpected results for an input with `type="number"`. When passing a string that represents a negative number such as `"-123"`, `userEvent.type` appears to dispatch the proper keyPress event, but something swallows the `-` (minus) key event.

I'm not sure if this is an issue with `user-event` or jsdom (fearing the latter)

As a workaround, I'm passing the options `{ allAtOnce: true }`, but I don't feel it properly simulates user input

**Comment by tadger** [comment]
@kentcdodds Thank you for the super quick action on this one. I feel like a bum for not noticing it before I opened this issue, but I'm also seeing unexpected behavior for `.` (period) key presses in decimals. I've added a test to the codesandbox (above) to illustrate it.

**Comment by kentcdodds** [comment]
No worries, I'm actively working on this and just pushed a fix. Should be released in a moment.

Note: it's a known limitation that you cannot use the `,` as a decimal separator. You can only use `.` as the decimal. Thanks!

**Comment by joelworsham** [comment]
This appears to be happening again. I'm at version `14.4.3`

```
    await user.type(
      screen.getByRole('textbox', {
        name: TID.SETUP_MFA.OPTIONS.FORM_FIELDS.REMEMBER_DEVICE.LABEL,
      }),
      '-1',
    );
```

`screen.debug()` result after this:

```
                      <input
                        class="css-8y04n6"
                        id="sz66ipcmvu"
                        name="mfa.rememberDeviceDays"
                        placeholder="0"
                        role="textbox"
                        type="number"
                        value="1"
                      />
```

**Comment by Michael-M-Judd** [comment]
It seems as though doing `.paste` has the same impact where it strips out the negative.

For those having issue, I was also able to solve it by just adding a negative at the beginning of the number:


```typescript
 await user.type(sourceAmountInput, '-', {
          initialSelectionEnd: 0,
          initialSelectionStart: 0,
        });
```
