### ISSUE TITLE
`type` regression if textarea has no value before typing

### ISSUE THREAD

**Issue by loekup** [testing-library/user-event#346]
- `@testing-library/user-event` version:
- Testing Framework and version: 11.4.2
  
- DOM Environment: 
jest@26.0.1
@testing-library/jest-dom@5.9.0
@testing-library/react@10.2.1
  

Relevant code or config

```javascript
test(" empty textarea", async () => {
  render(<textarea data-testid="textbox" />);

  await userEvent.type(screen.getByTestId("textbox"), "1234");
  expect(screen.getByRole("textbox")).toHaveValue("1234");
});

```

What you did:

Updated from 11.2.1 to 11.4.2

What happened:

library code types incorrectly if the textarea has no value when it start typing

Reproduction repository:
https://codesandbox.io/s/user-event-type-to-add-text-issue-exgpf?file=/src/__tests__/App.test.js

Problem description:

It seems like the "type" event returns to the beginning of the line after it has typed the first letter, after that it returns to normal resulting in the first letter always being at the end of the  word/sentence

**Comment by bmerkle3** [comment]
I'm following this issue as we encountered the same. 

if we expected to get the following input: "Entering a note."
we are currently receiving: "ntering a note.E"

**Comment by kentcdodds** [comment]
Thanks for the report you two. I'll get this fixed soon. Doing a bunch of work on user-event right now.

**Comment by kentcdodds** [comment]
If I download the codesandbox locally, it passes 🤔

![image](https://user-images.githubusercontent.com/1500684/84707696-66fca580-af1c-11ea-9c21-333950488cdc.png)

**Comment by loekup** [comment]
Did some further testing, the problem lies in 'jest-environment-jsdom-sixteen' in my own project i was running 'jest-environment-jsdom-global' and apparently the codesandbox online runner ignores the --env in the package scripts

**Comment by mpgon** [comment]
I don't think it's related, but the newly typed value doesn't show in the rendered markup. Shouldn't it?
```javascript
test(" empty textarea", async () => {
  const { debug } = render(<textarea data-testid="textbox" defaultValue="" />);


  debug(); // "" in textarea
  await userEvent.type(screen.getByTestId("textbox"), "1234");
  expect(screen.getByRole("textbox")).toHaveValue("2341"); // the other bug
  debug(); // still shows "" instead of "2341"
});
```

**Comment by kentcdodds** [comment]
I don't know. I'd have to look into it. You can if you like 😁

**Comment by twdrake-ap** [comment]
Yeah type is busted for me as well. Not modifying the input at all.

**Comment by mpgon** [comment]
The codesandbox repro case above is still failing for me for versions 12.0.4/5/6

**Comment by marcosvega91** [comment]
The problem here is that before typing `selectionStart` and `selectionEnd` are undefined. I think that can be a problem of `jsdom` instead

**Comment by nickmccurdy** [comment]
If anyone still has this issue, I think I've tracked it down in https://github.com/testing-library/user-event/issues/391#issuecomment-656444436, and you can subscribe to #391 for updates

**Comment by dave-cabbage** [comment]
I'm using the latest version of `user-event` but I still kept getting this issue, so I had to resort to setting a selection text before typing. That seemed to work

**Comment by ph-fritsche** [comment]
@dave-cabbage The reproduction example of this issue works as expected with up-to-date dependencies:
https://codesandbox.io/s/user-event-type-to-add-text-issue-forked-dezvq?file=/src/__tests__/App.test.js

Are you by chance using an old version of `jsdom`?

If your problem does not resolve by updating the dependencies on your project, please file a [new issue](https://github.com/testing-library/user-event/issues/new) with a reproduction example like above. :)

**Comment by dave-cabbage** [comment]
Yes @ph-fritsche, I'm using jsdom 15 with `jest-environment-jsdom-fifteen`. I had to downgrade to this from 16 because my CRA didn't play well with jsdom 16. 
Anyways, I'll have to refactor this in the future and I'll check again, but until then, selecting the text works for me.
