### ISSUE TITLE
userEvent.selectOptions does not trigger onChange event

### ISSUE THREAD

**Issue by khalidwilliams** [testing-library/user-event#358]
- `@testing-library/user-event` version: 12.0.0
- Testing Framework and version: jest@24.7.1
  
- DOM Environment: jsdom@14.1.0
  

Relevant code or config

```javascript
// Select.js
import React from "react";

const Select = props => {
  const handleChange = e => {
    console.log(e.target.value);
    props.test(e.target.value);

  };
  return (
    <select data-testid="select" onChange={handleChange}>
      <option data-testid="first" value="first">
        first
      </option>
      <option data-testid="second" value="second">
        second
      </option>
      <option data-testid="third" value="third">
        third
      </option>
    </select>
  );
};
export default Select;

// Select.test.js
  import React from 'react';
  import Select from './Select';
  import userEvent from '@testing-library/userEvent';
  import render from '@testing-library/react';


  test("`userEvent.selectOptions` should trigger an onChange event", () => {
    const mockTest = jest.fn().mockImplementation(val => console.log(val));
    const { getByTestId, debug } = render(<Select test={mockTest} />);
    const select = getByTestId("select");
    const second = getByTestId("second");

    userEvent.selectOptions(select, ["second"]);
    debug();
    console.log(select.value)
    expect(mockTest).toHaveBeenCalledTimes(1);
    expect(mockTest).toHaveBeenCalledWith('second');
    expect(second.selected).toBe(true);
  });
```

What you did:
I first noticed this behavior in a larger project, so I made a small repo to reproduce. 

I made a `<select/>` element in React that fires a function received from props onChange. This behavior works as expected in the browser. When testing the behavior, I can successfully assert that a mocked version of that onChange function is called when I trigger a change event (via importing `fireEvent` from RTL), but cannot assert that the same mock is called when using `userEvent.selectOptions`. 

What happened:
<img width="1435" alt="Screen Shot 2020-06-16 at 9 28 24 AM" src="https://user-images.githubusercontent.com/36432040/84794680-c6f25b00-afb3-11ea-9637-f4aa7790eb36.png">

Reproduction repository: 
https://github.com/khalidwilliams/select-test-demo

Problem description:
`userEvent.selectOptions` doesn't trigger a change event. onChange handlers won't fire in tests that use this method, leading to problems with testing any change-dependent behavior. 

Suggested solution:
I'm not sure what the best solution is, it seems like [this line](https://github.com/testing-library/user-event/blob/master/src/select-options.js#L64) may not be firing as expected? Please let me know if there's something I'm missing here -- I'm happy to keep digging!

**Comment by herecydev** [comment]
Thanks for opening this Khalid, experienced the same today and was going to put a repro together as well.

If I had to guess, the following PR would have caused it: #348

**Comment by herecydev** [comment]
Looks like `fireEvent.click(option, init)` is called when using multiple but not when a single option is supplied. That might be the error

**Comment by khalidwilliams** [comment]
@herecydev, how did you verify that clicks aren't going through when called with a single option? When I edit the test and implementation files to try multiple and non-multiple select elements (pushed up [here](https://github.com/khalidwilliams/select-test-demo/tree/multi-select-test/src), I can log information on click events in either case, but cannot log anything on change. Adding some screenshots of the results below:

<img width="1267" alt="Screen Shot of single-select test result" src="https://user-images.githubusercontent.com/36432040/84834075-d2fb0e80-afed-11ea-9b5d-88a8c7f6ae43.png">
<img width="1275" alt="Screen Shot of multi-select test result" src="https://user-images.githubusercontent.com/36432040/84834086-d68e9580-afed-11ea-8c75-6b7360cebe68.png">

**Comment by marcosvega91** [comment]
I think that the problem here is that React will trigger change on the bubbling phase but as I see in the code 
`fireEvent(select, createEvent('change', select, init))` the event is created from scratch with `bubbles` to `false`

**Comment by jamsinclair** [comment]
@marcosvega91 great debugging!

If you need a workaround you could update affected tests to override the event properties.
```js
userEvent.selectOptions(select, ["second"], { bubbles: true });
```

Curious as to why we're not using aliased event functions e.g. `fireEvent.change`, which defaults `bubbles` to true. Must be tied/regressed from the attempted move over to `dom-testing-library`.

**Comment by marcosvega91** [comment]
I think that @kentcdodds can help us to understand why is not called `fireEvent.change`

**Comment by kentcdodds** [comment]
It's because the browser doesn't call the change event. It calls a generic event with the type of change (like we do).

**Comment by herecydev** [comment]
@kentcdodds is that true? Using the user-event playground shows it calls change:

![image](https://user-images.githubusercontent.com/11328618/85143269-742dd300-b241-11ea-9fa7-3e523eb88be2.png)

**Comment by marcosvega91** [comment]
ok I understand, but in any case we should call the event with `bubbles=true`

**Comment by kentcdodds** [comment]
Yes, you're correct.

It just occurred to me that the event with type `change` can actually use `fireEvent.change` because [it's constructor is `Event`](https://github.com/testing-library/dom-testing-library/blob/55344ea3935a616b7e30f2a3aebb32c44134d75a/src/event-map.js#L59-L66), but we can't use `fireEvent.input` because it's constructor is `InputEvent` and that's not what the browser uses for this interaction.

So all that said, I think that we should change this code so it uses `fireEvent.change` for the change event (that'll make it bubble properly), and then we should add these properties to the init for the `input` event: `{bubbles: true, cancelable: false, composed: true}`.

A pull request to do this would be welcome :)

**Comment by marcosvega91** [comment]
Yes of course I'll open a PR for that. I'll love all these projects

**Comment by fabb** [comment]
I just wanted to open an issue and saw there's already a PR for it, nice!

Here's my repro:
https://codesandbox.io/s/usereventselectoptions-bug-gn8wb?file=/src/__tests__/App.js

**Comment by arjun-js** [comment]
It is happening now for select dropdowns.

I am using userEvent.selectOptions to change the value. I am able to change the value but the change event is not getting triggered. 

I am using: 

@testing-library/user-event : 13.5.0

**Comment by Bhuvanesh-git331** [comment]
const dbEle=document.getElementById('schemaname')
        const optionEle=document.createElement('option')
        optionEle.setAttribute('value', 'el_cardnumber_3')
        dbEle.domNode = optionEle
        dbEle.appendChild(optionEle);
        console.log(screen.debug(document.querySelectorAll('option')[1]))
      userEvent.selectOptions(dbEle, document.querySelectorAll('option')[1])


//Hi I tried the above method its working for me. The onChange event is getting triggered

**Comment by tcrz** [comment]
Hi @arjun-js I am facing the same issue currently. Did you find a solution yet?

**Comment by sKopheK** [comment]
```
"@testing-library/react": "^13.4.0",
"@testing-library/user-event": "^14.4.3",
```
the example in OP still does not work

**Comment by sKopheK** [comment]
```
"@testing-library/react": "^13.4.0",
"@testing-library/user-event": "^14.4.3",
```

the example in OP still does not work, but in my case it's due to missing `await` before `userEvent.selectOptions` call

**Comment by tristen831** [comment]
@kentcdodds https://opencodes.space/questions/what-is-preventing-me-from-updating-one-dropdown-list-based-on-the-selection-made-in-another-dropdown-list
