### ISSUE TITLE
Testing Upload: Not sure what input is as per readme file

### ISSUE THREAD

**Issue by VisheshSingh** [testing-library/user-event#359]
This is not an issue but more in the lines of a question:

- `@testing-library/user-event` version: 10.3.1
- Testing Framework and version: Using React (16.13.1)
I ran `npm ls jest` and got this
`-- react-scripts@3.4.1
  -- jest@24.9.0`
  
- DOM Environment:
  

Relevant code or config

```javascript
describe('Test Suite with file upload button', () => {
  test('Should be able to upload a file', () => {
    const { debug, getByText, getByPlaceholderText } = renderWithRedux(
      <MyComponent  />
    );

    const file = new File(['hello'], 'hello.png', { type: 'image/png' });
    const fileUploadBtn = getByText(/browse/i);
    userEvent.upload(fileUploadBtn, file);
    expect(input.files).toHaveLength(1);
  });
});
```

What you did:
I am new to testing, I was following the documentation for testing upload feature. From the documentation it is not clear to me as to what is `input` here?

What happened:
Seeing a ReferenceError:

```javascript
ReferenceError: input is not defined

      159 |     userEvent.click(fileUploadBtn);
      160 |     userEvent.upload(fileUploadBtn, file);
    > 161 |     expect(input.files).toHaveLength(1);
          |            ^
      162 |
      163 |     const comments = getByPlaceholderText(/comments/i);
      164 |     userEvent.type(comments, 'hello');
```
Reproduction repository:

Problem description: I would like to know what input is from the readme.md 

Suggested solution:

**Comment by nickmccurdy** [comment]
This section of the readme was missing the `input` variable, but it's been fixed in #362. This should hopefully make sense now, but if not feel free to ask more questions.
