### ISSUE TITLE
Error when selecting a option in a simple select

### ISSUE THREAD

**Issue by Spy-Seth** [testing-library/user-event#366]
- `@testing-library/user-event` version: v12.0.2
- Testing Framework and version: Jest v26.0.1
- DOM Environment: jsdom v11.5.1:
- Node: v14.3.0

Relevant code or config:

```javascript
import React from "react";
import { render } from "@testing-library/react";
import userEvent from "@testing-library/user-event";

test("select a color", () => {
  const { getByLabelText } = render(
    <div>
      <label htmlFor="favorite-color">Favorite color</label>
      <select id="favorite-color">
        <option value="red">Red</option>
        <option value="blue">Blue</option>
      </select>
    </div>
  );

  userEvent.selectOptions(getByLabelText("Favorite color"), "blue");
});
```

What happened:

```
  TypeError: (0 , _dom.createEvent) is not a function

       97 |     );
       98 | 
    >  99 |     userEvent.selectOptions(getByLabelText("Favorite color"), "blue");
          |               ^
      100 |   });
      101 | 

      at selectOption (node_modules/@testing-library/user-event/dist/select-options.js:74:54)
      at selectOptionsBase (node_modules/@testing-library/user-event/dist/select-options.js:67:5)
      at Object.<anonymous> (src/components/Foo.spec.tsx:99:15)
```

I'm not sure what happen. It seems the `createEvent` function is not available here:

https://github.com/testing-library/user-event/blob/0ce9dab7c80d66b9048d7a9aac04998ee40bfb05/src/select-options.js#L63

**Comment by marcosvega91** [comment]
Hi @Spy-Seth  I think that this issue is a duplicate of #335 
`@testing-library/user-event` has a peer dependency of `@testing-library/dom` so you need to install it manually

**Comment by nickmccurdy** [comment]
You specifically need at least version `7.16.0`, which we now require for features like `createEvent` that are used internally in `user-event`.

**Comment by Spy-Seth** [comment]
I see, I was using `@testing-library/dom@7.11.0`, after upgrading to `@testing-library/dom@7.16.2` everything works fine :ok_hand: 

Thanks for your help :+1:

**Comment by nickmccurdy** [comment]
FWIW you should occasionally check your peer dependency warnings with `npm install` (for yarn you have to delete node_modules/pnp before reinstalling)

**Comment by Spy-Seth** [comment]
I a big mono repo project they are to many warnings that could not be fixed: to much noise that hide true issue
