### ISSUE TITLE
userEvent.type doesn't work well when a value is formatted after the onChange is fired

### ISSUE THREAD

**Issue by WretchedDade** [testing-library/user-event#369]
- `@testing-library/user-event` version: 12.0.2
- Testing Framework and version: jest (24.9.0 locally and whatever version CodeSandbox uses)
- DOM Environment: `@testing-library/react`'s render function, so jsdom?

### React component logic
```tsx
export default function App() {
	const [rawPhone, setRawPhone] = useState('');
	const [formattedPhone, setFormattedPhone] = useState('');

	return (
		<div className="App">
			<form>
				<label htmlFor="raw-phone">Raw Phone: </label>
				<input id="raw-phone" type="text" value={rawPhone} onChange={event => setRawPhone(event.target.value)} />

				<label htmlFor="formatted-phone">Formatted Phone: </label>
				<input id="formatted-phone" type="text" value={formattedPhone} onChange={event => setFormattedPhone(formatPhone(event.target.value)) } />
			</form>
		</div>
	);
}
```

### Format function
```typescript
export function formatPhone(unformattedPhone?: string): string {
	if (unformattedPhone == null)  return '';

	// Remove all formatting from input
	let matchedValue = unformattedPhone.replace(/[^0-9]*/g, '').match(/\d*/g);

	const cleanedValue = matchedValue ? matchedValue.join('') : '';

	// group between areaCode, firstGroup, and secondGroup
	matchedValue = cleanedValue.match(/(\d{0,3})(\d{0,3})(\d{0,4})/);

	const [areaCode, firstGroup, secondGroup] = matchedValue ? matchedValue.slice(1) : ['', '', '']; 

	// initialize phoneNumber
	let phoneNumber = '';

	// begin with '(' after any digit input
	if (areaCode !== '') phoneNumber = `(${areaCode}`;

	// end area code with ')' if there are more than 3 digits (at least 1 digit in firstGroup)
	if (firstGroup !== '') phoneNumber = `${phoneNumber}) ${firstGroup}`;

	// add '-' if there are more than 6 digits (at least 1 digit in secondGroup)
	if (secondGroup !== '') phoneNumber = `${phoneNumber}-${secondGroup}`;

	return phoneNumber;
}
```

### Tests
```tsx
test('Raw phone should set the value to match excatly what is typed', async () => {
	render(<App />);
	userEvent.type(screen.getByLabelText(/Raw Phone/i), '1234567890');
	expect(screen.getByLabelText(/Raw Phone/i)).toHaveValue('1234567890');
});

test('Formatted phone should format the value as it is typed', async () => {
	render(<App />);
	userEvent.type(screen.getByLabelText(/Formatted Phone/i), '1234567890');
	expect(screen.getByLabelText(/Formatted Phone/i)).toHaveValue('(123) 456-7890');
});
```

What you did:

I have a field where we collect a phone number and format it as the user types. To do so, we format the value onChange before we call the `setState` function from the `useState` hook`.  

What happened:

When attempting to test this by calling `userEvent.type(..., '1234567890')` the value was being set to (098) 765-4321 instead of (123) 456-7890.

Reproduction repository:

https://codesandbox.io/s/usereventtype-reverses-value-mgi2n?file=/src/App.spec.tsx

Problem description:

This was extremely confusing at first and led me to do a lot of digging in the source code of `userEvent.type(...)`. Once I did so for a while I came across the idea that it may be an issue with the selected location returning to the beginning of the input. I think it may have something to do with the newValue being different than it expected.

Suggested solution:

I don't know that I have a suggested solution, as I don't have a complete grasp over the source code and the cause of the specific problem. However, I'm more than happy to help discuss options and take a crack at implementing a fix with some guidance.

**Comment by nickmccurdy** [comment]
Have you tried wrapping your `expect` calls in `waitFor`? `setState` updates are asyncronous in React so I believe you'd need to wait for them to update in your tests.

**Comment by WretchedDade** [comment]
That was my first thought but seeing as the test fails because the value is reversed rather than not having a value, i was able to rule that out.

**Comment by nickmccurdy** [comment]
Ah sorry, I think I misunderstood the issue. Have you tried `paste`? It writes the input all at once, so I wonder if that would avoid the bug.

**Comment by WretchedDade** [comment]
Paste did avoid the bug, but that would mean I'm not testing the same thing right? Or is it close enough to typing that its still a valid test for how the component responds to a user typing?

**Comment by kentcdodds** [comment]
I'm 90% certain that your test as written above should pass and this is a bug, probably related to: https://github.com/testing-library/user-event/issues/346

Reproducing this would probably be a matter of adding another test here: https://github.com/testing-library/user-event/blob/f4eae9cf3c4bb5765dcdb7ce7f7652ae16e2f9a7/src/__tests__/type.js#L708

I'm not sure about the solution, but that's where I'd start first to know for certain that this is a user-event bug.

I don't have the bandwidth to work on this myself unfortunately.

**Comment by nickmccurdy** [comment]
To be clear, I wasn't suggesting to actually keep `paste` in your test. You're right that it would be different behavior, I was just interested in it for troubleshooting.

**Comment by WretchedDade** [comment]
I'll pull down the repo and see if I can figure out what's going on.

**Comment by WretchedDade** [comment]
After digging into this some, here is what I found:

The assumed new value and next location to insert text is calculated by the `calculateNewValue` function in order to call `_dom.fireEvent.input(...)`. However, when this event is fired the value is formatted and changes the value of `currentElement().value`. Because of this, the `newSelectionStart` value is inaccurate to where I would expect the next insert location to be.

https://github.com/testing-library/user-event/blob/f4eae9cf3c4bb5765dcdb7ce7f7652ae16e2f9a7/src/utils.js#L95-L135
https://github.com/testing-library/user-event/blob/f4eae9cf3c4bb5765dcdb7ce7f7652ae16e2f9a7/src/type.js#L158-L161

I'm not proposing it as a change, but by forcing `newSelectionStart` to be `currentElement().value.length` my issue is resolved. Perhaps the selection calculation needs to be moved to after the input event is fired?

https://github.com/testing-library/user-event/blob/f4eae9cf3c4bb5765dcdb7ce7f7652ae16e2f9a7/src/type.js#L163
```js
setSelectionRange({ newValue, newSelectionStart: currentElement().value.length});
```

**Comment by nickmccurdy** [comment]
Hm, that's interesting. If the snapshot changes look okay to you feel free to start a PR and we can hopefully figure out the other failures.

**Comment by WretchedDade** [comment]
Well, the tests are failing because this prevents any scenario of inserting text in the middle of the input. I'll probably take a crack at implementing something that works for both scenarios sometime in the next couple days and open a PR if I get something working.

**Comment by WretchedDade** [comment]
The problem I ran into is I'm not sure how to convert my react test into one for this library (since its framework agnostic), so if anyone as ideas on that it would be appreciated.

**Comment by nickmccurdy** [comment]
You're probably looking for the `setup` function from utils which will let you get a DOM element or list of events that you can snapshot, for example: https://github.com/testing-library/user-event/blob/f4eae9cf3c4bb5765dcdb7ce7f7652ae16e2f9a7/src/__tests__/paste.js#L1-L19

**Comment by WretchedDade** [comment]
Thanks, that put me in the right direction and I've got a test written locally now. I tried to replicate what I had done in my react test with formatting the value on change but it doesn't seem to be firing a change event. When I format the value on the input event, it works fine. So I'm stumped now.

The test I wrote in `__tests__/type.js`:
```js
test('typing a value that is formatted on change', () => {
  function formatPhone(unformattedPhone) {
    if (unformattedPhone == null) return ''

    // Remove all formatting from input
    let matchedValue = unformattedPhone.replace(/[^0-9]*/g, '').match(/\d*/g)

    const cleanedValue = matchedValue ? matchedValue.join('') : ''

    // group between areaCode, firstGroup, and secondGroup
    matchedValue = cleanedValue.match(/(\d{0,3})(\d{0,3})(\d{0,4})/)
    const [areaCode, firstGroup, secondGroup] = matchedValue
      ? matchedValue.slice(1)
      : ['', '', '']

    // initialize phoneNumber
    let phoneNumber = ''

    // begin with '(' after any digit input
    if (areaCode !== '') phoneNumber = `(${areaCode}`

    // end area code with ')' if there are more than 3 digits (at least 1 digit in firstGroup)
    if (firstGroup !== '') phoneNumber = `${phoneNumber}) ${firstGroup}`

    // add '-' if there are more than 6 digits (at least 1 digit in secondGroup)
    if (secondGroup !== '') phoneNumber = `${phoneNumber}-${secondGroup}`

    return phoneNumber
  }

  const {element} = setup('<input />', {
    eventHandlers: {
      input: e => {
        console.log('Input event fired!')
        e.target.value = formatPhone(e.target.value)
      },
      change: e => {
        console.log('Change event fired!')
        e.target.value = formatPhone(e.target.value)
      },
    },
  })

  userEvent.type(element, '1234567890')

  expect(element).toHaveValue('(123) 456-7890')
})
```

**Comment by kentcdodds** [comment]
I'm not sure 😬 you may have to do a little more digging.

**Comment by WretchedDade** [comment]
So I did a little more digging and made a lot of changes. Which ultimately helped me understand the problem and reasons behind why the code was structured how it was. I then learned that the issue was ultimately how the browser responded to a programattic change and how userEvent.type responded to it. 

I learned what the intentions were behind the following code and that the problem was if the value was changed programattically, the selection would never update from it's initial value.
https://github.com/testing-library/user-event/blob/44b901165b599c5c7d28668375696adccb4cfdc5/src/type.js#L64-L70

Therefore, I have opened a PR recommending updating it to:
https://github.com/testing-library/user-event/blob/e6261e09fc8cd0851ffa938b320c1460cdf95a9f/src/type.js#L64-L77

**Comment by terraelise** [comment]
I am experiencing this issue with 13.5.0, had to downgrade to 12.0.4 to solve it.

**Comment by mickcastle** [comment]
can confirm as above that this issue is present in version 13.5.0

**Comment by ph-fritsche** [comment]
@terraelise @mickcastle Please don't add noise to the issue board. File an issue with a reproducible example.

Also try upgrading to the latest version.
The issue above has been resolved. There might be another issue with `13.5.0` that might or might not be already resolved.
