### ISSUE TITLE
References to React are misleading

### ISSUE THREAD

**Issue by nickmccurdy** [testing-library/user-event#393]
We still seem to suggest that this library is only for React in some places, when it's meant to be general purpose for any testing library.

Thanks to @gndelia for discovering most of these issues!

> - it only lists React in the summary
> 
> ![image](https://user-images.githubusercontent.com/352474/86245885-8b918800-bb80-11ea-85ff-c9304f2c1adc.png)
> 
> - All the examples are of React in the Readme - not `dom` related
> 
> [The docs state](https://testing-library.com/docs/ecosystem-user-event)
> 
> > user-event is a companion library for **React** Testing Library that provides...

**Comment by ph-fritsche** [comment]
Updated docs:
> While most examples with `user-event` are for `React`, the library can be used
with any framework as long as there is a DOM.

Updated repo info:
![image](https://user-images.githubusercontent.com/39068198/160106433-a86f28ce-43e2-45d3-9c03-b9c0b4fa2ab5.png)
