### ISSUE TITLE
tab should support composite elements

### ISSUE THREAD

**Issue by nickmccurdy** [testing-library/user-event#394]
Problem description: The [WAI ARIA `composite` abstract role spec](https://www.w3.org/TR/wai-aria/#composite) requires that any element with a subclass role of `composite` is treated as a single navigational element.

Suggested solution: We should treat any elements with these roles as a single "tabbable" element, rather than tabbing through its child elements. Perhaps we could add a function that gets parent elements of any elements inside composite elements, and then prune duplicates from the list before starting to tab over them.

**Comment by visualjerk** [comment]
I guess this could lead to some confusion, as the `composite` role does not prevent a user from tabbing through the children of the element.

It is on the developer to make sure that a `composite` element behaves like the spec suggests (eg. using roving tabindex or aria-activedescendant technique).

So in adding the proposed solution, we would create false positives for components, that do not follow the spec.

**Comment by kentcdodds** [comment]
Agreed. We always want to make certain that we follow what the browser actually does as closely as possible.

Thanks!
