### ISSUE TITLE
Add support for cyrillic and chinese characters in userEvent.type

### ISSUE THREAD

**Issue by jcolakk** [testing-library/user-event#395]
Problem description: `userEvent.type` doesn't support Cyrillic and Chinese characters(possibly others but didn't test it), its needed in order to test different locales, not sure if it can already be used, but didn't manage to find anything in the documentation.

**Comment by marcosvega91** [comment]
Hi @jcolakk thanks for opening the issue :)

I have created [here](https://testing-playground.com/?markup=DwSwdgDgrgLgUCAJgXgEQGMAW4CmBnHVOMAQwFsc0tcCiIAbE9HTAe3sRwCc0BlNqBwAEIGEIDurLgGsJozEOph8OISXoRMJAEY4YRAG7qolVDHz64AegB8QA&query=K4ZwpgTgogbmB2AXAdAYwDZgIYQBQlQjAWQHMxEAhATwCUB7TXAckTAA9EAje95gSn4AoUJFgIUiagAcw%2BQsXhkKNBk1YduvAQBoABM0A6q4ATxgUA) a playground with Chinese characters but I have no problem. have I missed something?

**Comment by jcolakk** [comment]
Hmm, indeed works 🤔  okay, I'll play around with it in our codebase a bit more, could be some underlying issue in our code. Thanks!

**Comment by marcosvega91** [comment]
If you need further assistance is better to create a reproduction case on [codesandbox](https://codesandbox.io/), in this way we can take a look of your code. 

You can also join our [discord server](https://discord.gg/MqGcZ9) for this kind of help. We will happy to help you 🥳

**Comment by jcolakk** [comment]
It was an issue on our side after all, sorry for bothering.

> If you need further assistance is better to create a reproduction case on [codesandbox](https://codesandbox.io/), in this way we can take a look of your code.
> You can also join our [discord server](https://discord.gg/MqGcZ9) for this kind of help. We will happy to help you 🥳
Sure, will do in the future 👍
