### ISSUE TITLE
TypeError: (0 , _dom.getConfig) is not a function

### ISSUE THREAD

**Issue by piyushbajaj** [testing-library/user-event#396]
![Screenshot 2020-07-08 at 5 29 11 PM](https://user-images.githubusercontent.com/12572883/86916026-90d27200-c140-11ea-8cee-113d85897239.png)

I already have latest version of @testing-library/user-event
and @testing-library/dom (Indirectly refrenced)

Still getting this error in my React JS code, please help me.

**Comment by piyushbajaj** [comment]
@kentcdodds 
I just saw this https://github.com/testing-library/user-event/releases
And so i reverted user-events to point to c12.0.2 and it started working fine.

That means with the current new release: v12.0.11. The same above error coming up.
Please do fix this with current version also.

Thanks

**Comment by kentcdodds** [comment]
You need to have the latest version of DOM Testing Library installed. Then that will work.

**Comment by nimobeeren** [comment]
Can confirm. Just ran into this issue, but I forgot to install `@testing-library/dom`.
