### ISSUE TITLE
userEvent.type doesn't seem to support `input` fields of `type="date"` (native datepicker)

### ISSUE THREAD

**Issue by ahayes91** [testing-library/user-event#399]
- `@testing-library/user-event` version: 12.0.11
- Testing Framework and version: jest (out of the box with Codesandbox MUI issue template)
  
- DOM Environment: Out of the box with Codesandbox MUI issue template
  

Relevant code or config

For an MUI native datepicker such as (which ultimately renders in the DOM as an `input` component of `type="date"`):

```javascript
<TextField
    id={`nativeDatepicker`}
    type="date"
    defaultValue={moment().toISOString()}
    onChange={event => handleDateValueUpdate(event.target.value)}
    error={false}
    helperText={""}
    disabled={false}
    inputProps={{
      "data-testid": `inputId-nativeDatepicker`
    }}
    required={true}
  />
```

`userEvent.type` will not call onChange with the specified `event.target.value`:

```javascript
it("should update with userEvent.type", async () => {
    const handleDateValueUpdate = jest.fn();
    render(<NativeDatepicker handleDateValueUpdate={handleDateValueUpdate} />);
    const nativeDatepicker = await screen.findByTestId(
      "inputId-nativeDatepicker"
    );
    userEvent.type(nativeDatepicker, "2020-01-02");
    expect(handleDateValueUpdate).toHaveBeenCalledWith("2020-01-02");
  });
```

Results:
```
expect(jest.fn()).toHaveBeenCalledWith(expected)

Expected mock function to have been called with:
  ["2020-01-02"]
But it was called with:
  [""]

  11 |       "inputId-nativeDatepicker"
  12 |     );
  13 |     userEvent.type(nativeDatepicker, "2020-01-02");
> 14 |     expect(handleDateValueUpdate).toHaveBeenCalledWith("2020-01-02");
  15 |   });
  16 | });
```

What you did:
I put the relevant code on a sandbox here:
https://codesandbox.io/s/heuristic-sun-dqfby?file=/src/NativeDatepicker.test.js

What happened:
I'd expect the testing library to be able to update the date field with the provided value, but it doesn't seem to happen. 

Results:
```
expect(jest.fn()).toHaveBeenCalledWith(expected)

Expected mock function to have been called with:
  ["2020-01-02"]
But it was called with:
  [""]

  11 |       "inputId-nativeDatepicker"
  12 |     );
  13 |     userEvent.type(nativeDatepicker, "2020-01-02");
> 14 |     expect(handleDateValueUpdate).toHaveBeenCalledWith("2020-01-02");
  15 |   });
  16 | });
```

Reproduction repository:

https://codesandbox.io/s/heuristic-sun-dqfby?file=/src/NativeDatepicker.test.js

Problem description:
I want to be able to update an input date field in my integration tests using userEvent, but not sure if the `type` method supports input fields of type date. 

Suggested solution:
Support input fields of type date.

**Comment by ahayes91** [comment]
The workaround for this for now is to use `fireEvent` from `@testing-library/react` - will update the sandbox with that now.

**Comment by lourenci** [comment]
I can confirm that. It's an issue even without React.

**Comment by stucox** [comment]
For anyone who happens upon this with the same issue I had: you may find that `userEvent.type()` may not fire expected events (and hence may not correctly update bound data) if a date input is already populated. This is because, like a text input, it tries to _append_ to the existing value — which a date field doesn't allow. Need to `userEvent.clear()` it first 😄 

I experienced this in Vue 2.x, with a date input bound with `v-model`.

**Comment by IuliiaBondarieva** [comment]
Had this issue too. And the problem was input type `date`. 
Found the answer here:
https://github.com/testing-library/user-event/issues/941#issuecomment-1234374123

> inputted string HAS to match the value of a date input (i.e. "YYYY-MM-DD")

**Comment by phillt** [comment]
I keep getting this for some reason:

![image](https://github.com/testing-library/user-event/assets/2586937/3884fe3c-3d24-44c3-8641-45a9127dfefc)
