### ISSUE TITLE
type event in textarea results in incorrect character order

### ISSUE THREAD

**Issue by willgorham** [testing-library/user-event#402]
- `@testing-library/user-event` version: 12.0.11
- Testing Framework and version: jest 24.9.0
  
- DOM Environment: jsdom 11.12.0
  

Relevant code or config:

Basic create-react-app (not ejected). 

Copied the `type` example directly from the readme:
```javascript
import React from 'react';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';

test('type', () => {
  render(<textarea />)

  userEvent.type(screen.getByRole('textbox'), 'Hello,{enter}World!')
  expect(screen.getByRole('textbox')).toHaveValue('Hello,\nWorld!')
});
```

What happened:

Running the test produces the following error:
<img width="571" alt="Screen Shot 2020-07-15 at 6 43 00 PM" src="https://user-images.githubusercontent.com/1883584/87607305-0acba380-c6cb-11ea-967c-4631e35e6a85.png">

Reproduction repository:

https://github.com/lm1503109/user-event-textarea

Problem description:

The first character of typed input is at the end of the resulting value.

Suggested solution:

**Comment by kentcdodds** [comment]
Hey there @willgorham,

The issue is there are lots of bugs in the version of jsdom you're using. Try using this: https://www.npmjs.com/package/jest-environment-jsdom-sixteen

There's nothing more we can do to fix this.

**Comment by rwalle61** [comment]
For anyone hitting this issue in Create React App and unable to override Jest's default jsdom `testEnvironment` using a `jest.config.js`, I used this to override it with jsdom-sixteen: https://github.com/facebook/create-react-app/issues/7491#issuecomment-520157683
