### ISSUE TITLE
Make type resolve to the text that was typed

### ISSUE THREAD

**Issue by imjordanxd** [testing-library/user-event#412]
Would it possible for `type` to resolve to the text that was typed?

I find myself doing the following often and wrote a utility function, but it would be nice to see this added to the library:
```
const name = faker.name.firstName();
await userEvent.type(getByLabelText('Name'), name);
```

With my utility I can do:
```
const name = await type(getByLabelText('Name'), faker.name.firstName());
```

Additionally, would it be possible to add an option that could clear the text before typing?

**Comment by kentcdodds** [comment]
Hi @imjordanxd,

I can see how that could be useful, but I don't think it makes sense for `type` to return a value you passed it. It would make just as much sense to return the element I think.

Luckily, if you follow [the advice about custom utils](https://testing-library.com/docs/react-testing-library/setup#configuring-jest-with-test-utils) then you could make your own version of this utility easily accessible all around your codebase.

Thanks! Good luck.
