### ISSUE TITLE
Docs improvement for using `selectedRange` with userEvent.type

### ISSUE THREAD

**Issue by ahayes91** [testing-library/user-event#413]
- `@testing-library/user-event` version: Latest
- Testing Framework and version: Jest
  
- DOM Environment: jsdom 16
  

Problem description:
The use case is being able to specify how many characters should be deleted with 
```
userEvent.type(input, `{backspace}`)
``` 
You can put this into a loop but the docs seems to suggest there is a way to use something called `selectedRange`, which I can't find in the codebase or in the documentation. 
https://github.com/testing-library/user-event#typeelement-text-options

Suggested solution:
Improve the documentation/examples 😁

**Comment by kentcdodds** [comment]
Good point @ahayes91! Perhaps an example could be helpful. Something like this: https://github.com/testing-library/user-event/blob/52c333cf1ea6d961bcfea64d974ee05845c1c924/src/__tests__/type-modifiers.js#L195-L197

Would be be interested in adding an example for this to the docs?

**Comment by lucbpz** [comment]
Hello! I took this issue as my first contribution to the project. I wrote the example like the other ones in the readme were written, let me know if it needs any changes! Thanks and I hope it helps!
