### ISSUE TITLE
userEvent.type honors maxLength when it's not supposed to

### ISSUE THREAD

**Issue by wilsonburnawan09** [testing-library/user-event#418]
- `@testing-library/user-event` version:
- Testing Framework and version:
  
- DOM Environment:
  

Relevant code or config

Dependencies
```
@testing-library/dom 7.21.5
@testing-library/react 10.4.4
@testing-library/user-event 12.0.11
react 16.12.0
react-dom 16.12.0
react-scripts 3.4.1
```

Failing test case
```javascript
it("should not honor maxLength on input type='number'", () => {
    const changeHandler = jest.fn();
    const { getByDisplayValue } = render(
      <input maxLength="3" type="number" value="123" onChange={changeHandler} />
    );
    const input = getByDisplayValue("123");
    userEvent.type(input, "456");
    expect(changeHandler).toHaveBeenCalledTimes(3);
  });
```

What you did:
Use userEvent.type on input with type=number and maxLength

What happened:
Fail the test case above

```
expect(jest.fn()).toHaveBeenCalledTimes(3)

Expected mock function to have been called three times, but it was called zero times.

  20 |     );
  21 |     const input = getByDisplayValue("123");
  22 |     userEvent.type(input, "456");
> 23 |     expect(changeHandler).toHaveBeenCalledTimes(3);
  24 |   });
  25 | });
```

Reproduction repository:
https://codesandbox.io/s/stupefied-booth-9ov2i?file=/src/input.test.js:522-888

Problem description:
I am trying to test my custom function to prevent user types more than `maxLength` but I can't test it because `userEvent.type()` honor the `maxLength` on `type='number'` (potentially other type as well) even though that's not the case in practice (check out codesandbox `src/index.js`).

`userEvent.type()` gives me false positive in passing my test case

Suggested solution:
Add condition such as:
```javascript
const honorMaxLengthType = new Set(['text']);
const elemType = element.getAttribute('type');
if (maxLength < 0 || !honorMaxLengthType.has(elemType) ) {
  ...
} else {
  ...
}
```
https://github.com/testing-library/user-event/blob/448046c237482837d18439ed9fc1128065e641f3/src/utils.js#L129

**Comment by marcosvega91** [comment]
Hi @wilsonburnawan09 thanks for opening the issue :).

You're right we should check this, not only inputs but also textarea. Do you want to submit a PR? :)
