### ISSUE TITLE
userEvent.type documentation is not precise

### ISSUE THREAD

**Issue by mnemanja** [testing-library/user-event#419]
- `@testing-library/user-event` version: 12.0.15

Problem description:
The documentation doesn't state that the `type` method returns a promise. Only that if we apply `options.delay` that we should `await.

Or, perhaps, it is awaiting optional and situational?

I have to say, reading through the documentation, after the latest `type` method update, it read as if the `type` method no longer returns promise by default, but only in case if you use the `options.delay`.

![image](https://user-images.githubusercontent.com/1423218/88583236-3dbd5200-d050-11ea-910b-d131459c13ae.png)

Perhaps it makes sense to state what the method returns and how the test will behave in case the method is `await`ed for and how when it's not.

**Comment by kentcdodds** [comment]
`type` always returns a promise, but if you don't pass a `delay` it finishes everything synchronously. So it only needs to be awaited if you pass a `delay`.

Would you like to describe this better in the docs in a PR?

**Comment by mnemanja** [comment]
Nope, I get it now and I think this sums your comment up very nicely.
>To be clear, userEvent.type always returns a promise, but you only need to await the promise it returns if you're using the delay option. Otherwise everything runs synchronously and you can ignore the promise.
