### ISSUE TITLE
Example in Testing Library docs fails

### ISSUE THREAD

**Issue by iainvdw** [testing-library/user-event#429]
I've been having an issue where I can't get `user-event` to work properly using [the example from the RTL docs](https://testing-library.com/docs/ecosystem-user-event). It fails stating that the received value is `null` instead of the actual value that should be typed into the textarea.

**Used libraries and versions:**
- `@testing-library/user-event` version: 12.1.1
- Testing Framework and version: react-scripts@3.4.3, so essentially jest@26.3.0
- DOM Environment:
Whatever comes default with react-scripts. `npm ls jsdom` results in either jsdom@11.12.0 or jsdom@14.1.0. Can't confidently tell which one is used unfortunately. :\

**What you did:**
Implemented the example and ran `npm run test` -> `react-scripts test`

**What happened:**
![Screenshot 2020-08-13 at 09 09 36](https://user-images.githubusercontent.com/1300766/90104544-c0c6f380-dd44-11ea-8672-6cf5d9990b36.png)

**Reproduction repository:**
[Issue repo](https://github.com/iainvdw/user-event-issue), see `src/App.test.tsx`.
Bare CRA setup with TypeScript template, to mimic my current setup. Added only `user-event` and the example test from the docs.

**Problem description:**
Running `npm run test` immediately fails the test that comes from the docs.

**Comment by nickmccurdy** [comment]
Can confirm, even if all dependencies are updated.

**Comment by marcosvega91** [comment]
Hi guys I think is more an issue with the doc. `textarea` doesn't have an attribute `value`. The value of the textarea is his content. If you access his dom node with `document.querySelector` for example you can access the value property.

`toHaveAttribute` will check only the element attributes but not properties of the object

**Comment by nickmccurdy** [comment]
It works if you replace `toHaveAttribute` with `toHaveProperty`. I'd recommend making the same change to your code, and I'll update the docs in testing-library/testing-library-docs#578.
