### ISSUE TITLE
Element event callback not fired from userEvent when callback is not a component prop

### ISSUE THREAD

**Issue by AsukaCHikaru** [testing-library/user-event#430]
- `@testing-library/user-event` version: 12.1.1
- Testing Framework and version: jest
- DOM Environment: jsdom
- node version: 12.18.1

## Issue

I wanted to use `userEvent.type` in a textbox and was expecting `.toBeCalledTimes` being fired number of typed string times, but the received result always being 0 times, when the `onChange` callback is not provided as a prop, but defined in the component only.

```
describe('', () => {
  const ComponentForTest = ({ onChange }: { onChange?: () => void }) => {
      const [text, setText] = React.useState('Hello');
      const handleInputChange = (event: any) => {
        setText(event.target.value);
      };

      return (
        <div>
          <input type="text" onChange={onChange ? onChange : handleInputChange} />
          <p>{text}</p>
        </div>
      );
    };

    it('fireEvent with callback defined inside component', () => {
      // this will pass
      render(<ComponentForTest />);
      const mockChange = jest.fn();
      screen.getByRole('textbox').onchange = mockChange;
      fireEvent.change(screen.getByRole('textbox'), { target: { value: 'Hello world!' } });
      expect(mockChange).toHaveBeenCalledTimes(1);
    });

    it('userEvent with callback defined inside component', () => {
      // this will fail
      render(<ComponentForTest />);
      const mockChange = jest.fn();
      screen.getByRole('textbox').onchange = mockChange;
      userEvent.type(screen.getByRole('textbox'), 'Hello world!');
      expect(mockChange).toHaveBeenCalledTimes(12);
    });

    it('userEvent with callback provided as a prop', () => {
      // this will pass
      const mockChange = jest.fn();
      render(<ComponentForTest onChange={mockChange} />);
      userEvent.type(screen.getByRole('textbox'), 'Hello world!');
      expect(mockChange).toHaveBeenCalledTimes(12);
    });
});
```
![image](https://user-images.githubusercontent.com/12955366/90465209-d9227e00-e149-11ea-83c9-20a8c6dddcf4.png)

I tried to use `mockImplementation`, adding `console.log` inside for debugging and found that the onchange callback did not fire, there were no logs printed, while there were when using `fireEvent`.

## Problem description:

Element event callback (ex. onChange) not fired from `userEvent` when callback is not provided as a component prop. Meanwhile `fireEvent` does not have this issue.
I would like to know if this is intentional?

**Comment by nickmccurdy** [comment]
Is there a specific reason why you need to mutate the DOM rendered by React? This doesn't really accurately test how your code works with React as React's synthetic event system may or may not properly pick up your mutations, so I'd recommend sticking with your last test case here.

**Comment by AsukaCHikaru** [comment]
There were some cases that I have event handler (like `onClick`) made in that component, instead of being passed as a prop, and I wanted to test if that particular event handler is being fired.

Also, while the second test I provided was binding `jest.fn()` to the event handler as a ref, I believe that if it was directly being refered in the expect function like `expect(screen.getByRole('...').onchange).toHaveBeenCalled`, it would fail too.

**Comment by ph-fritsche** [comment]
If you want to test if events are triggered as a side effect, attach a listener on that element:
```js
const onChange = jest.fn()
screen.getByRole('textbox').addEventListener('change', onChange)
// ... do what should trigger the event ...
expect(onChange).toBeCalled()
```
This also works across rerenders as long as the identity of the node doesn't change, but you should only use it when necessary.

If you want to test if the component handles the event, test the effect:
```js
userEvent.type(screen.getByRole('textbox'), 'foo')
expect(document.querySelector('p')).toHaveTextContent('foo')
```

Your test above fails because the input element has no real `change` event until it loses focus.
React generates a `change` event for the real `input` event. That's why the `onChange` prop works and the event handler in the DOM doesn't.
