### ISSUE TITLE
cannot tab back to previuos element when focus is on radiogroup

### ISSUE THREAD

**Issue by jKatt** [testing-library/user-event#441]
Since 11.3.2 it is not possible to tab back to the previous element when focus is on a radiogroup.
The focus is then instead switched to the last accessible element.

I wrote a little test scenario where the problem is shown:
https://codesandbox.io/s/distracted-beaver-zwbh2

**Comment by marcosvega91** [comment]
Hi @jKatt thanks for raising this 😄 

I'll fix the issue in a while. Stay tuned 🚀
