### ISSUE TITLE
contextMenu not callable

### ISSUE THREAD

**Issue by geoffroymounier** [testing-library/user-event#445]
Hi!
Any way to make the `<div ... onContextMenu={}>` fire ? 
I've tried by use of `userEvent.click(elem, {ctrlKey: true})` `userEvent.click(elem, {button: 2})` to emulate the right-click on an element but that does not trigger the context menu. 

Any advice on whether this is a enhancement or simply myself doing wrong

So far I'm using `fireEvent` but I'd love to convert to user-event for all my mocks.

**Comment by nickmccurdy** [comment]
Can reproduce https://codesandbox.io/s/amazing-cdn-hyis6?file=/src/index.test.js

**Comment by ph-fritsche** [comment]
Thanks for the report :smiley: 

@all-contributors add @geoffroymounier bug

**Comment by ph-fritsche** [comment]
@all-contributors add @geoffroymounier bug

**Comment by metehansenol** [comment]
Seems like this is not possible in v14 anymore. Sad. Any solution?

**Comment by sbland** [comment]
For V14 the api has changed. See test here: https://github.com/testing-library/user-event/blob/7a305dee9ab833d6f338d567fc2e862b4838b76a/tests/pointer/click.ts#L290
