### ISSUE TITLE
Material UI FormControlLabel w/ TextField

### ISSUE THREAD

**Issue by fadi-george** [testing-library/user-event#448]
Hello,

I have been recently changing tests to use user-event instead of fire-event. I ran into an issue for a specific case where I had a TextField inside the label of a FormControlLabel component. For whatever reason, fireEvent.change and fireEvent.input both work in updating the textfield but user.type doesn't work at all.

You can it see when running the tests here:
https://codesandbox.io/s/react-hook-form-unit-test-docs-forked-5vjqg?file=/src/App.test.js

**Comment by ph-fritsche** [comment]
Your HTML structure violates standard for [`<label>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label). Don't expect anything from it.

> #### Permitted content
> Phrasing content, but no descendant label elements. No labelable elements other than the labeled control are allowed.

Therefore I'll close this issue.
Should you still have trouble testing after fixing your code, please comment below and I'll gladly reopen.
