### ISSUE TITLE
UserEvent.type does not target the correct input

### ISSUE THREAD

**Issue by youf-olivier** [testing-library/user-event#449]
Hello, 

I had to downgrade RTL for the SB (with the current version CSB doesn't work well), but on my project here my versions (the latests) : 

    "@testing-library/jest-dom": "5.11.4",
    "@testing-library/react": "11.0.2",
    "@testing-library/react-hooks": "3.4.1",
    "@testing-library/dom": "7.24.1",
    "@testing-library/user-event": "12.1.4",
    "react-scripts": "3.4.3",

When I use a selector, any one, I catch the correct input, but when I use UserEvent.type, it change the wrong input. 

Here is my CSB : https://codesandbox.io/s/bug-testinglibraryuserevent-n3kuh?file=/src/App.js

As you can see in the log console, I catch the correct input. I also tried to target only with a data-testid and the result is the same. 

When I use UserEvent.type(input, "123123123") the radio button is selected.

**Comment by ph-fritsche** [comment]
Your HTML structure violates standard for [`<label>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label). Don't expect anything from it.

> #### Permitted content
> Phrasing content, but no descendant label elements. No labelable elements other than the labeled control are allowed.

Therefore I'll close this issue.
Should you still have trouble testing after fixing your code, please comment below and I'll gladly reopen.
