### ISSUE TITLE
Textarea `type` does not respect selection range

### ISSUE THREAD

**Issue by dvargas92495** [testing-library/user-event#450]
- `@testing-library/user-event` version: 12.1.4
- Testing Framework and version: jest
- DOM Environment: jsdom

Relevant code or config:
Check out [this pull request](https://github.com/dvargas92495/user-event/pull/1). I added a test to demonstrate the use case I ran into and to show the bug. I don't intent to merge the PR, it's simple there to as a simple reproducible version of my issue.

What you did:
- Textarea has some text `"foo"`
- Call `textarea.setSelectionRange(0,0)` to put cursor at the beginning of the textarea.
- Call `type` to add some text `"bar"`
- Expected textarea value should have `"barfoo"` 

What happened:
- textarea value is `"foobar"`

Image of running the test locally:
![image](https://user-images.githubusercontent.com/7143571/92962586-28a15480-f43f-11ea-8fc4-25b825b86c1c.png)

Reproduction repository:
Check out [this pull request](https://github.com/dvargas92495/user-event/pull/1).

Somewhat hilariously, I'm actually using the library to simulate user behavior on [Roam](https://roamresearch.com). I know the library is not designed for that and meant for testing, is there any concern with using it in this way? I was able to reproduce the issue I was running into in a testing use case anyway, as evidenced by the linked pull request above.

Here's my relevant use case anyway: https://github.com/dvargas92495/roam-js-extensions/blob/master/src/entries/todont.ts#L51-L53

Problem description:
I would expect moving the cursor using `setSelectionRange` would result in subsequent `type` calls to respect that invocation.

Suggested solution:
I haven't dove into the `user-event` source code yet, but if we agree that this is a bug, I would love to take a shot a solving this!

**Comment by marcosvega91** [comment]
Hi @dvargas92495 thanks for reaching us :).

This is the normal behaviour of `user-event`. If  selection start and selection end are both 0 they'll be set to the length of the actual value of the `textarea`.

https://github.com/testing-library/user-event/blob/986e06aec056a99f26c9b119be78268d9605573a/src/type.js#L113-L119

To solve your problem you should pass `initialSelectionStart` and `initialSelectionEnd` options like

```js
userEvent.type(element, "Prefix: ",{initialSelectionStart:0, initialSelectionEnd: 0})
```

I hope this'll help you 😄 . Let me know if you need further assistance.

**Comment by dvargas92495** [comment]
hey @marcosvega91, thanks for getting back to me so quickly!

I'm really sorry for not doing my due diligence here. But it appears that I'm still facing the issue in my use case. I was also able to reproduce the behavior in the linked PR and see that the test still fails locally:

![image](https://user-images.githubusercontent.com/7143571/92965725-47eeb080-f444-11ea-9a47-113582d6e37e.png)

**Comment by marcosvega91** [comment]
I'll try to take a look at your code

**Comment by dvargas92495** [comment]
ah I needed to do both:
```javascript
element.setSelectionRange(0,0);
await userEvent.type(element, "Prefix: ", {initialSelectionStart: 0, initialSelectionEnd: 0});
```

going to close the linked PR! Thanks for your help!

**Comment by marcosvega91** [comment]
I was supsecting this but I didn't try yet. 
I was thinking if this is really correct. 

The the parameters are used only when the  initial selection is 0. I guess  they should be used everytime they are provided
