### ISSUE TITLE
Wrong paste event typings

### ISSUE THREAD

**Issue by nikpl7777** [testing-library/user-event#452]
There's a problem with typings for the paste event.
It accepts four arguments (and the documentation says about it), but typings expects only 3 arguments (`text` is omitted).

Lib version is `12.1.4`

If you approve of the issue, I can raise a PR to fix it.

**Comment by marcosvega91** [comment]
Hi @nikpl7777 thanks for raising this 😄 
I can confirm that is a bug. Feel free to open a PR for this. Thanks a lot 🎉
