### ISSUE TITLE
userEvent can't fire space key event callback 

### ISSUE THREAD

**Issue by Morteza-Jenabzadeh** [testing-library/user-event#462]
- `@testing-library/user-event` version: 9.3.2
- Testing Framework and version: jest default CRA
  
- DOM Environment: jsdom default CRA
  

Relevant code or config

```javascript
import React from "react";

const Button = (props) => {
  const { children, disabled, ...rest } = props;

  return (
    <button
      disabled={disabled}
      autoFocus={rest.autoFocus}
      onClick={rest.onClick}
      type={rest.type}
      onFocus={rest.onFocus}
    >
      {children}
    </button>
  );
};
export default Button;
```

What you did:
I have tried to write a test suite that onClick event of a button fired by pressing the space key
it works in real-world (chrome browser)

here is my test suite:
```js
  it("focus and enter should fire handle click", () => {
    const handleFocus = jest.fn();
    const handleClick = jest.fn();
    const ui = (
      <Button type="button" onFocus={handleFocus} onClick={handleClick}>
        {TEXT1}
      </Button>
    );
    const { container } = render(ui);
    const button = container.querySelector("button");

    fireEvent.focus(button);
    expect(handleFocus).toHaveBeenCalled();
    userEvent.type(screen.getByRole("button"), "{space}");
    expect(handleClick).toHaveBeenCalled();
  });
```
What happened:
but the onClick callback has never been called

```Expected number of calls: >= 1
    Received number of calls:    0
      79 |     expect(handleFocus).toHaveBeenCalled();
      80 |     userEvent.type(screen.getByRole("button"), "{space}");
    > 81 |     expect(handleClick).toHaveBeenCalled();
         |                         ^
      82 |   });
      83 | });
      84 |
```

Reproduction repository:

please check this repo the code is the minimum to run the test
https://github.com/Morteza-Jenabzadeh/react-test-library.git

PS: I have already used fireEvent `Enter on input` `fireEvent.keyDown(textbox, { key: 'Enter' });` https://github.com/mui-org/material-ui/issues/22648#issuecomment-699680768  
just confusing why I can't use fireEvent here is it because of space or because of button:?

**Comment by nickmccurdy** [comment]
These packages are out of date, please run `yarn upgrade --latest @testing-library/user-event @testing-library/react` to fix the issue.
