### ISSUE TITLE
create-react-app install 7.2.1 version of user-event

### ISSUE THREAD

**Issue by presentY1897** [testing-library/user-event#465]
When install create-react-app. The lower version of user-event installed. 
But install command of README.md cant upgrade installed version from create-react-app. 
```sh
npm install @testing-library/user-event @testing-library/dom --save-dev
```
Maybe need to update version user-event on create-react-app or add some comment on README.md.

**Comment by malwilley** [comment]
I just created a new CRA app and you're right that it comes with some outdated versions:

```json
"dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-scripts": "3.4.3"
  },
```

But I'm not familiar with CRA and where these versions are declared. I did a quick search in https://github.com/facebook/create-react-app and couldn't anything referencing such an old version.

Upgrading them shouldn't be an issue though. The command in the readme is for installing from scratch, but if you want to upgrade major versions you just need to add `@latest` to the package name:

```
npm install @testing-library/user-event@latest @testing-library/react@latest @testing-library/jest-dom@latest
```

**Comment by presentY1897** [comment]
I got understand. This issue doesn't seem feet in here. Thank you for your help.
