### ISSUE TITLE
Warning when onChange is using Promise.resolve "An update to %s inside a test  was not wrapped in act"

### ISSUE THREAD

**Issue by PeoB** [testing-library/user-event#472]
- `@testing-library/user-event` version: 12.1.3

- Testing Framework and version:
  
- DOM Environment:
  

Relevant code or config

```
import React, { useState } from "react";
import { act, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";

const Foo = () => {
  const [state, setState] = useState<string>();

  return (
    <div>
      <span>{state}</span>
      <label htmlFor="bar">Change me!</label>
      <input id="bar" onChange={() => Promise.resolve().then(() => setState("really?"))} />
    </div>
  );
};

describe("test edit email modal", () => {

  it("should deal with async event(failing)", async () => {
    render(<Foo/>);
    await userEvent.type(screen.getByRole("textbox", {name: "Change me!"}), "hi?");
    expect(await screen.findByText("really?")).toBeInTheDocument();

  });

  it("should deal with async event(success)", async () => {
    render(<Foo/>);
    await act(() => userEvent.type(screen.getByRole("textbox", {name: "Change me!"}), "hi?"));
    expect(await screen.findByText("really?")).toBeInTheDocument();
  });
});
```

What you did:

For some of our flows we have asynchronous validation of inputs. Full repro example above including applied workaround.

What happened:

The tests get a long list of **Warning: An update to %s inside a test was not wrapped in act(...)**

Workaround works as the validation is not _really_ async, it just goes through a promise based flow causing it to occur after userEvent considers everything to be completed.

Suggested solution:

Unsure, I think I'm looking for insights from you here. Should we consider this valid and wrap the event and the findByText in an act, or is this considered a bug?

**Comment by marcosvega91** [comment]
Hi @PeoB :),

This is an expected behaviour, I may suggest you to take a look at #424. 

```js

  it("should deal with async event", async () => {
    render(<Foo/>);
    userEvent.type(screen.getByRole("textbox", {name: "Change me!"}), "hi?");
    await wait for(()=>expect(await screen.findByText("really?")).toBeInTheDocument());
  });
```

If you want to read more about act, Kent has written an article  https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning

If you have any further problem let me know.
