### ISSUE TITLE
Input type doesn't work

### ISSUE THREAD

**Issue by olegKusov** [testing-library/user-event#476]
- `@testing-library/user-event` version: 12.1.10
- Testing Framework and version: jest
  
- DOM Environment:16.4.0
  

Relevant code or config

```
describe('components > Input', () => {
  let inputValue = '';
  const handleLoginInput = jest.fn(() => {
    inputValue = '23';
  });

  it('should change value if user inputs', () => {
    const {debug} = render(
      <Input handler={handleLoginInput} value={inputValue} placeholder='Login' />
    );
    debug();
    userEvent.type(screen.getByTestId('input'), '23');
    debug();
    expect(handleLoginInput).toHaveBeenCalledTimes(2);
    expect(screen.getByTestId('input')).toHaveValue(23);
  });
});
```

What you did:
Tried to test input

What happened:
input event doesn't work.
![image](https://user-images.githubusercontent.com/28058268/96887102-e848e380-148c-11eb-941e-d327f7475d14.png)

Input component

![image](https://user-images.githubusercontent.com/28058268/96887244-13cbce00-148d-11eb-9889-f72d829eebca.png)

**Comment by zimmicz** [comment]
@olegKusov how did you solve this?
