### ISSUE TITLE
Clicking on <option> inside <select> does not change the select's value in tests

### ISSUE THREAD

**Issue by DamianPereira** [testing-library/user-event#478]
- `@testing-library/user-event` version: 12.1.5

- Testing Framework and version: react scripts 4.0.0, which includes jest
- DOM Environment: jsdom, whatever versions comes with react scripts 4.0.0

Relevant code or config

DropdownForm:

```javascript
import React from 'react'

const DropdownForm = () => {
  return (
    <form>
      <select>
        <option value={1}>1</option>
        <option value={2}>2</option>
        <option value={3}>3</option>
      </select>
    </form>
  )
}

export default DropdownForm
```

DropdownForm.spec.js
```javascript
  import React from "react";
  import { render, screen } from "@testing-library/react";
  import userEvent from "@testing-library/user-event";
  import DropdownForm from "./Dropdown";

  it("changes the value", async () => {
    render(<DropdownForm />);
    const select = screen.getByRole("combobox");
    userEvent.click(select);
    const secondOption = screen.getByText("2");
    userEvent.click(secondOption);
    expect(select.value).toEqual("2");
  });

```

What you did: I'm trying to click on the second option, and assert that the new value of the input is the correct one.

What happened: Value is not updated after clicking a select option.

expect(received).toEqual(expected) // deep equality

```
Expected: "2"
Received: "1"

   9 |   userEvent.click(select)
  10 |   const secondOption = screen.getByText('2')
  11 |   userEvent.click(secondOption)
> 12 |   expect(select.value).toEqual('2')
```

Reproduction repository:

https://codesandbox.io/s/userevent-dropdown-bug-5yiog?file=/src/DropdownForm.js

Problem description: Value should be updated after clicking on an option, just like if a human user clicked on the option.

Suggested solution: Not sure why this is happening, maybe the tests has a mistake somewhere that I can not see.

**Comment by marcosvega91** [comment]
Hi @DamianPereira thanks for reaching us :)

I have made small changes to your code to make it works.

I have used `userEvent.selectOptions` function to select the right option and `toHaveVale` from `jest-dom` to assert the value.

https://codesandbox.io/s/userevent-dropdown-bug-forked-m11uh?file=/src/DropdownForm.spec.js

Let me know if you need further assistance :)

**Comment by DamianPereira** [comment]
Makes sense, it even works without toHaveValue. Any idea why click does not trigger a change? Shouldn't it be the same as a user clicking?

**Comment by marcosvega91** [comment]
`click` event is not enough because it will only trigger `click` event on the option but to make an element selected `change` event on the select is also required.

`userEvent.selectOptions` function will do all of this for you.

**Comment by DamianPereira** [comment]
So userEvent can only work on 1 element at the time, and can not call an event from a different element (in this case calling onChange when onClick of option is called), right?

I guess it makes sense, and it's good that there are alternatives for this common scenarios.

**Comment by marcosvega91** [comment]
`userEvent` simulates user interaction on the browser. You can have a look at https://codesandbox.io/s/quizzical-worker-eo909?file=/src/index.js. The example is very useful to understand which events the browser will fire when the user interacts with the UI. These events are fired by `userEvent` too.

`userEvent.selectOptions` will fire for a single select these events

- pointerdown
- mousedown
- focusin
- pointerup
- mouseup
- click
- input
- change

The events are fired on the select itself

**Comment by DamianPereira** [comment]
Makes sense, I'll look into it.

Thanks for the detailed explanation, it's awesome to be able to understand how the tools I use everyday actually work.

**Comment by marcosvega91** [comment]
You're welcome :)
