### ISSUE TITLE
v12.2.1 npm package doesn't include the dist directory

### ISSUE THREAD

**Issue by Saul-Mirone** [testing-library/user-event#492]
- `@testing-library/user-event` version: v12.2.1

- Testing Framework and version: 26.6.1
  
- DOM Environment:
  

Relevant code or config

```javascript
import userEvent from '@testing-library/user-event';
```

What you did:
Just install and import '@testing-library/user-event'

What happened:

<project>/node_modules/@testing-library/user-event path doesn't have the dist directory

Reproduction repository:

Problem description:

Suggested solution:

**Comment by kentcdodds** [comment]
Whoops! Sorry about that. This will be fixed ASAP.

@All-contributors please add @Saul-Mirone for bugs
