### ISSUE TITLE
Latest release of user-event has no dist directory

### ISSUE THREAD

**Issue by corbpaul** [testing-library/user-event#496]
- `@testing-library/user-event` version: 12.2.2

- Testing Framework and version: jest@26.6.3
  
- DOM Environment: jsdom (default from jest)
  

What you did:
Updated to latest version of @testing-library/user-event

What happened:
Library failed to load when running tests

Problem description:
Looking into `node_modules` dir, there is no dist directory under user-event

**Comment by marcosvega91** [comment]
Hi @corbpaul ,

It was a problem of the `12.2.1` https://unpkg.com/@testing-library/user-event@12.2.1/dist/index.js

The latest version `12.2.2` has the folder https://unpkg.com/@testing-library/user-event@12.2.2/dist/index.js

Be sure to have installed the right version. Use `npm ls @testing-library/user-event`` to check which version you have installed
