### ISSUE TITLE
Problems with custom input types

### ISSUE THREAD

**Issue by kserjey** [testing-library/user-event#501]
- `@testing-library/user-event` version: 12.2.2
- Testing Framework and version: CodeSandbox (actually I don't know how to get it)
- DOM Environment: CodeSandbox (actually I don't know how to get it)

Relevant code or config:

```javascript
const { getByRole } = render(<input type="number"/>);
const input = getByRole('spinbutton');
userEvent.type(input, '123{selectall}{backspace}');
```

Reproduction repository:

https://codesandbox.io/s/user-event-and-typenumber-c5i10

Problem description:

After spending some time trying to solve this issue I've found what causing it. JSDOM has a limitation on `setSelectionRange`: 

https://github.com/jsdom/jsdom/blob/c2fb8ff94917a4d45e2398543f5dd2a8fed0bdab/lib/jsdom/living/nodes/HTMLInputElement-impl.js#L45

And you have a little hack to make it work with `userEvent.clear`:

https://github.com/testing-library/user-event/blob/f7620ab4193707a403c08cddec52297d377479f7/src/clear.js#L12-L27

But if we are talking about type actions like `{selectall}`, well, it doesn't work for types other than `["text", "search", "url", "tel", "password"]`. For now I'm just using:

```javascript
const { getByRole } = render(<input type="number"/>);
const input = getByRole('spinbutton');
userEvent.type(input, '123');
userEvent.clear(input);
```

When I tried to move your hack to the `type.js`, I faced problems with testing (I can't test `selectionStart`, because it `null`) and I wasn't sure how to temporary change `element.type`.

**Comment by PuckmanXY** [comment]
Had the same problem here, thanks for pointing the workaround! :D

**Comment by ph-fritsche** [comment]
We should apply the workaround in the helper:
https://github.com/testing-library/user-event/blob/f251d153d55e43ec84c6012fa09352b251133f20/src/utils/edit/setSelectionRangeIfNecessary.ts#L39-L44
