### ISSUE TITLE
Typing event wrapped in act()

### ISSUE THREAD

**Issue by tozaicevas** [testing-library/user-event#505]
I believe this is not a bug, but rather my own lack of knowledge, so I'd appreciate if someone would help me figure this out!
In this code snippet, change event is not fired when 'Save changes' is clicked. Why?
```
        await act(async () => {
          fireEvent.change(titleInput, { target: { value: 'abcde' } })
          fireEvent.click(getByText('Save changes')) // change event has not fired
        })
```
On the other hand, this works fine:
```
        fireEvent.change(titleInput, { target: { value: 'abcde' } })
        await act(async () => {
          fireEvent.click(getByText('Save changes')) // change event is fired
        })
```

**Comment by ph-fritsche** [comment]
Without your setup and code under test one can only guess what your code is doing and what you're trying to achieve in the first place.
Your test should probably not contain any `act` and just look like this:
```js
userEvent.type(titleInput, 'abcde')
userEvent.click(getByText('Save changes'))
```

If you are using `@testing-library/react` your event listeners triggered by `fireEvent`/`userEvent` calls are already wrapped in `act`.
If you receive warnings about changes not wrapped in `act` your event listeners trigger changes asynchronously. You can start reading about this [in this issue](https://github.com/testing-library/user-event/issues/457).
