### ISSUE TITLE
Must (sometimes) wrap calls to `userEvent.click()` in `act()` when using sinon fake timers?

### ISSUE THREAD

**Issue by jwalton** [testing-library/user-event#518]
- `@testing-library/user-event` version: 12.2.2
- Testing Framework and version: jest@26.4.2, sinon@9.0.3
- DOM Environment: jsdom@16.4.0

Relevant code or config

```typescript
// useExample.tsx
import { useEffect, useState } from 'react';

export interface UseVideoSegmentsParams {
  suspendLoad: boolean;
}

export function useExample(params: UseVideoSegmentsParams): { loaded: boolean } {
  const [loaded, setLoaded] = useState(false);
  const { suspendLoad } = params;

  // Load short segment data.
  useEffect(() => {
    if (suspendLoad) {
      return;
    }

    loadData().then(() => {
      setLoaded(true);
    });
  }, [suspendLoad]);

  return { loaded };
}

async function loadData() {
  return true;
}
```

```typescript
// useExample.test.tsx
import { render } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import React, { useState } from 'react';
import { act } from 'react-dom/test-utils';
import sinon from 'sinon';
import { useExample } from './useExample';

function TestComponent() {
  const [suspendLoad, setAllowLoad] = useState(true);

  const { loaded } = useExample({ suspendLoad });

  return (
    <div>
      <button onClick={() => setAllowLoad(!suspendLoad)}>Allow load</button>
      <div>Has loaded: {loaded ? 'true' : 'false'}</div>
    </div>
  );
}

describe('useVideoSegments', () => {
  let clock: sinon.SinonFakeTimers;

  beforeEach(() => {
    clock = sinon.useFakeTimers();
  });


  afterEach(() => {
    jest.resetAllMocks();
    clock.restore();
  });

  it('will pass', async () => {
    const { getByText, findByText } = render(<TestComponent />);

    getByText('Has loaded: false');
    act(() => {
      userEvent.click(getByText('Allow load'));
    });
    await findByText('Has loaded: true');
  });

  it('will fail', async () => {
    const { getByText, findByText } = render(<TestComponent />);

    getByText('Has loaded: false');
    userEvent.click(getByText('Allow load'));
    await findByText('Has loaded: true');
  });
});

```

What you did:

There are two tests in this suite - both are identical, except one has a `userEvent.click()` wrapped in an `act()`, and the other has a bare `userEvent.click()`.

What happened:

The one with the `act()` passes, the one without fails:

```
-- snip --

TestingLibraryElementError: Unable to find an element with the text: Has loaded: true. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

-- snip --

  console.error
    Warning: An update to TestComponent inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in TestComponent

      16 |
      17 |     loadData().then(() => {
    > 18 |       setLoaded(true);
         |       ^
      19 |     });
      20 |   }, [suspendLoad]);
      21 |

-- snip --

```

If you attach a debugger to this, the `useEffect()` function isn't called until after the test ends.

Removing the call to `sinon.useFakeTimers();` makes both pass.

Reproduction repository:

See above.

Problem description:

`userEvent.click()` should behave the same when wrapped in an `act()` or not wrapped in an `act()`, regardless of whether or not sinon's fake timers are in use.  Alternatively, documentation should be provided about how to interact with sinon (do we need to call `clock.tick()` to advance the fake clock?  If so, by how much?)

Suggested solution:

???

**Comment by ph-fritsche** [comment]
`@testing-library/react` wraps the `fireEvent` calls in `act` so that state changes inside the event handler are already wrapped in `act`.
Your state change is triggered asynchronously and therefore can happen after `act` finishes. See #457.
Solutions how to test asynchronous state changes are suggested here: https://github.com/testing-library/user-event/issues/128#issuecomment-720515712

**Comment by jwalton** [comment]
> @testing-library/react wraps the fireEvent calls in act so that state changes inside the event handler are already wrapped in act.

And yet, if I wrap this in an `act()` it passes 100% of the time, and if I do not, if fails 100% of the time.

> Your state change is triggered asynchronously and therefore can happen after act finishes. See #457.
Solutions how to test asynchronous state changes are suggested here: #128 (comment)

If you have a look, you'll notice that it uses (more or less) the fix @kentcdodds himself suggests for these issues [here](https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning/#how-to-fix-the-act-warning).  We have a `await findByText('Has loaded: true');` that prevents the test from finishing until the async call completes.

Also, we can test your hypothesis with the following change:

```js
function loadData() {
  return new Promise((resolve) => setTimeout(() => resolve(true), 1000));
}
```

And then for good measure, let's modify the test cases to look like this:

```js
  it('will fail', async () => {
    const { getByText, findByText } = render(<TestComponent />);
    jest.setTimeout(50000);

    getByText('Has loaded: false');
    userEvent.click(getByText('Allow load'));
    clock.tick(1000);
    await findByText('Has loaded: true', {}, { timeout: 40000 });
  });
```

So now, 100% for sure, the useEffect will trigger outside the act().  But they shouldn't happen after the end of the test (because the test runs for 40 seconds, and the change should only take 1 - less, in fact, because of sinon's fake timers).  If you're right, and somehow my additional `act()` call is just adding a little bit of timing or something, then here both tests should fail, and they should both fail roughly immediately, but instead, the first passes 100% of the time (with no 'act' warnings, even though the async event happens outside the act), and the second fails every time, and takes 40 seconds to do so.  The `setState()` from the `useEffect()` hook is not being allowed to fire in the second case until after the test ends.

**Comment by ph-fritsche** [comment]
Your examples from the first post - both tests passing:
https://codesandbox.io/s/exciting-sanne-9l2w3

**Comment by jwalton** [comment]
So you're suggesting these pass in a browser but fail in node.js?

**Comment by ph-fritsche** [comment]
I'm suggesting something in your setup is messing with the order of the event loop and your test relies on such order - while you give up control over the order when using asynchronous calls in the first place.

Your test can only pass without warning in certain scenarios, making your test effectively test your event loop order not your component.

> ```js
> act( /* Here you pass a function to act */ async () => {
>   /* Perform your click/type/selectOption ...*/
> 
>   await thePromiseThatResolvesWhenValidationIsDone // wait for the change
> 
>   /* Here you return from what is done inside act.
>      If any change happens later (but before the test ends) you will receive a warning. */
> })
> ```
> 
> See https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop
> When you use `setTimeout` or `Promise` you give up control over the order of operations. They will be added somewhere down the event loop and your code returns instantly.
> If your code is simple, you can, of course, predict in which order the statements will be executed. But you should not rely on that.
