### ISSUE TITLE
userEvent.type(input, '10') is not update the input value

### ISSUE THREAD

**Issue by jerry5789k1** [testing-library/user-event#519]
Relevant code or config

```javascript
test('entering an invalid value shows an error message', () => {
  render(<FavoriteNumber />)
  const input = screen.getByLabelText(/favorite number/i)
  userEvent.type(input, '10')
  screen.debug(input)
  expect(screen.getByRole('alert')).toHaveTextContent(/The number is invalid/i)
})

```
Favorite Number Component
```javascript
import * as React from 'react'

function FavoriteNumber({min = 1, max = 9}) {
  const [number, setNumber] = React.useState(0)
  const [numberEntered, setNumberEntered] = React.useState(false)
  function handleChange(event) {
    setNumber(Number(event.target.value))
    setNumberEntered(true)
  }
  const isValid = !numberEntered || (number >= min && number <= max)
  return (
    <div>
      <label htmlFor="favorite-number">Favorite Number</label>
      <input
        id="favorite-number"
        type="number"
        value={number}
        onChange={handleChange}
      />
      {isValid ? null : <div role="alert">The number is invalid</div>}
    </div>
  )
}

export {FavoriteNumber}
```

testing-library version
```javascript
"@testing-library/dom": "^7.29.0",
    "@testing-library/jest-dom": "^5.11.6",
    "@testing-library/react": "^11.2.2",
    "@testing-library/react-hooks": "^3.7.0",
    "@testing-library/user-event": "^12.5.0",
```

What you did:
npm run test

What happened:
I should see the input value updated into 10 instead of 0 in my terminal console 

I saw a similar issue https://github.com/testing-library/user-event/issues/411

**Comment by jerry5789k1** [comment]
fireEvent is working as expected.

**Comment by ph-fritsche** [comment]
Works as expected:
https://codesandbox.io/s/great-varahamihira-7i0f2?file=/src/FavoriteNumber.test.js

If you still think there is a problem with userEvent or if you need assistance how to use it, please set up a minimal working example of your problem on [codesandbox.io](https://codesandbox.io/) or another platform.

**Comment by vvscode** [comment]
@ph-fritsche  here is an example https://codesandbox.io/s/pensive-rgb-tcxije?file=/src/App.test.tsx

**Comment by NarekPoghosyan** [comment]
@jerry5789k1 Hack: You must clear the value before adding

    const input = await canvas.findByTestId('email_field_data_test_id')
    await wait(800)
    await userEvent.click(input)
    await userEvent.clear(input)
    await userEvent.type(input, 'test@mail.ru')
    await wait(800)
    await userEvent.click(await canvas.findByTestId('click_to_submit_user_form_3'))

    await wait(800)
  })

**Comment by NarekPoghosyan** [comment]
Hack 2: If you need try with empty value.
    
    const input = await canvas.findByTestId('email_field_data_test_id')
    
    await userEvent.clear(input)
    await userEvent.type(input, '' || '{tab}')
