### ISSUE TITLE
Return type of userEvent.type not always a promise

### ISSUE THREAD

**Issue by frontendphil** [testing-library/user-event#527]
As stated in the docs `userEvent.type` always returns a promise but you only need to `await` it if you're using the `delay` option. Is it sensible to still change the typescript type to **always** be `Promise` in this case? I'm asking because I'm working in a `vue` app and even though I don't use the `delay` option I actually need to `await` the result because `vue` will not have applied the changes otherwise. However, when I put `await` in front of `userEvent.type` I get a warning that `await` won't have an effect here (even though it does). 

Is that too `vue` specific or something that you'd be willing to change when I submit a PR?

**Comment by nickmccurdy** [comment]
This is accurate and still an issue, but it's already covered in #504 so I'll close it as a duplicate.
