### ISSUE TITLE
Add possibility to dispatch click on document

### ISSUE THREAD

**Issue by pakhuta** [testing-library/user-event#531]
- `@testing-library/user-event` version: 12.6.0

- Testing Framework and version: Jest v. 26.6
- DOM Environment:  jsdom v. 16.4.0

Relevant code or config

```typescript
userEvent.click(document); // typescript
```

What you did:
I render a component which subscribes on clicks on document level to be able handle clicks outside the component.

What happened:

> TS2345: Argument of type 'Document' is not assignable to parameter of type 'TargetElement'.   Type 'Document' is missing the following properties from type 'Window': applicationCache, clientInformation, closed, customElements, and 134 more.

Reproduction repository:
none

Problem description:
The problem in definition of types of click method:
```ts
click: (
    element: TargetElement, // <-- issue is here
    init?: MouseEventInit,
    options?: IClickOptions,
  ) => void
```
where
```ts
export type TargetElement = Element | Window
```

Suggested solution:
```ts
click: (
    element: TargetElement | Document, // or create new type instead of using a union
    init?: MouseEventInit,
    options?: IClickOptions,
  ) => void
```

P.S. Also it's relevant for `dblClick` event.

**Comment by ph-fritsche** [comment]
There are no clicks on `document` in the browser.

If you want to click outside of your component, you can use:
```js
userEvent.click(document.body)
```

Clicks outside of `HTMLBodyElement` (if you manipulate the style so that body does not stretch to the viewport) are performed on `HTMLHtmlElement`.

**Comment by pakhuta** [comment]
Brilliant, thanks!
