### ISSUE TITLE
Populate KeyboardEvent.code property

### ISSUE THREAD

**Issue by pakhuta** [testing-library/user-event#532]
@testing-library/user-event version: 12.6.0
Testing Framework and version: Jest v. 26.6
DOM Environment: jsdom v. 16.4.0

**Relevant code or config**

```typescript
// test:
userEvent.type(ui.input.get(), '{arrowdown}');


// code:
switch (event.code) { // "user-event" doesn't fill this property properly: event.code === ''
    case 'ArrowDown': {
        ...
    }
}
```

**What you did:**
I handle keyboard event by key code.

**What happened:**

Generated by package event doesn't contain value of event.code (actually it contains an empty string)

**Reproduction repository:**
none

**Problem description:**
In [type.js](https://github.com/testing-library/user-event/blob/master/src/type.js#L754) file for example for event of pressing "ArrowDown" key populated properties such as `key` and `keyCode` but not a `code`:
```ts
function handleArrowDown({currentElement, eventOverrides}) {
  const key = 'ArrowDown'
  const keyCode = 40

  _dom.fireEvent.keyDown(currentElement(), {
    key,
    keyCode,
    which: keyCode,
    ...eventOverrides
  });

  ...
}
```

**Suggested solution:**
Adding `code` to corresponding places, e.g.:
```ts
function handleArrowDown({currentElement, eventOverrides}) {
  const key = 'ArrowDown'
  const keyCode = 40
  const code = 'ArrowDown';

  _dom.fireEvent.keyDown(currentElement(), {
    code,
    key,
    keyCode,
    which: keyCode,
    ...eventOverrides
  });
  ...
}
```

Also it should be done for all other keys.

P.S. `code` looks like the same as `key` but it is not. Value of `code` is independent of modifiers like `shift` and used language.

**Comment by ph-fritsche** [comment]
See #456 and #521

**Comment by pakhuta** [comment]
Thanks. I closed the ticket as duplicate.
