### ISSUE TITLE
test debounce function,test result is different every time

### ISSUE THREAD

**Issue by nieyao** [testing-library/user-event#535]
- DOM Environment:
  

Relevant code or config

```javascript

```

What you did:

What happened:

Reproduction repository:
import React from 'react';
import { render, cleanup } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import DebounceSearchInput from '../../../src/components/Table/DebounceSearchInput';

const handleUpdateTableData = jest.fn();

describe('DebounceSearchInput', () => {
  const { getByRole, getByTestId, container } = render(
    <DebounceSearchInput width={100} onUpdateTableData={handleUpdateTableData} data-testid="12" />
  );
  const inputInstance = container.querySelector('[data-testid="12"]');

  test('handleUpdateTableData called one time', async () => {
    await userEvent.type(inputInstance, 'abcdefg', { delay: 298 });
    expect(handleUpdateTableData).toHaveBeenCalledTimes(1);
  });
});

Problem description: test debounce function,test result is different every time

Suggested solution:

**Comment by ph-fritsche** [comment]
This issue lacks information to reproduce the issue as it depends on undisclosed components under test.
If the the issue can be reproduced on codesandbox without third-party components or with a minimal working example including the required third-party components, please add a link to it.
For now, I'll close this.
