### ISSUE TITLE
userEvent.type doesn't work with numbers that have exponents

### ISSUE THREAD

**Issue by martin-watts** [testing-library/user-event#540]
- `@testing-library/user-event` version: 12.6.0

- Testing Framework and version: jest@26.6.3
  
- DOM Environment: jsdom@16.4.0
  

Relevant code or config

I made a codesandbox.io to replicate the issue: https://codesandbox.io/s/usereventtype-on-number-input-cgc13

What you did: Try to use `userEvent.type` to type a number that contains an exponent.

What happened: You only end up with the exponent in the input, because the value of the field changes to `''` as soon as `e` is 'typed'

Reproduction repository: (See the codesandbox above)

Problem description: `userEvent.type` doesn't handle numbers with exponents

Suggested solution: Make this a test case for the `userEvent.type` re-work (https://github.com/testing-library/user-event/issues/521)

**Comment by ph-fritsche** [comment]
Resolved in [v13.0.0](https://github.com/testing-library/user-event/releases/tag/v13.0.0) :rocket:
