### ISSUE TITLE
Feature Request: IntersectionObserver support

### ISSUE THREAD

**Issue by jamesarosen** [testing-library/user-event#541]
- `@testing-library/user-event` version: 12.6.0
- Testing Framework and version: jest@24.5.0

I'm trying to test an `<img>` (really a `<CloudinaryImage>` from [cloudinary-react](https://www.npmjs.com/package/cloudinary-react)) that uses `IntersectionObserver` to lazily set `src` when the `<img>` is visible.

I'd love a way to simulate the scrolling behavior that causes the `InersectionObserver` to fire. Perhaps something like
```js
const img = container.querySelector('img')

userEvent.scrollOutOfView(img)
expect(img.src).toBeNull()
userEvent.scrollIntoView(img)
expect(img.src).not.toBeNull()
```

**Comment by ph-fritsche** [comment]
See [this comment](https://github.com/testing-library/user-event/issues/440#issuecomment-685010755) on drag&drop.

This library aims to be usable in a jest/jsdom environment. Tests heavily relying on the layout (position / size / visibility of an element) add little confidence as there is no layout in the primary test environment.

But we are open to PRs if they provide a consistent implementation across real browsers and jsdom.
