### ISSUE TITLE
document.elementFromPoint is not a function.

### ISSUE THREAD

**Issue by simonssspirit** [testing-library/user-event#544]
We are using the elementFromPoint method internally to get an element inside the document:

````
export function getIndex(event: any, parent: HTMLTableRowElement | HTMLDivElement | null) {
    if (!parent || !event || !event.originalEvent) {
        return -1;
    }
    let target: Element | null = document ? document.elementFromPoint(event.clientX, event.originalEvent.clientY) : null;
````

The method is working as expected in a standard case, but when testing it is giving the following error:

````
Uncaught [TypeError: document.elementFromPoint is not a function]
````

Could you please advise if testing-library is creating a document that has all available methods of the real document, or this need to be added?

**Comment by ph-fritsche** [comment]
Testing-library does not provide the `document`. Your testing environment does.
If you're using JSDOM (which I guess you do), there is no layout, just the DOM.
So features depending on layout cannot work and are therefore not implemented.
