### ISSUE TITLE
Swipe event 

### ISSUE THREAD

**Issue by vivek1996** [testing-library/user-event#545]
It would be great if the library support swipe events as many sites on mobile use gestures for some interactions.

**Comment by ph-fritsche** [comment]
Gesture events are non-standard.

An implementation based on [TouchEvent](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent) would be welcome, but it has to provide a solution how to deal with the absence of layout in jsdom.

I'll close this for now. If someone comes up with a more detailed idea for an implementation, I'll gladly reopen.
