### ISSUE TITLE
Add ES modules to the bundle

### ISSUE THREAD

**Issue by manuel-mauky** [testing-library/user-event#547]
- `@testing-library/user-event` version: 12.6.0

- Testing Framework and version: [web-test-runner](https://www.npmjs.com/package/@web/test-runner)
- DOM Environment: Chrome latest

What you did: I'm trying to use your library with `@web/test-runner` but it fails because the bundle of `@testing-library/user-event` does not provide an ES module.
I'm creating plain web components so I don't need webpack or a similar tool to transform code but only use the module and import feature that modern browsers support. Web-test-runner is a tool that leverages this to run tests. However, it only works with third-party-libraries that also support ES modules.

What happened:
I've created a reproduction repository and when I run the tests I get the message `SyntaxError: The requested module './../node_modules/@testing-library/user-event/dist/index.js' does not provide an export named 'default'`.
This message indicates that `index.js` is not an ES Module.

Reproduction repository: https://github.com/manuel-mauky/repro_testing_library_esm

Suggested solution:
In addition to the current CJS files, bundle your library as ES modules. Many libraries are doing this by adding a separate folder in their bundle that contains the ES modules or use a different file ending like `index.esm.js` or `index.mjs`.
In the package.json you have to point to this file with `module: 'dist/esm/index.js'`.
This should then not interfere with existing tools that are using the common-js files.

**Comment by ph-fritsche** [comment]
This repo uses the `build` by [kcd-scripts](https://github.com/kentcdodds/kcd-scripts/).

It might be worth discussing there if adding ESM or replacing CJM entirely is the way to go.
