### ISSUE TITLE
userEvent.type(...) does not work if an input or its container contain default-prevented onMouseDown/Up event

### ISSUE THREAD

**Issue by d4rekanguok** [testing-library/user-event#548]
- `@testing-library/user-event` version: 12.6.2

- Testing Framework and version: jest@26.6.3
- DOM Environment: jsdom@16.4.0

Relevant code or config

```javascript
import React from 'react'
import { render, fireEvent } from '@testing-library/react'
import userEvent from '@testing-library/user-event'

test('input with prevented mouseDown event', () => {
  const state = { value: '' }
  const handleChange = jest.fn(e => (state.value = e.target.value))
  const { getByRole } = render(
    <div>
      <input
        type="text"
        value={state.value}
        onChange={handleChange}
        onMouseDown={(e) => void e.preventDefault()}
      />
    </div>
  )
  const $input = getByRole('textbox')
  
  const sample = 'hello world'
  userEvent.type($input, sample)

  expect(handleChange).toHaveBeenCalledTimes(sample.length)
})
```

What you did:
Hi! I've been adding tests for a set of react input components. They support click & drag events & have `onMouseUp` & `onMouseDown` attached.

What happened:

I noticed that `userEvent.type(...)` does not work if one of the attached mouse events is default-prevented.

Reproduction repository:
https://github.com/d4rekanguok/repro-input-mouse

Problem description:
Removing `e.preventDefault()` seems to have no affect on the components, however this is definitely an unexpected behavior-- if it's actually a problem with userEvent.

Suggested solution:

**Comment by ph-fritsche** [comment]
`userEvent.type` does per default click the element before typing to move the focus to the given element.

If you `preventDefault` on the `mousedown` event the element does not gain focus.
The subsequent events happen on the `activeElement` which is still the `document` and not the `input`.

```js
  $input.focus()
  userEvent.type($input, sample)
```

**Comment by d4rekanguok** [comment]
gotcha, thanks
