### ISSUE TITLE
How are we meant to test controlled components? 

### ISSUE THREAD

**Issue by dwjohnston** [testing-library/user-event#549]
"@testing-library/user-event": "^12.1.10", (From CRA) -   "version": "12.6.0" in node modules. 

- Testing Framework and version:
  
- DOM Environment:
  
  
  Jest. 

I've copied the code from this closed issue: https://github.com/testing-library/user-event/issues/307

```
import React from "react";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";

test("THE BUGGED TEST", async () => {
  let formValue = "";
  const setFormValue = jest.fn((newFormValue) => {
    formValue = newFormValue;
  });

  render(
    <input
      data-testid="thisinput"
      type="text"
      value={formValue}
      onChange={(event) => setFormValue(event.target.value)}
    />
  );

  await userEvent.type(screen.getByTestId("thisinput"), "Ben Mayer");

  expect(setFormValue).toHaveBeenCalledWith("Ben Mayer");

  expect(screen.getByTestId("thisinput")).toHaveDisplayValue("Ben Mayer");
});
```

The output I get is: 

```
 FAIL  src/TestSandbox.test.tsx
  ✕ THE BUGGED TEST (55 ms)

  ● THE BUGGED TEST

    expect(jest.fn()).toHaveBeenCalledWith(...expected)

    Expected: "Ben Mayer"
    Received
           1: "B"
           2: "e"
           3: "n"

    Number of calls: 9

      20 |   await userEvent.type(screen.getByTestId("thisinput"), "Ben Mayer");
      21 |
    > 22 |   expect(setFormValue).toHaveBeenCalledWith("Ben Mayer");
         |                        ^
      23 |
      24 |   expect(screen.getByTestId("thisinput")).toHaveDisplayValue("Ben Mayer");
      25 | });

      at Object.<anonymous>.test (src/TestSandbox.test.tsx:22:24)

```

This makes sense to me as I can't see that reassigning the 'formValue' variable will cause a rerender for RTL. 

However, from reading the issue thread, it looks like Kent is saying that it should work? 

I've searched 'controlled components' across the User Events github issues, and that's the only issue for it. 

How are we mean to test controlled components, like a simple text field like this? Can an example be added to the main readme?

**Comment by ph-fritsche** [comment]
The issue you mentioned is closed because it does not describe an issue with testing-library.

userEvent applies the input character by character just as typing in your browser would.

Testing your controlled component is probably more straightforward than you thought:
```js
import React, {useState} from 'react'
import {render, screen} from '@testing-library/react'
import userEvent from '@testing-library/user-event'

function MyComponent() {
  const [value, setValue] = useState('')

  return (
    <div>
      <input value={value} onChange={(event) => setValue(event.target.value)} />
      <span data-testid="output">{value}</span>
    </div>
  )
}

test('controlled component', () => {
  render(<MyComponent />)

  userEvent.type(screen.getByRole('textbox'), 'Ben Mayer')

  // if your component produces some sort of output, testing output/effect is recommended
  expect(screen.getByTestId('output')).toHaveTextContent('Ben Mayer')

  // or if you want to test the input field itself
  expect(screen.getByRole('textbox')).toHaveValue('Ben Mayer')
})
```

**Comment by dwjohnston** [comment]
@ph-fritsche you might be misunderstanding what I mean by controlled component in this case What I mean is where 'the value of the component is controlled by its parent.

Eg. 

```
function MyComponent(props) {
  const {value, onChange} = props; 

  return (
    <div>
      <input value={value} onChange={(event) => onChange(event.target.value)} />
      <span data-testid="output">{value}</span>
    </div>
  )
}
```

**Comment by ph-fritsche** [comment]
The value of the `input` component is controlled by its parent `MyComponent`.

```js
function MyOuterComponent() {
  const [value, setValue] = useState('')
  const onChange = useCallback((event) => setValue(event.target.value), [
    setValue,
  ])

  return <MyInnerComponent value={value} onChange={onChange} />
}

function MyInnerComponent({value, onChange}) {
  return (
    <div>
      <input value={value} onChange={onChange} />
      <span data-testid="output">{value}</span>
    </div>
  )
}

test('nested component', () => {
  render(<MyOuterComponent />)

  userEvent.type(screen.getByRole('textbox'), 'Ben Mayer')

  // if your component produces some sort of output, testing output/effect is recommended
  expect(screen.getByTestId('output')).toHaveTextContent('Ben Mayer')

  // or if you want to test the input field itself
  expect(screen.getByRole('textbox')).toHaveValue('Ben Mayer')
})
```

Maybe you want to share an example of what you're struggling with.

**Comment by dwjohnston** [comment]
No, yip, what you've got there is one approach I considered. 

However, a little bit of a pain to do it for every controlled component I've got. 

I guess one could create a 'state containing' HOC that will do it for all cases.

**Comment by dwjohnston** [comment]
The alternative, is to just use `paste`, which will give everything in a single change event.

**Comment by ph-fritsche** [comment]
> However, a little bit of a pain to do it for every controlled component I've got.

I'm not sure I understand your problem.\
If your components are not exposed, i.e. only used as internal components, you might want to test them by using your exported components who manage state. (So that you test the expected behavior and not implementation details.)\
If your components are exported, i.e. as part of a library, you might want to use a setup function providing the required environment.

> I guess one could create a 'state containing' HOC that will do it for all cases.

There is no way to guess the requirements of your components.

I'd very much like to help, but I guess you have to provide a concrete example of your problem. Otherwise we're just producing a long list of guesses what your problem might be that you can shut down one by one...

**Comment by dwjohnston** [comment]
>I'd very much like to help, but I guess you have to provide a concrete example of your problem. Otherwise we're just producing a long list of guesses what your problem might be that you can shut down one by one...

Ok, so basically I'm just starting to use RTL for testing, so there's a wide range of use cases and 'how do I...?' type questions. 


But to give you a solid example of where this came up, there are two parts of it: 


**Use case one - an exported design library**

We have a design library of basic components, that tend to be controlled components,  that we export for use anywhere. 

eg: 


```

const MyTextInput = ({value, label, onChange}) => {

  return <label>{label}<input type ="text" value = {value} onChange = {(e) => onChange(e.target.value)}/></label>;
}

const MyCheckbox = ({isChecked, label, onChange}) => {

  return <label>{label}<input type ="checkbox" checked = {isChecked} onChange = {(e) => onChange(!isChecked)}/></label>;
}
```

For these the main test I want is that when the user enters some text, the onChange is fired with the actual value, rather than the event. Just a simple sanity test. 


**Use case two, dynamic form generation** 

Elsewhere we have a tool that produces dynamic forms. 

```
const formItemMapper = {

  "text": {
    jsx: ({onChange, id, value }) => {
      return <MyTextInput value = {value} label = {id} onChange = {(value) => onChange(value, id)}/> 
    }
  }, 
  "checkbox": {
    jsx: ({onChange, id, value }) => {
      return <MyCheckbox isChecked = {value} label = {id} onChange = {(value) => onChange(value, id)}/> 
    }
  }
}

const DynamicForm = ({formItems, onChange, dynamicFormValues}) => {

  return <div> 
      {formItems.map((v) => {
        
        const Comp = formItemMapper[v.type].jsx; 
        return <Comp key = {v.id} onChange = {onChange} value = {dynamicFormValues[v.id]} id = {v.id}/> 

      })}

    </div> 
}
```

Usage: 

```
      <DynamicForm formItems = {[
        {
          type: "text", 
          id: "first name", 
        }, 
        {
          type: "text", 
          id: "last name"
        }, 
        {
          type: "checkbox", 
          id: "subscribe"
        }
      ]}
        dynamicFormValues = {dynamicForm}
        onChange = {handleDynamicFormChange}
      />
```


Full example of this code here: 

https://github.com/dwjohnston/dynamic-form-example

For this, I want to write tests like: 

> If I create a dynamic for with the formItems: 
```
  {
          type: "text", 
          id: "first name", 
        }, 
        {
          type: "text", 
          id: "last name"
        }, 
        {
          type: "checkbox", 
          id: "subscribe"
        }
```

>then I want there to be a text field with label 'first name' a text field with label 'last name' and a checkbox with label 'subscribe'. 

and 

> When the user types 'hello' into the textfield with label 'first name' then I want onChange to be fired with 'hello', 'first name'



The problem of course is that I need something to provide state in order for this to work, as you have done with the `MyOuterComponent`. 

As you say: 

>you might want to test them by using your exported components who manage state. 

So yes, in this scenario, I could test the the main `<App/>` component. 

But I'm not sure I like this. It feels less like unit tests and more like end to end testing.

**Comment by ph-fritsche** [comment]
Thanks for providing these informations. I understand your problem is more how to organize your tests than how to actually write them.

> It feels less like unit tests and more like end to end testing. Like I should be able to test my component in an application-non-specific context.

Some might stone me for this, but I feel like tests should reflect your codes objective and the risks to produce bugs instead of some philosophy.
So for a lot of simple components this means that a strict "unit test" would basically just protect you from a typo by requiring you to type it twice (once in the component and once in the test). This sounds useless to me and is rendered even more useless by autocompletion and the like.
The DRY devil has possessed me regarding code as well as in the test, so whenever an additional test requires more copy and paste than original typing there is probably a better way.
That said, let's head over to your scenarios:

### Setup function to test similar components

You should use a setup function in your component tests that reflects the expected environment for your components like:
```js
// test/_setup.js
export function setup(FormComponent, props) {
  let onChange
  function TestEnvironment() {
    const [value, setValue] = useState(props.value)

    onChange = jest.fn(v => setValue(v))

    return <FormComponent id={props.id} value={value} onChange={onChange}/>
  }
  render(<TestEnvironment/>)
  return { onChange }
}
```
```js
// test/components.js
import { setup } from './_setup'

test('render editable text input', () => {
  const { onChange } = setup(MyTextInput, {id: 'someField', value 'someValue'})

  userEvent.type(screen.getByLabel('someField'), 'Foo')

  expect(onChange).toBeLastCalledWith('someValueFoo')
  expect(screen.getByLabel('someField')).toHaveValue('someValueFoo')
})
```
This tests your exported components against the behavior and with the requirements you laid out for the consumers of your library.
It prevents you from repeating yourself in the tests and also makes the test much more readable.

### Testing wiring of components

If your `DynamicForm` does some magic with the props you can test if you pass down the correct results at the correct spots by inspecting the rendered React tree with [react-test-renderer](https://reactjs.org/docs/test-renderer.html).

If you don't do some magic, your tests will just be a repetition of `FormItemMapper`. (imho see above)
You can however improve your confidence in passing down correct props at correct places by using TypeScript.

### Dependency Injection

If you manage state up the tree, you can make your state managing component more testable by making the used components injectable.

```js
// src/App.js
import { UserSignUp, PaymentDetails, AccountDetails, DynamicForm } from './components'

export function App({
  UserSignUpComponent = UserSignUp,
  PaymentDetailsComponent = PaymentDetails,
  AccountDetailsComponent = AccountDetails,
  DynamicFormComponent = DynamicForm,
} = {}) {
  // ...
  <DynamicFormComponent />
  // ...
}
```
```js
// test/components/_setup.js
const mockComponents = {
  UserSignUpComponent = 'div',
  PaymentDetailsComponent = 'div',
  AccountDetailsComponent = 'div',
  DynamicFormComponent = 'div',
}
export function setup(components) {
  // ...
  render(<App {...mockComponents} {...components}/>)
  // ...
}
```
```js
// test/components/DynamicForm.js
import { setup } from './_setup'
test('some test', () => {
  setup({MyDynamicForm})
  // ...
}
```

**Comment by dwjohnston** [comment]
Great, thanks for your help. 

It does look like the solution is to create some kind HOC (eg. your `setup` function) test utility that provides the state management.

**Comment by geryogam** [comment]
@ph-fritsche for providing solutions. Your `setup` function did not work for me though because it is called only once even on multiple character input on keyboard. The problem is that the mock `onChange` function is redefined at each render of the uncontrolled `TestEnvironment` component, so it does not accumulate information across calls.

Here is the solution that worked for me:

```javascript
import { useState } from 'react';
import { render, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { ControlledComponent } from './ControlledComponent'

const ControllingComponent = ({
  defaultValue,
  mockOnChange,
  ...rest
} => {
  const [value, setValue] = useState(defaultValue);
  mockOnChange.mockImplementation(v => setValue(v));
  return (
    <ControlledComponent value={value} onChange={mockOnChange} {...rest} />
  );
};

test('should call onChange on keyboard input', async () => {
  const user = userEvent.setup();
  const defaultValue = '';
  const mockOnChange = jest.fn();
  render(
    <ControllingComponent
      defaultValue={defaultValue}
      mockOnChange={mockOnChange}
    />,
  );
  await user.keyboard('abc');
  await waitFor(() => expect(mockOnChange).toHaveBeenCalledTimes(3));
  await waitFor(() => expect(mockOnChange).toHaveBeenNthCalledWith(1, 'a'));
  await waitFor(() => expect(mockOnChange).toHaveBeenNthCalledWith(2, 'ab'));
  await waitFor(() => expect(mockOnChange).toHaveBeenNthCalledWith(3, 'abc'));
});
```
