### ISSUE TITLE
userEvent.type doesn't change the value of the input

### ISSUE THREAD

**Issue by daniele-zurico** [testing-library/user-event#573]
Hi there,
I'm struggling to understand why the userEvent.type doesn't change the value of the input. This is my small repro:
```js
export const Input = ({handleChange, value}) => (
    <input type="text" value={value} onChange={handleChange} />
)
```
test:
```js
it('should display the Input value', () => {
    const handleChange = jest.fn();
    render(<Input handleChange={handleChange} value="test"/>);
    const input:any = screen.getByRole("textbox")
    userEvent.type(input, 'TEST VALUE');
    expect(input.value).toBe('TEST VALUE')
  })
```
result:
Expected: "TEST VALUE"
Received: "test"

to make it work I can wrap the Input component in another container component something like:
```js
const DummyParent = () => {
  const [value, setValue] = React.useState("");
  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setValue(event.target.value)
  }
  return (
      <Input value={value} handleChange={handleChange} />
  )
}
```
and then test the DummyParent but I was wondering if I can avoid that.

**Comment by ph-fritsche** [comment]
I don't really understand why you would open an issue here, when you already receive explanations on [Discord](https://discord.com/channels/723559267868737556/723565903228305549).
Anyway:

Your [controlled component](https://reactjs.org/docs/forms.html#controlled-components) will not behave [uncontrolled](https://reactjs.org/docs/uncontrolled-components.html).
Also you're trying to test something that is out of the scope of the unit under test.
As pointed out on Discord you should either render the component that includes the functionality you are testing or adjust the scope of your test to the functionality that the component you're using provides.
Alternatively you can use a wrapper like you mentioned to provide functionality that is out of the scope of your component but required environment for your component when being used.
