### ISSUE TITLE
userEvent.type return empty string with <input type="time">

### ISSUE THREAD

**Issue by waystilos** [testing-library/user-event#582]
- `@testing-library/user-event` version :12.8.3

- Testing Framework and version: `jest` version:26.6.3

- DOM Environment: `@testing-library/jest-dom` version:5.11.6

Relevant code or config

```
 test('input selects time', () => {
   render(<TravelDetails />)

   const timePicker = screen.getByLabelText(/^time$/i)

   userEvent.type(timePicker, '01:01')

   expect(timePicker).toHaveAttribute('type', 'time')
   expect(timePicker).toBe('01:01')
 })
```

What you did:  called userEvent.type on <input type="time">

What happened: The input value is an empty string. 

Error (I didn't add .value to show that the dom element is being captured):

```
    Expected: "09:09"
    Received: <input aria-invalid="false" aria-labelledby="TextFieldLabel41" class="ms-TextField-field field-130" id="TextField39" placeholder="Time" type="time" value="" />
```
Problem description: It's not typing the values within the input.

**Comment by ph-fritsche** [comment]
Typing into an input does not change the element attribute (`element.getAttribute('value')`), that is to be expected.
But it should change the IDL value (`element.value`).

Could you reproduce the behavior in a [sandbox](https://codesandbox.io) please?
We don't have the `TravelDetails` component and can not rule out a bug there.

**Comment by waystilos** [comment]
> Typing into an input does not change the element attribute (`element.getAttribute('value')`), that is to be expected.
> But it should change the IDL value (`element.value`).
> 
> Could you reproduce the behavior in a [sandbox](https://codesandbox.io) please?
> We don't have the `TravelDetails` component and can not rule out a bug there.

It works as expected when I recreated it without the component library I'm using so I'm closing this. Thanks for the response though, I appreciate it.
