### ISSUE TITLE
feat: advanceTimers callback

### ISSUE THREAD

**Issue by ph-fritsche** [testing-library/user-event#585]
@ph-fritsche - Would it be possible to add an `advance` option to type?
The typeImpl function could then call that with the delay before `await` ing on the promise.

As an example of the approach, I'm using this "wrapper" around type (it only works for plaintext):
```
async function typeWithDelay(input, text, delayInMilliseconds) {
  let previous = Promise.resolve();
  for (const codepoint of text) {
    await previous;
    userEvent.type(input, codepoint);

    previous = new Promise((resolve) => setTimeout(() => resolve(), delayInMilliseconds));

    act(() => {
      jest.advanceTimersByTime(delayInMilliseconds);
    });
  }
}
```
So instead of above, I could just call `userEvent.type(input, 'some text', { delay: 20, advance: jest.advanceTimersByTime });`

_Originally posted by @icedtoast in https://github.com/testing-library/user-event/issues/565#issuecomment-800694378_

**Comment by nickmccurdy** [comment]
Tip: You can start block quotes on GitHub by prefixing lines with `>` or pressing the `Insert a quote` button.

**Comment by ph-fritsche** [comment]
@all-contributors add @icedtoast ideas
