### ISSUE TITLE
maxlength attribute is ignored

### ISSUE THREAD

**Issue by afontcu** [testing-library/user-event#591]
(Source: [how to test input maxlength attribute](https://spectrum.chat/testing-library/help-react/how-to-test-input-maxlength-attribute~96beb2fe-9ba0-4246-9d81-df188ec74caa)).

---

- `dom-testing-library` version: 5.6.1
- `react` version: - 
- `node` version: 10.16
- `npm` version: 6.9

### Relevant code or config:

```js
import { getByRole, fireEvent } from '@testing-library/dom'

test('maxlength', () => {
  const div = document.createElement('div')
  div.innerHTML = `<input type="text" maxlength="10" />`

  const input = getByRole(div, 'textbox')

  fireEvent.input(input, { target: { value: '01234657890123456789' }})

  expect(input.maxLength).toBe(10)
  expect(input.value).toBe('0123456789') // <-- fails
})
```

### What happened:

Expected the test above to pass.

```bash
  ● maxlength

    expect(received).toBe(expected) // Object.is equality

    Expected: "0123456789"
    Received: "01234657890123456789"

      26 | 
      27 |   expect(input.maxLength).toBe(10)
    > 28 |   expect(input.value).toBe('0123456789') // <-- fails
         |                       ^
      29 | })
      30 | 

      at Object.toBe (src/Input.spec.js:16:23)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.332s, estimated 1s
```

This might be an expected behavior (not sure if an `Event` should honor `maxlength` attribute), but felt weird. I thought about this a bit and explore some ideas, but couldn't come up with a fix.

Tried with RTL and VTL and both failed too, obviously.

**Comment by nickmccurdy** [comment]
Reproduction: https://codesandbox.io/s/thirsty-mclaren-n7zk6?file=/src/index.test.js

**Comment by ph-fritsche** [comment]
Works as expected :smiley: 
https://codesandbox.io/s/old-dream-wfqku?file=/src/index.test.js

**Comment by nickmccurdy** [comment]
My mistake, thanks for clarifying.

**Comment by jefelewis** [comment]
> I could test it using the userEvent library:
> 
> ```
>   it('should not support more than 10000 chars', () => {
>     expect(input.maxLength).toBe(10000)
>     const text = 'loong text'
>     const longText = text.repeat(999)
> 
>     fireEvent.change(input, { target: { value: longText } })
>     userEvent.type(input, text + '!')
>     expect(input.value).toBe(text.repeat(1000))
>     expect(input.value.length).toBe(10000)
>   })
> ```

Can this be used with **React Native**?

**Comment by imronpuji** [comment]
> expect(input.maxLength).toBe(10000)
>     const text = 'loong text'
>     const longText = text.repeat(999)
> 
>     fireEvent.change(input, { target: { value: longText } })
>     userEvent.type(input, text + '!')
>     expect(input.value).toBe(text.repeat(1000))
>     expect(input.value.length).toBe(10000)

you must using async
