### ISSUE TITLE
onBlur and onFocus events do not fire when running against React 17.x

### ISSUE THREAD

**Issue by NateRadebaugh** [testing-library/user-event#592]
- `@testing-library/user-event` version:
```
"@testing-library/jest-dom": "^5.11.6",
"@testing-library/react": "^11.0.0",
"@testing-library/user-event": "^13.0.1",
```

- Testing Framework and version:
```
"jest": "^26.0.1",
```
  
- DOM Environment:
Default jest env using `tsdx test`

Relevant code or config

```javascript
          // Act
          expect(document.body).toHaveFocus();

          // Tab in
          userEvent.tab();
          expect(element).toHaveFocus();

          // Tab out
          userEvent.tab();

          // Should have triggered "onBlur"
          expect(handleBlur).toHaveBeenCalledTimes(1);
```

What you did: I updated from react 16 to react 17. `user-event` functions that used to trigger blur and focus events no longer trigger those events. I've got `onBlur` and `onFocus` listeners, so I'd expect them to still be triggered, for example `userEvent.tab()`.

What happened:

```
● DateTime › end-to-end › events › onBlur › should trigger onBlur with no value when tabbed out with no value

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0

      2809 |
      2810 |           // Should have triggered "onBlur"
    > 2811 |           expect(handleBlur).toHaveBeenCalledTimes(1);
           |                              ^
      2812 |           expect(element).not.toHaveFocus();
      2813 |           expect(handleBlur).toHaveBeenCalledWith(undefined);
      2814 |         });

      at src/DateTime.test.tsx:2811:30
      at step (node_modules/tslib/tslib.js:143:27)
      at Object.next (node_modules/tslib/tslib.js:124:57)
      at fulfilled (node_modules/tslib/tslib.js:114:62)
```

Reproduction repository: 
https://github.com/NateRadebaugh/react-datetime/pull/1789/commits/f058eb1ca2ffc45f556bf7b5cff00883ac878c16

Problem description: 

Suggested solution: Tab and other focus/blur-related user events should trigger the appropriate `focusin` and `focusout` bubbled events.

https://reactjs.org/blog/2020/08/10/react-v17-rc.html#aligning-with-browsers

**Comment by NateRadebaugh** [comment]
I can fix my tests by adding these type of changes around `.tab()` but that doesn't feel like the right fix:

```
userEvent.tab();
fireEvent.focus(element);
expect(element).toHaveFocus();
```

```
// Tab out
userEvent.tab();
fireEvent.focusOut(element);

// Should have triggered "onBlur"
expect(handleBlur).toHaveBeenCalledTimes(1);
```

**Comment by believeinalex** [comment]
I just tried to upgrade to React 17 and encountered the same issue.

**Comment by oriolcp** [comment]
I have the same issue with React 17.0.1, I was migrating some test from fireEvent to fireEvent but I realised focus is not triggered for userEvent.type, I also checked with React 16.14.0 and it works as expected

**Comment by oriolcp** [comment]
> I have the same issue with React 17.0.1, I was migrating some test from fireEvent to userEvent but I realised focus is not triggered for userEvent.type, I also checked with React 16.14.0 and it works as expected

after upgrading other npm packages the issue is solved.

**Comment by alcferreira** [comment]
Same here after upgrading to React 17

**Comment by NateRadebaugh** [comment]
@oriolcp  were you able to pinpoint what other packages you needed to update to resolve the issue? Perhaps the issue is in another dependency rather than the `user-event` lib?

**Comment by oriolcp** [comment]
> @oriolcp were you able to pinpoint what other packages you needed to update to resolve the issue? Perhaps the issue is in another dependency rather than the `user-event` lib?

I upgraded several packages, but now I've just tested upgrading only jest and the issue was also fixed 
- "jest": "^26.4.2"
+ "jest": "^26.6.3"

**Comment by ph-fritsche** [comment]
@oriolcp Thanks for clearing this up.
