### ISSUE TITLE
Click, keyboard & type TypeScript types are resolved as "any" because of wrong imports in typings

### ISSUE THREAD

**Issue by mkapal** [testing-library/user-event#594]
- `@testing-library/dom` version: 7.30.0
- `@testing-library/user-event` version: 13.0.1
- `typescript` version: 4.2.3

**Problem description:**
The file `typings/index.d.ts` contains type imports from `../src/` folder, which does not exist in the distributed package, so all those types are resolved to `any`.

Codesandbox: https://codesandbox.io/s/romantic-shadow-uio28

![image](https://user-images.githubusercontent.com/6420535/111598257-52ad4800-87cf-11eb-93a7-899772e17aca.png)

`typings/index.d.ts` in the corresponding `node_modules` folder:

![image](https://user-images.githubusercontent.com/6420535/111598700-c6e7eb80-87cf-11eb-831c-fb7673af86ac.png)

This concerns the following types:

- click, clickOptions
- keyboard, keyboardOptions, keyboardKey,
- type, typeOptions

**Comment by ph-fritsche** [comment]
Might be that removing the typings folder and adding declarations of the JS modules in `src` is easier than to get `rollup`(?) to resolve these. It's for sure better than to continue maintaining the seperated typings.

**Comment by mkapal** [comment]
Maybe it would be better to do it the same way as other `@testing-library` packages do it - to have all type declaration files in the `types` folder with no imports from `src`. You can see it in the [dom-testing-library](https://github.com/testing-library/dom-testing-library/tree/master/types) for example.

I can try fixing it if you agree.

**Comment by ph-fritsche** [comment]
If you fix the typings, I would of course merge it as a fix for now. :rocket: 

The seperate typings are necessary because the libraries have been written in JS. I converted a part of this one to TS and planning to convert the rest. So seperate definition files for already converted modules are duplicates that we have to update and review by hand.

The cleaner solution would be to convert `src/index.js` and add missing module definitions in `src`.
This means we could drop the `typings` folder.

Eventually the solution has to be to convert the remaining JS modules to discover the false type assumptions that might be hidden in the code.

**Comment by ph-fritsche** [comment]
@mkapal Thanks a lot for the reports. Please check out the new version. :smiley:

**Comment by ph-fritsche** [comment]
@all-contributors add @mkapal bug

**Comment by mkapal** [comment]
> @mkapal Thanks a lot for the reports. Please check out the new version. 😃

Unfortunately, it is still not correct. Now the distributed `.d.ts` files contain `any` types, and also, there are `.d.js` files generated, which I'm guessing shouldn't be there.

For example, the bundled `click.d.ts` file looks like this:

```typescript
export function click(element: any, init: any, { skipHover, clickCount }?: {
    skipHover?: boolean | undefined;
    clickCount?: number | undefined;
}): void;
export function dblClick(element: any, init: any): void;
```

**Comment by ph-fritsche** [comment]
See https://github.com/testing-library/user-event/pull/596#issuecomment-802792000
`.d.js` won't hurt

Rollup removed the references to `lib.dom.d.ts`. I'm on it.

**Comment by ph-fritsche** [comment]
@mkapal Could you have a look at #599 ?

**Comment by mkapal** [comment]
> @mkapal Could you have a look at #599 ?

It works great now, thanks for the fix!
