### ISSUE TITLE
Typescript error in click function when upgrading to v13.0.3 

### ISSUE THREAD

**Issue by sstauross** [testing-library/user-event#598]
- `@testing-library/user-event` version: 13.0.3

- Testing Framework and version: jest@26.6.0
  
- DOM Environment:
-  "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.5",
  

What you did: Upgrading to v13.0.3 the types exported seem to have the `init` property of the click function as mandatory while in `click.d.ts` [in the repo](https://github.com/testing-library/user-event/blob/16314c6f10a4e0cdd25024e25ebb588c7abe8935/src/click.d.ts) it seems to be optional.

What happened: Typescript error. 

![image](https://user-images.githubusercontent.com/1146626/111794195-a5215e00-88ce-11eb-8f9a-669ff10d7340.png)
![image](https://user-images.githubusercontent.com/1146626/111794593-0fd29980-88cf-11eb-8ae1-03c2376fedfb.png)

**Comment by ph-fritsche** [comment]
@sstauross Thanks a lot for the report.

Could you have a look at #599 ?

**Comment by ph-fritsche** [comment]
@all-contributers add @sstauross bug

**Comment by ph-fritsche** [comment]
@all-contributors add @sstauross bug
