### ISSUE TITLE
Wrong type definitions for hover/unhover

### ISSUE THREAD

**Issue by rosczja** [testing-library/user-event#608]
Hi,

I am using @testing-library/user-event 13.0.6 and it seems that the Typescript types are wrong, because suddenly for the hover and unhover functions the `init` parameter is reported as mandatory.

Is this intended?

**Comment by strangedev** [comment]
I am also experiencing this issue. Also, it seems the type is now `any` instead of `MouseEventInit`.

**Comment by ph-fritsche** [comment]
Thanks a lot for the report.

That module escaped the hurried converting in #599 :disappointed: 
Fix will be released in a few minutes.
