### ISSUE TITLE
v13.0.11 has apparently broken imports

### ISSUE THREAD

**Issue by ljosberinn** [testing-library/user-event#620]
- `@testing-library/user-event` version: 13.0.11

Relevant code or config

https://github.com/ljosberinn/personal-react-boilerplate/pull/905/checks?check_run_id=2187475320

What you did: just a dependabot auto-update

What happened:
Multiple tests fail, all with the same error:

```sh
FAIL src/client/__tests__/useAuth.test.tsx
  ● Test suite failed to run

    Cannot find module 'utils/misc/isElementType' from 'node_modules/@testing-library/user-event/dist/utils/edit/calculateNewValue.js'

    Require stack:
      node_modules/@testing-library/user-event/dist/utils/edit/calculateNewValue.js
      node_modules/@testing-library/user-event/dist/utils/index.js
      node_modules/@testing-library/user-event/dist/click.js
      node_modules/@testing-library/user-event/dist/index.js
      testUtils/index.tsx
      src/client/__tests__/useAuth.test.tsx

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/@testing-library/user-event/dist/utils/edit/calculateNewValue.js:8:22)
```

sorry for not providing more info, can't debug at this time

**Comment by jacknewberry** [comment]
I have been struggling with this too for the last hour or so. Exact same error output.

I am using yarn 2.4.0 with workspaces. @testing-library/user-event is a dev dependency of a non-root workspace.

Reverted to 13.0.11 in the mean time.

**Comment by ph-fritsche** [comment]
@ljosberinn  Thanks for the report :heart: 

https://github.com/kentcdodds/kcd-scripts/issues/197 struck again :facepalm: 
Fix will be ready in a few minutes
