### ISSUE TITLE
13.0.13 no longer triggering onChange event handler when calling userEvent.type

### ISSUE THREAD

**Issue by robin-ambachtsheer** [testing-library/user-event#624]
- `@testing-library/user-event` version: 13.0.13
- Testing Framework and version: Jest
- DOM Environment: jsdom, jest 26.6.3

Relevant code or config

```javascript
test('input should trigger onchange', () => {
  const onChangeMock = jest.fn();
  const { getByTestId } = render(<input data-testid="input" onChange={onChangeMock} />);
  const input = getByTestId('input');

  userEvent.type(input, 'hello');

  expect(input).toHaveValue('hello');
  expect(onChangeMock).toHaveBeenCalled();
});
```

Expected output (version 13.0.12)

```
  ✓ input should trigger onchange (56 ms)
```

Instead getting (version 13.0.13)

```bash
  ✕ input should trigger onchange (54 ms)

  ● input should trigger onchange

    expect(jest.fn()).toHaveBeenCalled()

    Expected number of calls: >= 1
    Received number of calls:    0

      16 |
      17 |   expect(input).toHaveValue('hello');
    > 18 |   expect(onChangeMock).toHaveBeenCalled();
         |                        ^
      19 | });
      20 |
      21 | // test('renders a custom input', () => {

      at Object.<anonymous> (src/hooks/useFormField.test.js:18:24)
```

I'm assuming this has to do with changes that were made to this file https://github.com/testing-library/user-event/commit/5c40248c0a2bad32ece26319458e88f44eed6e64?branch=5c40248c0a2bad32ece26319458e88f44eed6e64&diff=split#diff-a95e781d26472f11b0c7fb9827c835cc5ffac421a1867c09be9aaa6212e027c4

It look likes the value is still being set on the element, but the onChange event is not being triggered.

**Comment by ph-fritsche** [comment]
Thanks a lot for the report.

This one is tricky.
The input event is triggered and React creates a `SyntheticEvent` and also passes it to the `onInput` handler. But it does not dispatch that `SyntheticEvent` for `onChange` anymore.

https://codesandbox.io/s/quirky-wilbur-z0fey?file=/src/App.test.js

We need to investigate how React determines that the `input` is also worth a `change`.

**Comment by ph-fritsche** [comment]
React tracks the value before and on the input event per this tracker:
https://github.com/facebook/react/blob/148f8e497c7d37a3c7ab99f01dec2692427272b1/packages/react-dom/src/client/inputValueTracking.js#L51-L104

If the value changed, it also dispatches an event for `onChange`.
We might be able to work around by disconnecting React from the `value` property for our change and reconnecting it afterwards.

**Comment by ph-fritsche** [comment]
@all-contributors add @robin-ambachtsheer bug

**Comment by NextNebula** [comment]
This does not seem fixed for me. After upgrading from v12 to v13 (13.0.15) one of my tests fails because typing does not trigger validation anymore.

**Comment by ph-fritsche** [comment]
@NextNebula Could you provide more context? Maybe a reproduction at codesandbox?
There have been a lot of changes and tests might rely on undocumented/unintended behavior of the previous implementation - that's why it was flagged as a major release.

The issue described above is resolved in `v13.0.15` as you can see [here](https://github.com/testing-library/user-event/blob/51bffe9391ccf5e86083234557552adf485ef865/src/__tests__/react/type.tsx#L5-L15) and [here](https://codesandbox.io/s/quirky-wilbur-z0fey?file=/src/App.test.js)

Should there be more bugs, please help improving this software by providing enough information to reproduce the behavior.

**Comment by NextNebula** [comment]
I just saw this reported bug. I think that is what is wrong for me. Thx for the info. 👍 
https://github.com/testing-library/user-event/issues/606

**Comment by EstopaceMA** [comment]
onChange didn't trigger on version 14.2.0
