### ISSUE TITLE
add pointerDown, pointerMove and pointerUp events for API

### ISSUE THREAD

**Issue by lifeiscontent** [testing-library/user-event#638]
I think it would be beneficial to have pointerDown, pointerMove, and pointerUp user events so you can encapsulate touch events, mouse events, pointer events all under one API.

The reason why I think something like this should exist is it would allow for testing complex UI components like a slider input.

the basic implementation I think could work from a high level is the following:

```js
const input = document.getElementById('input');
// you could use a percent to represent the bounds of the element
// or use a specific number to represent a pixel value
userEvent.pointerDown(input, {x: '50%', y: '50%'}); // starting point of where you "clicked"
userEvent.pointerMove(input, {x: '75%', y: '50%', duration: '1s'}); // where you want to move to over a period of time
userEvent.pointerUp(input); // remove your finger from the screen/mouse/etc
```

@kentcdodds what do you think?

**Comment by kentcdodds** [comment]
What difference would this be from just using fireEvent directly?

**Comment by lifeiscontent** [comment]
It would provide a more ergonomic API for emulating down/move/up events just like all the methods in this API provide.

**Comment by ph-fritsche** [comment]
@lifeiscontent Could you describe the differences between your idea and the behavior of `userEvent.hover()` and `userEvent.click()`?

I don't think that adding more APIs with separate implementations is a good idea.
But the pointer related APIs might benefit from an abstract underlying implementation.
A `pointer` API could provide a solid stateful handling of pointer events that is then used by the convenience APIs like `click`, `dblClick` etc.
Like `keyboard` provides the implementation that is used for `type`.

**Comment by kentcdodds** [comment]
Keep in mind that `user-event` is intended to simulate common things users do. Based on your example, it looks like you're trying to simulate a user pressing down on an element, moving their finger somewhere on that element and then pulling their finger up. I can see how this might be useful in some very niche situations, but most people wouldn't have a use for this. Everything we add to `user-event` adds complexity and therefore every user of `user-event` pays the cost for what's added. We want to make sure the cost everyone pays is worth the benefit to most people. This is just good OSS stewardship.

I think what's being suggested here is outside the scope of `user-event`. You could absolutely build these utilities yourself and even publish them as a package on npm. But I don't think we should add this to `user-event`.

**Comment by lifeiscontent** [comment]
@ph-fritsche Yep, totally.

So if you're testing a range input.

![image](https://user-images.githubusercontent.com/180963/113440928-35b56f00-93a2-11eb-8276-309423214332.png)

a click event or a hover would not work, because a click consists of a mouse up / mouse down.

You need to have all three of these events down/move/up in order to correctly imitate a finger/mouse pointer.

down (your finger is on the handle of the range input)
move (you're now dragging your mouse in the place you want to move the range to)
up (you've now selected the value that you want from the input)

there are a lot of other events that happen with this typical UX that is not covered by just "pointer*" events.

but maybe I'm wrong, do you know how you would test this kind of UI using the current API? @kentcdodds @ph-fritsche

**Comment by kentcdodds** [comment]
Personally I'd just use cypress. JSDOM doesn't support layout so you'd have to mock that out of you wanted to do it in that environment...

**Comment by lifeiscontent** [comment]
Ah that's a good point. Thanks @kentcdodds alright, I'll close the issue. Thanks to both of you for your responses!

**Comment by ph-fritsche** [comment]
@all-contributors add @lifeiscontent ideas

**Comment by imnasnainaec** [comment]
What about just adding `pointerDown` and `pointerUp` events? It's not uncommon to have click-and-hold actions (e.g., an audio recording button; or to temporary highlight/select an item).
