### ISSUE TITLE
Tests performance dropped after upgrading to v. 13

### ISSUE THREAD

**Issue by LukaszNowakPL** [testing-library/user-event#650]
- `@testing-library/user-event` version: 13.1.2

- Testing Framework and version: Jest
  
- DOM Environment: jest-environment-jsdom-sixteen
  

Relevant code or config

Repo: https://github.com/LukaszNowakPL/user-event-performance/

What you did: Upgraded `userEvent` library from version `12.1.8` to `13.1.2`.

What happened: Tests performance dropped significantly. The execution time of entire test suite lengthened by up to 40%. Also some longer test cases (testing of entire form-page) failed because of timeouts.

Reproduction repository: https://github.com/LukaszNowakPL/user-event-performance/

Problem description: The example repo contains same test scenarios. The only difference is version of `UserEvent` provided. Test cases that use `13.1.2` version of `UserEvents` normally takes about 20% more time to execute. It applies for using raw html forms as well as those wrapped with library like Material-ui. Test suites for our company projects lengthened the execution time by 30-40%.

**Comment by ph-fritsche** [comment]
We've added new features and fixed a bunch of bugs. This also means we execute more checks on every execution.
So a drop in performance is to be expected. Our primary target is accuracy not performance.

That said - if you identify parts of the code that could be optimized while yielding the same result, PRs are welcome.
