### ISSUE TITLE
Focusing wrong element when .click()

### ISSUE THREAD

**Issue by luckened** [testing-library/user-event#652]
- `@testing-library/user-event` version:
`^13.0.15`

- Testing Framework and version:
`"jest": "^26.6.3"`

  
- DOM Environment:
`"@testing-library/jest-dom": "^5.11.9"`
  

Relevant code or config

```javascript
import { fireEvent, render } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { Modal } from ".";

describe("Modal", () => {
    it("should trap the focus inside it", () => {
        const { getByText, getByRole } = render(<Modal />);
        const firstFocusedButton = getByRole("button", { name: /some label/i });

        //this works
        fireEvent.click(getByRole("button", { name: /open modal/i }));
        userEvent.tab();
        expect(firstFocusedButton).toHaveFocus();
        
        //this doesnt
        userEvent.click(getByRole("button", { name: /open modal/i }));
        userEvent.tab();
        expect(firstFocusedButton).toHaveFocus();
    });
}
```

What you did:
Im using react.portal (https://pt-br.reactjs.org/docs/portals.html), maybe it has something to do with it

Clicking in "open modal" button should append modal as a sibling to `<div id="root" />` (like in CRA).

It works perfectly fine with `fireEvent.click()`, but `userEvent.click()` set the focus to the document body, as shown below

What happened:
The focus is set to the `<body>`, not the component being rendered

```
  ● Modal › should trap the focus tab navigation correctly

    expect(element).toHaveFocus()

    Expected element with focus:
      <button aria-label="Fechar modal" class="modalCloseButton" tabindex="0" />
    Received element with focus:
      <body><div><div id="root" /><div id="modal"><div class="modalOverlay"><div class="modal"><div class="modalCloseButtonContainer"><button aria-label="Fechar modal" class="modalCloseButton" tabindex="0" /></div><h1 class="modalTitle">Exemplo de modal</h1><div><p>Texto fofinho</p>Bom dia<input type="checkbox" /><p>Boa tarde</p><button>Tab aqui e volta pra cima =)</button></div></div></div></div><button>Abrir Modal</button></div></body>

      33 |
      34 |         userEvent.tab();
    > 35 |         expect(closeButton).toHaveFocus();
         |                             ^
      36 |
      37 |         /* userEvent.tab();
      38 |
```

**Comment by ph-fritsche** [comment]
Thanks for the report.
Could you add a reproduction at codesandbox ?

**Comment by luckened** [comment]
@ph-fritsche thanks for the answer!

here: https://codesandbox.io/s/upbeat-panini-4qd4k?file=/src/modal.spec.js:241-478, to reproduce the error just comment the "this works" block and uncomment the "this doesnt" block on the `modal.spec.js`

i guess the line 9 on `modal.js`: `refModal.current.focus();` is not running at the expected time (first render)..

**Comment by ph-fritsche** [comment]
Both used `userEvent` function work as expected.

When you use `fireEvent.click` the focus is not moved. So it is still on the `document.body` when you use `userEvent.tab()`. Therefore the focus moves to the first focusable element.

When you use `userEvent.click` the focus is moved to the clicked element. So it is on the `open modal` button. Therefore the focus moves to the first focusable element after this button or the `document.body` if it's the last focusable element in the document.

Now here what tricks you into thinking `fireEvent` works and `userEvent` doesn't:

Your DOM structure in the browser:
```html
<div id="root">
  <div id="root"></div>
  <button>open modal</button>
</div>
<div id="modal"><!-- ... --></div>
```

Your DOM structure in test environment:
```html
<div id="root"></div>
<div id="modal"><!-- ... --></div>
<button>open modal</button>
```

Your Portal implementation is flawed.
