### ISSUE TITLE
How should I test a Radio with onChange is called when Space is pressed?

### ISSUE THREAD

**Issue by bozdoz** [testing-library/user-event#653]
By default, an onChange event will fire when a radio button is focused and the user presses [Enter] or [Space]. Example: https://codepen.io/bozdoz/pen/zYNLGWe?editors=1001

Here's what I expect should work with the new keyboard method:

```javascript
it('activates radio with spacebar', () => {
    const onChange = jest.fn();

    render(<input type="radio" onChange={onChange} />);

    userEvent.tab();

    userEvent.keyboard('[Space]');

    expect(onChange).toHaveBeenCalled();
});
```

I expect that test should pass, but it is not passing (because onChange has not been called).  Any idea where I'm going wrong here, or suggestions?

**Comment by bozdoz** [comment]
Referenced in #654

**Comment by ph-fritsche** [comment]
`checkbox` and `radio` are missing in [CLICKABLE_INPUT_TYPES](https://github.com/testing-library/user-event/blob/d22ea5e0f5b042d743380efe089644ad7f65d29f/src/utils/click/isClickableInput.ts#L3)

**Comment by bozdoz** [comment]
> `checkbox` and `radio` are missing in [CLICKABLE_INPUT_TYPES](https://github.com/testing-library/user-event/blob/d22ea5e0f5b042d743380efe089644ad7f65d29f/src/utils/click/isClickableInput.ts#L3)

@ph-fritsche #654 passed! Thanks! I'll see if that PR is good to go
