### ISSUE TITLE
userEvent.type() doesn't work

### ISSUE THREAD

**Issue by glowlh** [testing-library/user-event#661]
- `@testing-library/user-event` version: 13.1.5

Code from docs

```javascript
import React from 'react'
import {render, screen} from '@testing-library/react'
import userEvent from '@testing-library/user-event'

test('type', () => {
    render(<textarea />)

    userEvent.type(screen.getByRole('textbox'), 'Hello, World!')
    expect(screen.getByRole('textbox')).toHaveValue('Hello, World!')
})
```

What you did: ran this code

What happened: got an error, because it received 'H' instead 'Hello, World!'

**Comment by ph-fritsche** [comment]
Works fine in codesandbox.
https://codesandbox.io/s/trusting-drake-b73hq?file=/src/661.test.js

**Comment by glowlh** [comment]
This problem was due to jest 25.x.x version. For jest 26.x.x version is ok

**Comment by widoz** [comment]
Actually with jest 27.x.x it does not work either. It's simply does not change the value.

I've tried the example code found in https://testing-library.com/docs/ecosystem-user-event/#typeelement-text-options

```javascript
import React from 'react'
import {render, screen} from '@testing-library/react'
import userEvent from '@testing-library/user-event'

test('delete characters within the selectedRange', () => {
  render(
    <div>
      <label htmlFor="my-input">Example:</label>
      <input id="my-input" type="text" value="This is a bad example" />
    </div>,
  )
  const input = screen.getByLabelText(/example/i)
  input.setSelectionRange(10, 13)
  userEvent.type(input, '{backspace}good')

  expect(input).toHaveValue('This is a good example')
})
```

Output Is

```
Error: expect(element).toHaveValue(This is a good example)

Expected the element to have value:
  This is a good example
Received:
  This is a bad example
```

My packages are

- "jest": "^27.0.6",
- "react": "^17.0.2",
- "@testing-library/react": "^12.0.0",
- "@testing-library/user-event": "13.2.1"

**Comment by ph-fritsche** [comment]
@widoz I filed a new issue for the docs. The code example is invalid as it renders a read-only field.
Use the `defaultValue` prop if you don't supply an `onChange` handler.

**Comment by netcoding87** [comment]
I am having the same issue currently. Here is an Codesandbox for reproduction: https://codesandbox.io/s/suspicious-water-gn4371?file=/src/MyInput.test.tsx

It only changes the first letter... 

```jsx
import React from "react";
import "@testing-library/jest-dom/extend-expect";

import MyInput from "./MyInput";

describe("<MyInput />", () => {
  it("should change value", async () => {
    render(<MyInput />);

    await userEvent.type(screen.getByPlaceholderText(/^Customer$/), "John", {
      delay: 1
    });
    expect(screen.getByPlaceholderText(/^Customer$/)).toHaveValue("John");
  });
});
```

Expected outcome: Input to have value "John", but got only "J"

**Comment by ph-fritsche** [comment]
@netcoding87 Fixed your event handler:
https://codesandbox.io/s/recursing-haze-48u6to?file=/src/MyInput.tsx

**Comment by netcoding87** [comment]
Thanks. Just try to think why this small change makes such a difference 🧐 It must be sth with how React is calling the callback passed into the set function of the state and how the values are evaluated.
