### ISSUE TITLE
userEvent.upload `changeInit` option does not update the change event

### ISSUE THREAD

**Issue by sydneyjodon-wk** [testing-library/user-event#667]
Hello 👋   I’m new to `testing-library`, but am really enjoying it so far! I’m currently running into an issue when using the `changeInit` option on `userEvent.upload`.

- `@testing-library/user-event` version: 13.1.5
- `@testing-library/jest-dom` version: 5.11.9
- `@testing-library/react` version: 11.2.5

Relevant code or config

```javascript
import "@testing-library/jest-dom/extend-expect";
import React from "react";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";

test("upload file", () => {
  const file = new File([], "hello.png");
  var clickEvents = [];
  var changeEvents = [];

  render(
    <div>
      <label htmlFor="file-uploader">Upload file:</label>
      <input
        id="file-uploader"
        type="file"
        onClick={(e) => clickEvents.push(e)}
        onChange={(e) => changeEvents.push(e)}
      />
    </div>
  );
  const input = screen.getByLabelText(/upload file/i);
  userEvent.upload(input, file, {
    clickInit: { shiftKey: true },
    changeInit: { cancelable: true }
  });

  expect(input.files[0].name).toStrictEqual("hello.png");
  expect(clickEvents[0].shiftKey).toBeTruthy();
  expect(changeEvents[0].cancelable).toBeTruthy(); // this check fails
});

```

What I did:

I wrote a test using the `changeInit` option on `userEvent.upload` and expected that the change event would have the updated `cancelable` value (similar to `clickInit` with `shiftKey`).

What happened:

The change event was not updated like I expected it to be and the test failed.

Test results:
```
expect(received).toBeTruthy()

Received: false

  48 |   expect(input.files[0].name).toStrictEqual("hello.png");
  49 |   expect(clickEvents[0].shiftKey).toBeTruthy();
> 50 |   expect(changeEvents[0].cancelable).toBeTruthy();
  51 | });

```
Reproduction repository:

[Sandbox link](https://codesandbox.io/s/user-event-upload-changeinit-example-zfbwx?file=/src/__tests__/index.js)

Suggested solution:
 
I think the issue might have to do with [this line](https://github.com/testing-library/user-event/blob/master/src/upload.ts#L83). Maybe it could be something like `...init?.changeInit` instead?

**Comment by ph-fritsche** [comment]
Thanks a lot for the report :heart: 
You're 100% correct. Should deconstructure `init.changeInit`.

**Comment by ph-fritsche** [comment]
@all-contributors add @sydneyjodon-wk bug

**Comment by sydneyjodon-wk** [comment]
@ph-fritsche Thank you for fixing that so quickly!
