### ISSUE TITLE
userEvent.click on component with React Hook causes Jest to hang indefinitely

### ISSUE THREAD

**Issue by prescottbreeden** [testing-library/user-event#678]
- `@testing-library/user-event` version: 12.1.10

- Testing Framework and version: Jest: (CRA - 26.6.3)
  
- DOM Environment: CRA(jsdom -  26.6.2)
  

Relevant code or config:
see repo for context -- code that causes the bug is the following:
```javascript
const button = screen.getByRole('button', { name: /submit/i }); 
userEvent.click(button);  
```

What you did:
calling userEvent.click on a button that triggers a react hook

What happened:
Jest hangs indefinitely without timeout, no error messages

Reproduction repository:  https://github.com/prescottbreeden/hanging-test-repro

Problem description:
I have a validation library that uses a react hook, and interestingly, I can use `fireEvent` and any other `userEvent` methods on the button that triggers the hook to run without a problem, but when I used `userEvent.click` specifically, Jest hangs infinitely.

Suggested solution:
unsure

**Comment by ph-fritsche** [comment]
Your reproduction works fine in codesandbox:
https://codesandbox.io/s/modest-sunset-gh0of?file=/src/App.tsx

**Comment by prescottbreeden** [comment]
Myself and others have cloned this repo and had the same problem. I don't think code sandbox is reproducing the same conditions to produce the bug that we are encountering if it worked for you.

**Comment by ph-fritsche** [comment]
I just cloned your reproduction earlier. Just saw now, that you commented out the `click`.
When uncommenting it, codesandbox hangs too.

The loop is at `validateAll()` which is created per `createValidateAll` from `@de-formed/base`.
I suggest you inspect this part of the code and/or file an issue at `@de-formed/base`. This has nothing to do with `userEvent`

**Comment by prescottbreeden** [comment]
Thank you for taking the time to write all this out. However -- if indeed it is an infinite state update (which I'm not sure it is, this code is being used in a very large system currently), why does every other userEvent method work except click?

**Comment by ph-fritsche** [comment]
Trigger the infinite loop per `fireEvent.click`:
https://codesandbox.io/s/eloquent-hypatia-km99i?file=/src/components/CreateAccount.test.tsx

**Comment by prescottbreeden** [comment]
It seems with the scaled down repo those indeed also hang, and I see the loop now, my thanks for your time.
