### ISSUE TITLE
userEvent.type does not dispatch change events on input with @testing-library/dom

### ISSUE THREAD

**Issue by tf** [testing-library/user-event#682]
- `@testing-library/user-event` version: 13.1.9
- Testing Framework and version:  `jest` 26.6.3, `@testing-library/dom` 7.31.0
- DOM Environment: `jsdom` 16.5.3

I have some code that listens for `change` events on an `input`. How do I make sure the event is triggered when using `userEvent.type`? I understand that typing alone does not trigger the event - only blurring the field. But in the browser, clicking another element or pressing tab causes this to happen. I am unable to reproduce this interaction with `userEvents`.

```javascript
test("fires change event after typing", () => {
  const listener = jest.fn();

  document.body.innerHTML = `
    <label for="name">Name</label>
    <input type="text" id="name" />
    <button role="button">Save</button>
  `;
  // This would normally live somewhere in application code
  document.querySelector("input").addEventListener("change", listener);

  userEvent.type(screen.getByLabelText("Name"), "Max");
  userEvent.tab();
  userEvent.click(screen.getByRole("button", { name: "Save" }));

  expect(screen.getByLabelText("Name").value).toEqual("Max");
  expect(listener).toHaveBeenCalled(); // fails
});
```

Reproduction sanbox: https://codesandbox.io/s/cocky-swartz-5nnn6?file=/src/type.test.js

**Comment by ph-fritsche** [comment]
Thanks for the report. :heart: 

I think we might be able to fix this by adding an event listener on the `document` for capture phase of BlurEvent in https://github.com/testing-library/user-event/blob/master/src/keyboard/shared/fireInputEvent.ts .

**Comment by qister** [comment]
@tf , to dispatch change event on input you can add some delay.

`await userEvent.type(screen.getByLabelText("Name"), "Max", { delay: 500 });`

**Comment by tf** [comment]
@qister Thanks for the response! Tried to make it work, but failed: https://codesandbox.io/s/happy-currying-jg2oc?file=/src/type.test.js

**Comment by ph-fritsche** [comment]
@all-contributors add @tf bug
