### ISSUE TITLE
userEvent.type() doesn't work with decimal numbers on PrimeReact/InputNumber, was working with v12.8.3

### ISSUE THREAD

**Issue by ankitprahladsoni** [testing-library/user-event#684]
- `@testing-library/user-event` version: 13.1.9

- Testing Framework and version:
```
"@testing-library/react": "11.2.7",
    "@testing-library/user-event": "13.1.9",
    "primereact": "6.3.2",
    "prop-types": "15.7.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-scripts": "4.0.3"
```
  
- DOM Environment: jsdom

Node: 16

Relevant code or config

```javascript
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { InputNumber } from "primereact/inputnumber";
import { useState } from "react";

function DecimalInput() {
  const [num, setNum] = useState(undefined);
  return (
    <div>
      <label htmlFor="inputId">DecimalInput</label>
      <InputNumber
        inputId="inputId"
        value={num}
        onValueChange={(e) => setNum(e.value)}
        locale="en-IN"
        mode="decimal"
        minFractionDigits={1}
        maxFractionDigits={3}
      />
    </div>
  );
}

test("sets the value to InputNumber", () => {
  render(<DecimalInput />);
  const upperInput = screen.getByLabelText(/DecimalInput/i);
  const num = "18.27";
  userEvent.type(upperInput, num);
  expect(upperInput.value).toEqual(num);
});

```

What you did:
Created a component that accepts a decimal number using `primereact/inputnumber`
userEvent.type was given the input as `18.27`
What happened:
```
expect(received).toEqual(expected) // deep equality

Expected: "18.27"
Received: "1827"

  26 |   const upperInput = screen.getByLabelText(/DecimalInput/i);
  27 |   const num = "18.270";
  28 |   userEvent.type(upperInput, num);
> 29 |   expect(upperInput.value).toEqual(num);
  30 | });
```

This test case was working fine with userEvent v12.8.3. But when I decided to upgrade to v13, the test failed.

Codesandbox: https://codesandbox.io/s/gallant-ishizaka-hv4n7?file=/src/aaa.test.js

**Comment by ph-fritsche** [comment]
It looks like `primereact` relies on the deprecated [`KeyboardEvent.which`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which) and/or [`KeyboardEvent.keyCode`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode).
https://github.com/primefaces/primereact/blob/052193601c52d14e0025041897bf1f318ca82d1d/src/components/inputnumber/InputNumber.js#L506-L508

We've added a few `keyCode` values for special keys for backwards compatibility in our default [`keyboardMap`](https://github.com/testing-library/user-event/blob/master/src/keyboard/keyMap.ts).
You can file a PR adding missing ones for an US-keyboard or if you use the `keyboard` API you can plugin your own `keyboardMap`.
```js
element.focus();
userEvent.keyboard('18.27', {keyboardMap: myKeyboardMap});
```

Either way I suggest to file an issue with `primereact` for them to update their code to use [`KeyboardEvent.key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key).
