### ISSUE TITLE
Typing `{arrowleft}` doesn't change the selection

### ISSUE THREAD

**Issue by Ayc0** [testing-library/user-event#690]
- `@testing-library/user-event` version: 13.x.x -> 13.1.9
- Testing Framework and version: jest 27 (same behavior in jest 26)
- DOM Environment: jsdom provided by jest

```javascript
expect(textArea.selectionStart).toBe(5);
fireEvent.type(textArea, "{arrowleft}");
expect(textArea.selectionStart).toBe(4); // ❌  doesn't pass
```

What happened:

![image](https://user-images.githubusercontent.com/22725671/123263489-4dac1300-d4f9-11eb-9aad-4a1df04ca716.png)

Reproduction repository:

There is a full reproduction here: https://codesandbox.io/s/testing-libraryuser-event-bug-with-arrows-62f7g

Problem description: the selection should be shifted by 1 to the left (to 4) instead of staying at its initial position (at 5)

Suggested solution: No idea

**Comment by Ayc0** [comment]
I also have a similar bug with `initialSelectionStart`, I think it's related to the same issue, but I'm not sure (maybe I should open another issue for that):

![image](https://user-images.githubusercontent.com/22725671/123263804-a8de0580-d4f9-11eb-96d4-3fce63c12f3c.png)

**Comment by ph-fritsche** [comment]
There are two things:
1. `element.focus()` does nothing if the element is not inserted in the DOM. Insert your element somewhere in the `body`.
2. Textarea is not supported yet. It looks like this will change with #686 :smile:

**Comment by Ayc0** [comment]
>element.focus() does nothing if the element is not inserted in the DOM. Insert your element somewhere in the body.

I had the same even when adding the elements to the body, but I updated the sandbox to fix that in the example:
![image](https://user-images.githubusercontent.com/22725671/125057091-29c80000-e0a9-11eb-9064-2176bdeb5888.png)

**Comment by Ayc0** [comment]
> Textarea is not supported yet

I didn't know!
Thanks for linking the related PR addressing the issue 🙇
