### ISSUE TITLE
Upgrading Breaks Tests

### ISSUE THREAD

**Issue by neilchaudhuri** [testing-library/user-event#691]
- `@testing-library/user-event` version: ^13.1.9

- Testing Framework and version:

```
"@testing-library/dom": "^7.31.2",
"@testing-library/react": "^11.2.7",
"@testing-library/user-event": "^13.1.9",
```

- DOM Environment:

Running in Webstorm IDE with Node and NPM versions that qualify

Relevant code or config

```
userEvent.type(autocomplete, "al{arrowdown}{arrowdown}{enter}")

expect((autocomplete as HTMLInputElement).value).toBe("California")
expect(onChange).toHaveBeenCalledWith("CA")
```

What you did:

Upgraded from this:

```
"@testing-library/dom": "^7.29.4",
"@testing-library/react": "^11.2.5",
"@testing-library/user-event": "^12.7.0",
```

to this

```
"@testing-library/dom": "^7.31.2",
"@testing-library/react": "^11.2.7",
"@testing-library/user-event": "^13.1.9",
```
What happened:

```
userEvent.type(autocomplete, "al{arrowdown}{arrowdown}{enter}")

expect((autocomplete as HTMLInputElement).value).toBe("California")
```

which used to work now breaks. 

```
● Basic AutocompleteSelect function › AutocompleteSelect basic selection works

    expect(received).toBe(expected) // Object.is equality

    Expected: "California"
    Received: "Alabama"
```

Suggested solution:

It is quite possible this isn't a bug. I tried a different API instead:

```
userEvent.type(autocomplete, "al")
userEvent.keyboard("{arrowdown}{arrowdown}{enter}")
```

Any help on how v13 accomplishes `userEvent.type(autocomplete, "al{arrowdown}{arrowdown}{enter}")` is appreciated.

I should note that I am testing an autocomplete written with Downshift that has Alabama, Arkansas, California as values, so the scenario is typing "al" to filter the list down to Alabama, California, arrow down twice to get to California, and enter to select it

<img width="259" alt="Screen Shot 2021-06-28 at 4 46 43 PM" src="https://user-images.githubusercontent.com/1239158/123701921-78b3a100-d830-11eb-9b21-72a402fcdc62.png">

**Comment by neilchaudhuri** [comment]
FWIW I tried key navigation with `fireEvent` and also failed:

```
userEvent.type(autocomplete, "al")
fireEvent.keyDown(autocomplete, { key: "ArrowDown", code: "ArrowDown" })
fireEvent.keyDown(autocomplete, { key: "ArrowDown", code: "ArrowDown" })
fireEvent.keyDown(autocomplete, { key: "Enter", code: "Enter" })
```

**Comment by ph-fritsche** [comment]
It looks as if the bug is in your component, but there is not enough information to reproduce.
You could try creating a reproduction example at [codesandbox](https://codesandbox.io).

**Comment by neilchaudhuri** [comment]
It's certainly possible, although it is weird that identical tests and components worked before the upgrade and that manual interaction works as expected. 

Anyway, I will see about a codesandbox.
