### ISSUE TITLE
Support PageUp/PageDown special keys

### ISSUE THREAD

**Issue by mammadataei** [testing-library/user-event#694]
Hi. I couldn't find out how I can trigger `pageUp`/`pageDown` keys using the `keyboard` function and these are not in `specialChars` too.

**Comment by ph-fritsche** [comment]
`specialChars` is legacy.
I recommend referencing non-printable keys should [per `key` or `code`](https://github.com/testing-library/user-event#keyboardtext-options).

A PR adding missing keys to the default key map would be welcomed:
https://github.com/testing-library/user-event/blob/402944134d10a33a9837be25ca8b1991f510fc6d/src/keyboard/keyMap.ts#L73-L78

Implementations of default browser behavior for control keys go here:
https://github.com/testing-library/user-event/blob/master/src/keyboard/plugins/control.ts

**Comment by JohannesFischer** [comment]
Happy to have a stab at this. I assume this is to be used in input and textarea elements, is that correct?

**Comment by JohannesFischer** [comment]
Had some time and went ahead adding support for the two keys. Please have a look if you have a minute and let me know if that is what you where going for for.
