### ISSUE TITLE
userEvent.type() writes to the same input

### ISSUE THREAD

**Issue by AlonBru** [testing-library/user-event#697]
-  "@testing-library/jest-dom": "^5.14.1",
-  "@testing-library/react": "^12.0.0",
-  "@testing-library/user-event": "^13.1.9",
-  "formik": "^2.2.5",

- Testing Framework and version:  "jest": "^27.0.6",
  
- DOM Environment: "jsdom":  "version": "16.6.0"
  

Relevant code or config

```javascript
test('can edit options',async ()=>{
    const testValue = 'test option';
    const {getAllByPlaceholderText} = init()
    
    const inputs = getAllByPlaceholderText(translationBase + "Answer placeholder", {})
    userEvent.type(inputs[0], testValue)
    userEvent.type(inputs[1], testValue)
    return waitFor(()=>{
      expect(inputs[0]).toHaveValue(testValue)
    })
  })
```

What you did:
I need to test several inputs, used `userEvents.type()` for each of them

What happened:
the test value is typed two times into the first input

![image](https://user-images.githubusercontent.com/66993391/125178305-4caefd00-e1ec-11eb-8b2d-2ce41363f98f.png)

Reproduction repository:
have tried to create a reproduction but on[codesandbox](https://codesandbox.io/s/modest-fermat-m2nci?file=/src/name-edit.spec.js) it works as expected.

**Comment by ph-fritsche** [comment]
This could be something trapping the focus on the first element. Maybe there is something wrong in your `init()`.

There isn't much we can do without a reproduction. Should anyone experience a similar issue and/or be able to come up with a reproduction, please add this information and we might be able to investigate this further.

**Comment by johnmryan** [comment]
I was seeing the same issue with this version. Bumped my version down to explicitly @13.0.7 and it fixed it. Going to just avoid updating for now. 

Haven't gotten a chance to look through the releases from 13.0.7 to 13.1.9, but something definitely changed in the user.type behavior.
