### ISSUE TITLE
Deprecate and remove legacy `type` features

### ISSUE THREAD

**Issue by nickmccurdy** [testing-library/user-event#702]
The `specialChars` export and `{}` syntax for modifier keys from the old `type` implementation still exist, but are no longer necessary with the new implementation. Our plan for now is to mark features as deprecated in 13.x, and remove them in 14.0.0. We also might want to consolidate the two tables in the readme.

**Comment by ph-fritsche** [comment]
`keyCode` is already marked as deprecated and should be removed in v14 as well.
https://github.com/testing-library/user-event/blob/673c2257ef63f69dd46b9fe2d4bbc3146db1426b/src/keyboard/getEventProps.ts#L12-L16
(The implementation is also bugged - see #727 )

**Comment by ph-fritsche** [comment]
Remaining `keyboardState.carryValue` is internal and can be removed in a `refactor` once behavior plugins for `time` and `date` input are rewritten.
