### ISSUE TITLE
Pointer events set to none shouldn't throw

### ISSUE THREAD

**Issue by jseto** [testing-library/user-event#708]
- `@testing-library/user-event` version: 13.2.0

- Testing Framework and version:
   jest 27.0.4
- DOM Environment:
   jsdom

Relevant code or config

```javascript
	it( 'should not call onClick event', ()=> {
		const clickSpy = jest.fn()
		render( <div style={{ pointerEvents: 'none'}} onClick={ clickSpy }>Something here</div> )
		userEvent.click( screen.getByText( 'Something here' ) )
		expect( clickSpy ).not.toHaveBeenCalled()
	})
```

What you did:

Pass the test

What happened:

An exception is thrown:

Error: unable to click element as it has or inherits pointer-events set to "none"

Reproduction repository:

N/A

Problem description:

Throwing an exception here is not the expected behaviour as the browser will let you click but no event fired.

By throwing the exception you are giving clues of the inner implementation which, in my opinion, should not be like that.

Suggested solution:

If agreed after some discussion...

Remove the exception and continue execution silently

**Comment by ph-fritsche** [comment]
> the browser will let you click but no event fired

That is a misconception. You can not click a `pointer-event: none` element. You can click on the same area that element occupies in the layout, but strictly speaking there is no pointer event on that element.
Therefore the input action does not traverse up the DOM but "falls through" the element to whatever element is the first behind it with pointer events.

When you use `userEvent.click(element)` you explicitly ask the library to perform an input action on that element. While we also support other testing environments, the primary environment for this library is jest+jsdom which has no layout.
So we don't know what to do with your command and discarding the events silently let to confusion - see discussion in #639 .

Therefore #647 added the error. Please work around by expecting it:
```js
expect(() => userEvent.click(screen.getByText( 'Something here' ))).toThrow()
expect( clickSpy ).not.toHaveBeenCalled()
```
