### ISSUE TITLE
UIEvent.view is always null

### ISSUE THREAD

**Issue by creage** [testing-library/user-event#709]
- `@testing-library/user-event` version: 13.2.1

- Testing Framework and version: "@testing-library/react": "12.0.0",
  
- DOM Environment: "@testing-library/jest-dom": "5.14.1",
  

Relevant code or config

```javascript
import React from 'react';
import { FormInput } from '@fluentui/react-northstar';

import {render, screen} from '@testing-library/react';
import userEvent from '@testing-library/user-event';

test('type in form input', () => {
  render(
    <FormInput label="Test" placeholder="welcome" />
  );

  userEvent.type(screen.getByPlaceholderText('welcome'), 'hello');

  expect(screen.getByDisplayValue('hello')).toBeInTheDocument();
});
```

Trying to execute code above fails the test with `TypeError: Cannot read property 'document' of null`

According to [specs](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/view) the `view` property of UIEvent should point to the `window`.

This issue affects other libraries, like https://github.com/microsoft/fluentui/issues/19233.

The more generic `fireEvent` works fine though - the `view` property is defined as expected:
```js
act(() => {
    fireEvent.change(screen.getByPlaceholderText('welcome'), { target: { value: 'hello' } });
});

**Comment by ph-fritsche** [comment]
First of all thanks for the report!
But I don't think that this is a bug in `userEvent`.

MDN seems to be wrong here - at least regarding the [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent#browser_compatibility).
See https://codesandbox.io/s/eventview-njq60?file=/src/App.js .
Open https://njq60.csb.app/ with different browsers.
The `event.view` is `null` on `input` event in Chrome (Ubuntu) and `Window` in Firefox (Ubuntu).
It is `undefined` on `change` event in both.

It's also the same with `fireEvent` which we use to dispatch the `change` event.
https://github.com/testing-library/user-event/blob/9600abb57d28b5e356e68d858f7c8f84e17e4a54/src/keyboard/shared/fireInputEvent.ts#L127

**Comment by Ethan-Arrowood** [comment]
@ph-fritsche what would fluentui and northstar need to do to fix this issue? Is it just not throw an error when this property is null?

**Comment by ph-fritsche** [comment]
@Ethan-Arrowood Have a look at the PR at fluentui.

**Comment by layershifter** [comment]
> See https://codesandbox.io/s/eventview-njq60?file=/src/App.js .
> Open https://njq60.csb.app/ with different browsers.
> The `event.view` is `null` on `input` event in Chrome (Ubuntu) and `Window` in Firefox (Ubuntu).
> It is `undefined` on `change` event in both.

@ph-fritsche this is not correct 😥 `event.view` is supported widely, but **only** on `UIEvent`.

`change` event does not inherit `UIEvent`, see https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event-

---

> Several interfaces are direct or indirect descendants of this one: MouseEvent, TouchEvent, FocusEvent, KeyboardEvent, WheelEvent, InputEvent, and CompositionEvent.

https://developer.mozilla.org/en-US/docs/Web/API/UIEvent

---

I modified your CodeSandbox to use `keydown` (https://codesandbox.io/s/event-view-forked-dn3w7?file=/src/App.js) and it works:

![image](https://user-images.githubusercontent.com/14183168/135230250-cfe5a990-3532-419d-864e-218f000c26e1.png)

In that place we use only `UIEvent` (`MouseEvent`, `PointerEvent`, `TouchEvent`) so `event.view` should work there ¯\_(ツ)_/¯

I have not tested yet, but this looks like a problem specific to JSDom...

**Comment by ph-fritsche** [comment]
> > The `event.view` is `null` on `input` event in Chrome (Ubuntu) and `Window` in Firefox (Ubuntu).
> > It is `undefined` on `change` event in both.
> @ph-fritsche this is not correct disappointed_relieved `event.view` is supported widely, but **only** on `UIEvent`.

The part about change was regarding the `fireEvent.change` call which has never a `view` property.
This seems to work just because the `keydown` event is not fired and the event handler in fluentui is not triggered.

The `input` event however should be an `InputEvent` and thus implement `UIEvent.view`, but in Chrome it does not.
I did not go further and test all UIEvents. :disappointed: 
https://w3c.github.io/uievents/#event-type-input

> In that place we use only `UIEvent` (`MouseEvent`, `PointerEvent`, `TouchEvent`) so `event.view` should work there ¯_(ツ)_/¯
> 
> I have not tested yet, but this looks like a problem specific to JSDom...

You're probably right.
The `InputEvent` seems to be the only `UIEvent` without a `view` property in browser.
https://codesandbox.io/s/uievent-view-go6kz

**Comment by ph-fritsche** [comment]
@Ethan-Arrowood I guess this should be an issue with Chrome (for `InputEvent`) and jsdom (for `UIEvent`).

**Comment by layershifter** [comment]
> The `InputEvent` seems to be the only `UIEvent` without a `view` property in browser.
> https://codesandbox.io/s/uievent-view-go6kz

Yeah, but we don't use `InputEvent` in our code:

https://github.com/microsoft/fluentui/blob/586adc8eb7c4bbe3429dcb2231d713d96fc3b716/packages/fluentui/react-northstar/src/utils/whatInput.ts#L90-L108

(we use only `MouseEvent`, `PointerEvent` & `TouchEvent`)
