### ISSUE TITLE
hover does not trigger mouseenter and mouseover events for disabled elements

### ISSUE THREAD

**Issue by rodolfoprr** [testing-library/user-event#715]
- `@testing-library/user-event` version: 13.2.1

What you did:

Using `.hover` in a disabled button element.

What happened:

It does not trigger `mouseenter` and `mouseover` events.

Problem description:

According to the source code, we don´t trigger those events for disabled elements:

https://github.com/testing-library/user-event/blob/9600abb57d28b5e356e68d858f7c8f84e17e4a54/src/hover.ts#L33-L38

I'm wondering the reason behind that decision. Is that expected?

Suggested solution:

Remove `isDisabled` checks?

**Comment by ph-fritsche** [comment]
Yes, this is expected as the browser does not dispatch these events for disabled elements.
https://codesandbox.io/s/userevent-715-5ulpd?file=/src/App.js

**Comment by csantos-nydig** [comment]
I know this is a pretty old issue, but should we revisit this implementation as of now?

all browsers seems to trigger `mouseover`/`mouseout` in disabled elements now

https://github.com/testing-library/user-event/assets/87080313/0c6d02b8-bfc8-457f-b8e5-300656be345d

Tested on:
- Safari: 17.5 (19618.2.12.11.6)
- Firefox: 115.12.0esr (64-bit)
- Google Chrome: Version 126.0.6478.127 (Official Build) (arm64)

OS: macOs Sonoma 14.5
