### ISSUE TITLE
Hover doesn't trigger css changes

### ISSUE THREAD

**Issue by angel-git** [testing-library/user-event#719]
- `@testing-library/user-event` version: `13.2.1`
- Testing Framework and version: `jest@26.6.0`
- DOM Environment: `jsdom@16.7.0`

Reproduction repository:

It's a create-react-app with styled-components: https://github.com/angel-git/jsdom-issue

```
yarn install
yarn test
```

Problem description:

Hi first of all, sorry if the issue doesn't belong here, with so many libs around I don't know where to create it.
Looks like the hover event is not working, css changes that should happen to child components are not taking into account. It works on browser but not in the test.

See `App.test.js`.

```
  ● renders learn react link

    expect(element).toBeVisible()

    Received element is not visible:
      <div class="child" data-testid="child" />

       8 |   expect(screen.queryByTestId('child')).not.toBeVisible();
       9 |   userEvent.hover(screen.getByTestId('parent'));
    > 10 |   expect(screen.queryByTestId('child')).toBeVisible()
         |                                         ^
      11 | });
      12 |

      at Object.<anonymous> (src/App.test.js:10:41)
```

Notes:
While trying to create this small repository from a big one, i managed to fix the big one using:

```
  "resolutions": {
    "jsdom": "16.6.0"
  },
```

But here it doesn't fix the problem

Thanks

**Comment by ph-fritsche** [comment]
There is no way to control the pseudo-selectors. It's up to the environment to apply those.

But you should probably not functionally test `:hover` anyway as anything subject to `:hover` should be functionally irrelevant.

[Per MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover):
> **Note:** The `:hover` pseudo-class is problematic on touchscreens. Depending on the browser, the `:hover` pseudo-class might never match, match only for a moment after touching an element, or continue to match even after the user has stopped touching and until the user touches another element. Web developers should make sure that content is accessible on devices with limited or non-existent hovering capabilities.

**Comment by angel-git** [comment]
@ph-fritsche thanks for your reply, why not then remove the hover api if it doesn't work?

**Comment by ph-fritsche** [comment]
It does work. It triggers the events that happen when the user moves a mouse over the element.

The `:hover` pseudo-class might or might not be applied accordingly depending on the environment.

**Comment by bodograumann** [comment]
Could we add a notice about this in the documentation?

**Comment by ph-fritsche** [comment]
This isn't specific to `user-event`. I'm not sure how we could add such information without plastering the docs with general knowledge about the DOM.
But PRs to the docs are always welcome at https://github.com/testing-library/testing-library-docs
