### ISSUE TITLE
ev.which is always 0 when type is used with addEventListener('keydown')

### ISSUE THREAD

**Issue by fa93hws** [testing-library/user-event#726]
- `@testing-library/user-event` version: 13.2.1

- Testing Framework and version:
  
- DOM Environment: 8.5.0
- jest version: 27.2
- jsdom version: 16.6.0
  

Relevant code or config

```javascript
/**
 * @jest-environment jsdom
 */
const { default: userEvent } = require('@testing-library/user-event');

describe('foo', () => {
  function generateHTML() {
    const input = document.createElement('input');
    input.id = 'input-id';
    input.addEventListener('keydown', ev => {
      console.log('addEventListener:', {
        keyCode: ev.keyCode,
        which: ev.which,
      });
    });

    document.body.appendChild(input);
  }

  it('bar', () => {
    generateHTML();
    const input = document.getElementById('input-id');
    userEvent.type(input, 'a')
    expect(1).toBe(1);
  })
})
```

What you did:
nothing but running the test

What happened:
I got `addEventListener: { keyCode: 97, which: 0 }` in the console

Reproduction repository:
https://github.com/fa93hws/testing-library-userevent-which-bug-demo

Problem description:
`which` should be `97`, same as `keyCode` instead of 0

Suggested solution:
`which` should be `97`, same as `keyCode` instead of 0

**Comment by ph-fritsche** [comment]
`UIEvent.which` is non-standard and deprecated. See MDN [here](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which) and [here](https://developer.mozilla.org/de/docs/Web/API/KeyboardEvent):
> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

We just set the `keyCode` for backward-compatibility and don't intend to implement any other deprecated properties on the event.

You should rely on [`KeyboardEvent.key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) (for key meaning) or [`KeyBoardEvent.code`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) (for physical key position) instead.
