### ISSUE TITLE
keyCode from keyboard is wrong for letter

### ISSUE THREAD

**Issue by fa93hws** [testing-library/user-event#727]
- `@testing-library/user-event` version: 13.2.1

- Testing Framework and version:
  
- DOM Environment:
  

Relevant code or config

```javascript
onKeyDown = (ev) => { console.log(ev.keyCode)}
```

What you did:
press `c`
What happened:
`99` is logged instead of `67`

Reproduction repository:

Problem description:
I think the keycode is not the ascii code for character. https://github.com/testing-library/user-event/blob/main/src/keyboard/getEventProps.ts#L16
Suggested solution:

**Comment by ph-fritsche** [comment]
`keyCode` is deprecated. Use `code` instead.

Per [MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode):
> Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. [...] Be aware that this feature may cease to work at any time.

Our implementation is also marked as deprecated and will not be fixed but removed in the future.
If you want to, you can plugin your own `keyboardMap` with `keyCode` support.
