### ISSUE TITLE
Input to element controlled by `rifm` fails due to jumping cursor position

### ISSUE THREAD

**Issue by Dm1Korneev** [testing-library/user-event#758]
- `@testing-library/user-event` version: 13.1.9 (Have tryed the last one also)

- Testing Framework and version: `@testing-library/react 11.2.7`
- DOM Environment: `@testing-library/jest-dom 5.12.0`

**Test**

```javascript
await userEvent.type(screen.getByPlaceholderText('£0.00'), '123456')
```

I use [rifm](https://github.com/realadvisor/rifm) library to format money in input and this library controls cursor position in input element.
But in current version of `user-event` it set cursor in the last position after enter each symbol that brakes `rifm` formatting

Is it possible to disable this feature somehow?

**Comment by ph-fritsche** [comment]
It looks like everything on our part is resolved. The remaining issue looks to be an issue with `rifm` itself and therefore out of scope.
If anybody gathers more insight, please add the information here. Should we have missed something, I'll gladly reopen.
