### ISSUE TITLE
Typing targets wrong element when focus changes

### ISSUE THREAD

**Issue by ghengeveld** [testing-library/user-event#775]
- `@testing-library/user-event` version: 12.7.3

- Testing Framework and version: Storybook 6.4 alpha
  
- DOM Environment: Brave browser (non-headless, latest version)
  

Relevant code or config

```javascript
const canvas = within(canvasElement);
await userEvent.type(canvas.getByTestId('email'), 'gert@chromatic.com', { delay: 100 });
await userEvent.type(canvas.getByTestId('password1'), 'secret', { delay: 100 });
await userEvent.click(canvas.getByRole('button', { name: /create account/i }));
```

What you did:

I'm running Testing Library with userEvent directly in the browser, on a live React component. This is part of ongoing work to build a [GUI for Testing Library in Storybook](https://storybook.js.org/blog/interaction-testing-sneak-peek/).

What happened:

Typing into an input will set focus to the input, and then fire a series of keyboard events at it. When you click anywhere outside the input field or press Tab while the delayed typing is running, thereby moving focus away from the input, the keyboard events go to a different element than the one originally targeted. This might very well be a different input field.

<img width="758" alt="Screenshot 2021-11-03 at 13 10 15" src="https://user-images.githubusercontent.com/321738/140057599-81021250-7f94-4b77-8a34-a663ee199366.png">

Reproduction repository:

https://github.com/storybookjs/storybook/blob/next/addons/interactions/src/components/AccountForm/addon-interactions.stories.tsx#L60-L63

Live example (slightly different but same problem): https://5a375b97f4b14f0020b0cda3-naptvsjacg.chromatic.com/?path=/story/addons-interactions-accountform--verification-success (you'll have to switch to another story and back to allow it to play correctly (its a bug on our end))

Problem description:

Keyboard events are sent to the currently active element rather than the element passed as 1st argument to `userEvent.type`.

Suggested solution:

Either restore focus before sending the next key event in case focus was lost, or always send the key events to the targeted element regardless of focus state.

**Comment by ph-fritsche** [comment]
This is the intended behavior as the user can not input character data to an element that is not the `activeElement`.
If e.g. an event handler moves the focus to a different element, it is an important catch for the dev that the focus moved unexpectedly.
