### ISSUE TITLE
Bug - Inconsistent behavior between browser and test environment with react-hook-form with react-select

### ISSUE THREAD

**Issue by wdfinch** [testing-library/user-event#777]
- `@testing-library/react` version: 11.2.7
- Testing Framework and version: Jest + bundled version with CRA version 4.0.3
  
- DOM Environment:  bundled version with CRA version 4.0.3
  

### Relevant code or config:

[react-hook-form-jest-issues.zip](https://github.com/testing-library/react-testing-library/files/7501213/react-hook-form-jest-issues.zip)

I have tried to reproduce this issue in code sandbox, but due to some issue with code sandbox, I am unable to click a `react-select` element in a test. I have opened an issue with the code sandbox client for this. Therefore I have attached a simple reproduction using `create-react-app`.

https://github.com/codesandbox/codesandbox-client/issues/6257

### What you did:

Ran a test that selects an option from a `react-select` component.

### What happened:

The form management library (`react-hook-form` in this case) did not update its internal state correctly inside of the testing environment only. Specifically, the library is reporting that errors are present in the `formState.errors` object when there should be no errors. If the actions in the test are replicated on the browser, no errors are present after the option is selected which is the expected behavior. 

### Reproduction:

1. Open the attached project
2. Run `npm install`
3. Run `npm start` and open the project in your browser
4. Select an option from the select input. Open the console. Notice that the final console log of `formState.errors` is an empty object and `formState.isValid` is true as expected .
5. Run `npm test `and select all tests using the a key
6. Notice that the final console log of the test reports `formState.errors` as not being empty. Instead, an error is present while `formState.isValid` is true. This is incorrect and does not match how the browser logs.

The output from jest is:
`formState.errors: [object Object] formState.isValid: true
`
The output from the browser is:
`formState.errors: undefined formState.isValid: true
`

### Problem description:

This is a problem since I cannot write accurate tests for a large portion of my app. The issue seems to be isolated to r`eact-hook-form` version 7.15.1 and above, `react-select`, and inputs that use the field array feature inside `react-hook-form`. I spoke to the `react-hook-form` author and he does not believe this is an issue with the `react-hook-form` library as the correct behavior occurs in the browser. 

### Suggested solution:

I'm not sure what the correct code solution is, but it seems to be related to context not being updated correctly in certain cases within the testing environment.

**Comment by ph-fritsche** [comment]
@eps1lon 
To me this does not look like an issue with `user-event` or any `testing-library` package but with `react-hook-form`.
Maybe it relies on some API not available in `jsdom`.

**Comment by wdfinch** [comment]
So the version of react-hook-form where this issue starts happening is 7.15.1.

Below is the release notes and source code for this version. I don't see anything unusual that would lead to this issue. It was just a minor release change and `react-hook-form` has no non-dev dependencies. 

https://github.com/react-hook-form/react-hook-form/releases/tag/v7.15.1

Any ideas? If you can pinpoint the API incompatibility, I can suggest a change/workaround to them.

**Comment by ph-fritsche** [comment]
@wdfinch I'm sorry, but I don't have the capacity to debug every library out there. We act on the DOM and `react-hook-form` acts on the DOM. This is not an issue with `user-event` until someone can demonstrate that we do something to the DOM that differs from what a user interaction in the browser does to the DOM.

If you can break down what aspect of the DOM is used for `formState.errors` or at least identify the commit that changed the behavior, I might be able to look into it, but for now I'll close this as unrelated to this repo. (I'll gladly reopen if your research on this should reveal a bug on our side.)

**Comment by wdfinch** [comment]
@ph-fritsche thanks for the reply. Totally understand. I spent some time digging into this and have some more details. I'm still not sure what the exact cause it as I'm not very familiar with the internal workings of `react-testing-library` and `user-event`, but hopefully this helps. 

The exact commit where this broke was this:

https://github.com/react-hook-form/react-hook-form/commit/15f2dc5c6d23af7cab4e544edd02ad4adbcb6ee2

Given this is a small commit, I believe the issue was the change in `src/useController.ts`. 

If you look at how `react-select` calls `onBlur`, it seems that a synthetic event is passed to the `onBlur` function.

https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Select.tsx#L1379

I did take a look at [this bug](https://github.com/testing-library/react-testing-library/issues/908) which seems related, but react-select isn't a native HTML element and I'm not trying to use the `fireEvent.onChange` method but rather click on the element.

Does this help at all? I would be happy to dig some more and produce a more minimal reproduction if you could point me in the right direction.

**Comment by wdfinch** [comment]
It seems this has been resolved in newer react-hook-form versions.

**Comment by ph-fritsche** [comment]
Thanks for the update on this.
