### ISSUE TITLE
userEvent.hover does not fire event on disable element

### ISSUE THREAD

**Issue by elad823** [testing-library/user-event#789]
[-](url) `@testing-library/react` version: ^10.2.1
- Testing Framework and version: jest ^24.9.0
- DOM Environment: jsdom ^5.10.0

### Relevant code or config:

```js
    const pickButton = await findByLabelText(/Pick/, {
      selector: "button",
    });
    expect(pickButton).toHaveAttribute("disabled");
    act(() => {
      userEvent.hover(pickButton);
    });
    expect(await findByText(/Pick/)).toBeInTheDocument();   
```

### What you did:
Fetched a disabled button, try to fire the hover event,  and expect the tooltip toBeInTheDocument.

### What happened:
Tooltip was not found:
`TestingLibraryElementError: Unable to find an element with the text: /Pick/. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.`

### Reproduction:
See code above

### Problem description:
 fireEvent.mouseOver does not fire hover event on disable button. 

![WhatsApp Image 2021-11-19 at 01 37 36](https://user-images.githubusercontent.com/25868731/142514082-fe7ba56e-1761-45ac-a970-7ae1ddb1e613.jpeg)

**Comment by ph-fritsche** [comment]
There is no `mouseover` event when hovering disabled elements.
https://codesandbox.io/s/happy-pine-k7q7x?file=/src/App.js
