### ISSUE TITLE
userEvent.type not entering spaces into inputs with type password

### ISSUE THREAD

**Issue by rreevesforage** [testing-library/user-event#792]
Based on this [issue](https://github.com/testing-library/user-event/issues/479), there appears to be a sanitation algorithm that may be removing (not entering) space characters into password fields. There is a work-around using `fireEvent.change()` to get my test to pass instead

> Hi, I think that the same problem is present when the input control is of type `url`: https://github.com/jsdom/jsdom/blob/5279cfda5fe4d52f04b2eb6a801c98d81f9b55da/lib/jsdom/living/helpers/form-controls.js#L266
> _Originally posted by @BentMylund in https://github.com/testing-library/user-event/issues/479#issuecomment-773395242_

**Comment by ph-fritsche** [comment]
`password` is not sanitized in `jsdom`:
https://github.com/jsdom/jsdom/blob/a61fdb886a30fce6a3aa68002e1af6e5bcb4c372/lib/jsdom/living/helpers/form-controls.js#L180-L186

Using `fireEvent.change` is not a workaround here. It's a [Volkswagen](https://github.com/auchenberg/volkswagen).
