### ISSUE TITLE
UIEvent modifiers per `getModifierState`

### ISSUE THREAD

**Issue by themadtitanmathos** [testing-library/user-event#812]
- `@testing-library/user-event` version:
13.5.0

- Testing Framework and version:
Jasmine 2.5.2

Relevant code or config:

```javascript
userEvent.type(input, '{capslock}hello');
expect(input.value).toEqual('HELLO');
```

What you did:
Tried to use `userEvent.type` to simulate a user typing into an input text box with the caps lock modifier turned on.

What happened:
When the caps lock modifier is seen/sent as a `keyDown` event to the component, the `event.getModifierState` does _not_ recognize the key as being an actual caps lock modifier, even though `event.key === 'CapsLock'` as expected.

The following screenshot was taken while evaluating the `event` passed into my component's `onKeyDown` handler.

![image](https://user-images.githubusercontent.com/54560914/146454445-87be6cf2-abee-496a-b302-d8e2dcf5bce9.png)

Problem description:
Caps lock key down events are not given their proper modifier status.

Suggested solution:
Have the event generated properly signify `event.getModifierState('CapsLock') === true`. I believe this would be done by ensuring the `fireEvent` behind the scenes is properly setting `modifierCapsLock: true` when appropriate.

**Comment by ph-fritsche** [comment]
Thanks for opening this issue. :heart: 

Yes, we should implement https://www.w3.org/TR/uievents/#event-modifier-initializers

Additional note: The `keydown` for `CapsLock` still has the previous set of modifiers in the browser
