### ISSUE TITLE
index.d.ts is not a module

### ISSUE THREAD

**Issue by mohetti** [testing-library/user-event#819]
- `@testing-library/user-event` version: 14.0.0-beta.4

- Testing Framework and version:
- jest: 27.4.4
- ts-jest: 27.1.1

- DOM Environment:
- jsdom: 27.4.4

What you did:
`npm i --save-dev @testing-library/user-event@14.0.0-beta.4`

What happened:
Received the following error-message:
`File '/home/<name>/Projects/battleship/node_modules/@testing-library/user-event/dist/index.d.ts' is not a module.`

Reproduction repository:
You can recreate the problem with the following steps:
- `git clone git@github.com:mohetti/jestBattleship.git`
- `npm install`
- open `./src/Components/SingleBoard/index.test.ts`
- At this point, the latest user-event version is installed and the tests run fine. To reproduce the error:
- `npm i --save-dev @testing-library/user-event@14.0.0-beta.4`
- after installation and with index.test.ts open, the error message appears

Thank you for looking into it.

**Comment by ph-fritsche** [comment]
Thanks for the report :heart: 

I have no clue how I tricked myself into thinking that this export included a working declaration.
