### ISSUE TITLE
Cannot tab in react-modal

### ISSUE THREAD

**Issue by dannyharding10** [testing-library/user-event#820]
- `@testing-library/user-event` version: 12.0.2

- Testing Framework and version: Jest, whatever version CodeSandbox uses
- DOM Environment: jsdom, whatever version CodeSandbox uses

Relevant code or config

```javascript
import Modal from 'react-modal';

function ModalTest() {
  return (
      <Modal isOpen={true}>
         <button>button 1</button>
          <button>button 2</button>
      </Modal>;
}

it('should allow tabbing inside of a modal', () => {
  const { getByText } = render(<ModalTest {...props} />);

  const button1 = getByText("button 1");
  const button2 = getByText("button 2");

  expect(button1).toBeInTheDocument();
  expect(button2).toBeInTheDocument();

  button1.focus();
  expect(button1).toHaveFocus();
  userEvent.tab();
  // fails right here
  expect(button2).toHaveFocus();
});
```

What you did:
 1. Render a Modal from react-modal with some tabbable elements
 2. Try to tab between elements using [userEvent.tab()](https://testing-library.com/docs/ecosystem-user-event/#tabshift-focustrap)

What happened:
 3. The focused element does not change 😢

![image](https://user-images.githubusercontent.com/11875246/147830506-c526f70d-6032-4357-a848-058f5ff5ccc7.png)

Reproduction repository:
https://codesandbox.io/s/xenodochial-mestorf-qx6j8?file=/src/__tests__/index.js

Problem description:
Tabbing does not work properly when inside of a react-modal.

### Additional notes:
I'm aware the issue could be in the [react-modal](https://github.com/reactjs/react-modal) library, so I made a companion issue over there ([clicky](https://github.com/reactjs/react-modal/issues/919)). I'm also thinking I could just need more understanding of how the focus trapping is working in react-modal / user-event so I can get them to play together nicely.

**Comment by ph-fritsche** [comment]
> * `@testing-library/user-event` version: 12.0.2

Could you please test with `v13.5.0` and/or `v14.0.0-beta`.  
I won't look into possible bugs of a version that is outdated since `Jun 21, 2020`.

**Comment by dannyharding10** [comment]
@ph-fritsche  🤦‍♂️  I think this fixed it! I was using a CodeSandbox template so I assumed that it was the latest version of user-event. It did not work with v13.5.0, but it did work with v14.0.0-beta. Strangely, I was able to narrow the fix down to [v14.0.0-alpha.11](https://github.com/testing-library/user-event/releases/tag/v14.0.0-alpha.11), which does not seem to have anything specific to tabbing, which I found odd. Do you have any idea why these changes would have fixed this issue?

Thanks for pointing me in the right direction! Is there a timeline for when v14 will be released?

**Comment by ph-fritsche** [comment]
> Strangely, I was able to narrow the fix down to [v14.0.0-alpha.11](https://github.com/testing-library/user-event/releases/tag/v14.0.0-alpha.11), which does not seem to have anything specific to tabbing, which I found odd. Do you have any idea why these changes would have fixed this issue?

I don't think this can be right.

> Thanks for pointing me in the right direction! Is there a timeline for when v14 will be released?

Not really. You can see the open issues on the [milestone](https://github.com/testing-library/user-event/milestone/1). I might be able to resolve the remaining issues this weekend. If we just look at the code, I think this is already worth to be called stable and replace `v13.5.0`. In fact if you're actively working on a project, I'd recommend to switch now.
The remaining issues could as well be resolved in minor releases.

But before the official release and recommendation to migrate existing projects, I'd like to get a little more feedback to ensure this is working in different environments (see e.g. the issues about the build) so that we won't run into a situation where we would have to switch to `v15` after just a few weeks.
Also we need to update the docs.

**Comment by christocarr** [comment]
@danny-does-stuff did you manage to resolve your issue? I'm facing the same problems with userEvent v14.

**Comment by danny-does-stuff** [comment]
@christocarr sorry, I don’t remember what exactly I was working on when I made this issue. I was satisfied with the responses here, though. Are you able to duplicate it with the codesandbox I shared above?

**Comment by danny-does-stuff** [comment]
@christocarr what versions of the relevant packages are you using? can you modify my code sandbox to duplicate your issue?

**Comment by christocarr** [comment]
@danny-does-stuff all my packages are up to date. I have other react-modal tests which are passing. I've updated your codesandbox to a very similar approach I'm using for a company project where the test fails but passes on the codesandbox which is very strange.

**Comment by christocarr** [comment]
@danny-does-stuff all my packages are up to date. I have other react-modal tests which are passing. I've updated your codesandbox to a very similar approach I'm using for a company project where the test fails but passes on the codesandbox which is very strange.

**Comment by phyrwork** [comment]
Hi, I work with @christocarr 

We've [duplicated your sandbox](https://codesandbox.io/s/exciting-glitter-6pgrjw) and observe that the tabbing inside modal test breaks when updating react-modal from 3.15.1 to 3.16.1.

**Comment by danny-does-stuff** [comment]
@Ninita1 and other future devs, I was able to fix my issue by simply updating @testing-library/react to version 14 or later. It was not working in older versions, but worked after upgrading
