### ISSUE TITLE
Calling `userEvent.upload` from Firefox opens a file upload window which breaks headless mode

### ISSUE THREAD

**Issue by SquiffyK7** [testing-library/user-event#824]
- `@testing-library/user-event` version: 13.5.0

- Testing Framework and version: Karma 6.3.9, jasmine 4.0.1
  
- DOM Environment: Firefox 95.0
  

Relevant code or config

```javascript
import React from "react";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";

it("upload file", () => {
  const file = new File(["hello"], "hello.png", { type: "image/png" });

  render(
    <div>
      <label htmlFor="file-uploader">Upload file:</label>
      <input id="file-uploader" type="file" />
    </div>
  );
  const input = screen.getByLabelText(/upload file/i);
  userEvent.upload(input, file);

  expect(input.files[0]).toBe(file);
  expect(input.files.item(0)).toBe(file);
  expect(input.files.length).toBe(1);
});
```

What you did:
Run `yarn test` in the linked reproduction repo to execute the above test in Firefox.

What happened:
Firefox launches a file upload window.

Reproduction repository:
https://github.com/SquiffyK7/user-event-upload

Problem description:
Calling `userEvent.upload` within a firefox environment launches a file upload window. This is a problem when running in headless mode because there is no GUI to render the window, so the test can't run and an error like the following is thrown:
```
.04 01 2022 22:10:11.407:ERROR [launcher]: FirefoxHeadless crashed.
	*** You are running in headless mode.

(firefox:3849936): Gtk-CRITICAL **: 22:10:11.190: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(firefox:3849936): Gtk-CRITICAL **: 22:10:11.190: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(firefox:3849936): Gtk-CRITICAL **: 22:10:11.190: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
ExceptionHandler::GenerateDump cloned child 3850206
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
Exiting due to channel error.
```

My current workaround for this is to replace
```
userEvent.upload(input, file);
```
with
```
fireEvent.change(input, {
  target: { files: { item: () => file, length: 1, 0: file } },
});
```

The same test works in a chrome headless environment, as chrome does not attempt to launch a file upload window.

Suggested solution:
Don't launch the file upload window.

**Comment by ph-fritsche** [comment]
We don't launch the window, the browser does - presumably on the `click` event on the file input.
I don't think there is anything we can do about this. This is a bug with Firefox.

**Comment by Wellers0n** [comment]
great, fire event worked for me

```js
fireEvent.change(input, {
  target: { files: { item: () => file, length: 1, 0: file } },
});
```
