### ISSUE TITLE
Document migration steps for updating to `user-event@14`

### ISSUE THREAD

**Issue by NateRadebaugh** [testing-library/user-event#836]
From the current documentation:
> "This is still a pre-release and might be subject to breaking changes if they should be deemed necessary in the light of feedback we receive for this version.
> **All planned breaking changes are already implemented though.**
> If you are starting or actively working on a project, we recommend to use this pre-release, as it includes important bug fixes and new features."
>
> https://testing-library.com/docs/user-event/intro/

What are the planned breaking changes that have been implemented and what are the mitigations?

**Comment by ph-fritsche** [comment]
Breaking changes are listed in https://github.com/testing-library/user-event/releases

**Comment by MerlinMason** [comment]
Any suggestions for a workaround of the removed `{selectall}` option?

**Comment by ph-fritsche** [comment]
@MerlinMason Describe how the user would "select all". You can use the `pointer`, e.g. per `user.tripleClick(inputElement)`, or the keyboard (`user.keyboard('{Control>}[KeyA]')`)

**Comment by MerlinMason** [comment]
Ahh yeah right, thanks! That makes sense!

In my case, I was trying to remove some text from an input, just spotted `.clear()` in the the utility docs. So I could just replace: 

```js
userEvent.type(input, "{selectall}{del}");
```
with:
```js
await user.clear(input);
```
