### ISSUE TITLE
_userEvent.default.setup is not a function

### ISSUE THREAD

**Issue by Tommoore96** [testing-library/user-event#839]
- `@testing-library/user-event` version: ^14.0.0-beta
- DOM Environment: 8.11.1
- Node version: 14.17.4

Relevant code or config

```javascript
const user = userEvent.setup()
```

What you did:
Tests worked perfectly before updating, I just wanted the latest version for the pointer method.

Followed the latest documentation and tried multiple versions 14 and above.

Imported like so:
```js
import userEvent from '@testing-library/user-event';
```
and initialised like so:
```js
const user = userEvent.setup()
```

What happened:
Tests failed and receive following error:
`TypeError: _userEvent.default.setup is not a function`

**Comment by ph-fritsche** [comment]
`_userEvent.default.setup` suggests that the `import` statement is transpiled before being executed.

Could you please provide a reproduction?

**Comment by ph-fritsche** [comment]
@bijay-ps `userEvent.setup()` was introduced in `v14`.

**Comment by nickmccurdy** [comment]
What build tools are you using (it would help to see your configs as well)?

**Comment by mattxyzeth** [comment]
The same thing happened to me. I'm using typescript with jest Node 16 lts.

```json
"devDependencies": {
    "@testing-library/jest-dom": "^5.16.2",
    "@testing-library/react": "^12.1.3",
    "@testing-library/user-event": "^14.0.0-beta",
    "jest": "^27.5.1",
    "ts-jest": "^27.1.3",
    "ts-node": "^10.5.0"
}
```

```json
{
  "compilerOptions": {
    "allowUmdGlobalAccess": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noUnusedParameters": false,
    "noUnusedLocals": true,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "removeComments": true,
    "target": "ESNEXT",
    "module": "ESNext",
    "noEmit": true,
    "esModuleInterop": true,
    "jsx": "react"
  },
  "include": ["src"]
}
```

```javascript
export default {
  clearMocks: true,
  collectCoverage: true,
  coverageDirectory: "coverage",
  coverageProvider: "v8",
  preset: 'ts-jest/presets/default-esm',
  testEnvironment: 'jest-environment-jsdom',
  transform: {},
  transformIgnorePatterns: [
    "node_modules/(?!(ts-invariant)/)",
  ],
  extensionsToTreatAsEsm: [
    ".jsx",
    ".ts",
    ".tsx"
  ],
  globals: {
    'ts-jest': {
      useESM: true
    },
  },
  setupFilesAfterEnv: ['./jest.setup.ts']
};
```

```
import userEvent from '@testing-library/user-event'

const user = userEvent.setup()
```

error: `TypeError: userEvent.setup is not a function`

If I run `console.log(userEvent)` I get `{ PointerEventsCheckLevel: [Getter], default: [Getter] }`

**Comment by mattxyzeth** [comment]
Strangely enough, this issue is not present on my private CI runner I'm running on EC2. So it seems to be related to my local environment. I'm using `.nvmrc` so my node install should be the same. I'm not using different build/test tooling in the CI so I'm not sure what is different.

**Comment by ph-fritsche** [comment]
The import works just fine in node locally and on Stackblitz:
https://stackblitz.com/edit/node-ndptdu?file=index.mjs

@mattxyzeth Could you check if this works in both of your environments outside of the test runner?
We need to make sure this is not a misconfiguration of the transpiler.

**Comment by timdeschryver** [comment]
Could you create a reproduction please?
FWIW, the latest version (previous version too) seems to be working in combination with TypeScript in the Angular Testing Library - https://github.com/testing-library/angular-testing-library/pull/283

**Comment by mattxyzeth** [comment]
I’ll be busy for a while working on a big release coming up in the next couple of months. I will be happy to help in June. Sorry for not being available sooner.

**Comment by eps1lon** [comment]
`import userEvent from '@testing-library/user-event';` imports the default export of user-event as `userEvent`. However, that package has no default export. Only named exports. What you probably want is 
```diff
-import userEvent from '@testing-library/user-event';
+import * userEvent from '@testing-library/user-event';

**Comment by ph-fritsche** [comment]
https://unpkg.com/browse/@testing-library/user-event@14.0.0-beta.13/dist/index.mjs
```js
2966 | var userEvent = __spreadProps(__spreadValues({}, directApi_exports), {
2967 |   setup: setupMain
2968 | });
2969 | export {
2970 |   PointerEventsCheckLevel,
2971 |   userEvent as default
2972 | };
```

**Comment by eps1lon** [comment]
Oh we're talking about the beta. The latest stable didn't have a ESM entrypoint specified in the package.json so I was confused.

Can't say why this is happening in the beta without a repro.

**Comment by jahumes** [comment]
Could this be related to https://github.com/facebook/jest/issues/12120? I am running typescript and ts-jest and the import is `index.cjs`?

**Comment by capndave** [comment]
Same issue, but with any of the `userEvent` methods

**Comment by sherodtaylor** [comment]
same issue getting `_userEvent.default.click` is not a function with jest

jsdom fourteen w/ jest react-scripts

```
     "react": "^16.12.0",
     "react-scripts": "^3.4.1",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^12.1.3",
    "@testing-library/react-hooks": "^7.0.2",
    "@testing-library/user-event": "^14.0.4",
  ```

**Comment by sherodtaylor** [comment]
Any update on this?

**Comment by strmer15** [comment]
This happened to me today with `@testing-library/user-event` 14.1.0 with Typescript 4.6.3, Jest 27.5.1 and TS Jest 27.1.4 (latest version of each).

What I found was that this happened in my project because the files in the `dist` folder of the package are produced with `.cjs` and `.mjs` extensions. When I renamed them to use `.js`, moved the ESM entry point into a separate `esm` directory, and then updated the `package.json` paths, everything worked again for me.

Here's the patch file I created locally:

```
diff --git a/node_modules/@testing-library/user-event/dist/index.mjs b/node_modules/@testing-library/user-event/dist/esm/index.js
similarity index 100%
rename from node_modules/@testing-library/user-event/dist/index.mjs
rename to node_modules/@testing-library/user-event/dist/esm/index.js
diff --git a/node_modules/@testing-library/user-event/dist/index.cjs b/node_modules/@testing-library/user-event/dist/index.js
similarity index 100%
rename from node_modules/@testing-library/user-event/dist/index.cjs
rename to node_modules/@testing-library/user-event/dist/index.js
diff --git a/node_modules/@testing-library/user-event/package.json b/node_modules/@testing-library/user-event/package.json
index 9d8bdc0..35134cb 100644
--- a/node_modules/@testing-library/user-event/package.json
+++ b/node_modules/@testing-library/user-event/package.json
@@ -25,12 +25,12 @@
   "files": [
     "dist"
   ],
-  "main": "./dist/index.cjs",
-  "module": "./dist/index.mjs",
+  "main": "./dist/index.js",
+  "module": "./dist/esm/index.js",
   "exports": {
     ".": {
-      "require": "./dist/index.cjs",
-      "default": "./dist/index.mjs"
+      "require": "./dist/index.js",
+      "default": "./dist/esm/index.js"
     }
   },
   "types": "./dist/types/index.d.ts",
```

**Comment by JimLin94** [comment]
I came across the same issue too.
In my case, the issue was Jest didn't transform the file type `cjs` which is the compiled file of `user-event` to the plain js.
It was solved after I added the support type `cjs` to the transform configs of Jest in the package.json

```   
jest: {
  ...,
  "transform": {
    "^.+\\.(js|jsx)$": "babel-jest", -> "^.+\\.(js|jsx**|cjs**)$": "babel-jest",
  }
}
```

**Comment by martenmatrix** [comment]
I just had to update to the latest version:
`npm install @testing-library/user-event@latest --save`

**Comment by indgomez** [comment]
hello, i have the same problem and i have already tried with version 14 and 13.5.0 of @testing-library/dom/user-event
`TypeError: userEvent.upload is not a function`

**Comment by sbland** [comment]
> This happened to me today with `@testing-library/user-event` 14.1.0 with Typescript 4.6.3, Jest 27.5.1 and TS Jest 27.1.4 (latest version of each).
> 
> What I found was that this happened in my project because the files in the `dist` folder of the package are produced with `.cjs` and `.mjs` extensions. When I renamed them to use `.js`, moved the ESM entry point into a separate `esm` directory, and then updated the `package.json` paths, everything worked again for me.
> 
> Here's the patch file I created locally:
> 
> ```
> diff --git a/node_modules/@testing-library/user-event/dist/index.mjs b/node_modules/@testing-library/user-event/dist/esm/index.js
> similarity index 100%
> rename from node_modules/@testing-library/user-event/dist/index.mjs
> rename to node_modules/@testing-library/user-event/dist/esm/index.js
> diff --git a/node_modules/@testing-library/user-event/dist/index.cjs b/node_modules/@testing-library/user-event/dist/index.js
> similarity index 100%
> rename from node_modules/@testing-library/user-event/dist/index.cjs
> rename to node_modules/@testing-library/user-event/dist/index.js
> diff --git a/node_modules/@testing-library/user-event/package.json b/node_modules/@testing-library/user-event/package.json
> index 9d8bdc0..35134cb 100644
> --- a/node_modules/@testing-library/user-event/package.json
> +++ b/node_modules/@testing-library/user-event/package.json
> @@ -25,12 +25,12 @@
>    "files": [
>      "dist"
>    ],
> -  "main": "./dist/index.cjs",
> -  "module": "./dist/index.mjs",
> +  "main": "./dist/index.js",
> +  "module": "./dist/esm/index.js",
>    "exports": {
>      ".": {
> -      "require": "./dist/index.cjs",
> -      "default": "./dist/index.mjs"
> +      "require": "./dist/index.js",
> +      "default": "./dist/esm/index.js"
>      }
>    },
>    "types": "./dist/types/index.d.ts",
> ```

Slightly more edge case example. Using the UserEvent library in a `bit.dev` component had the same issue. I followed the steps above but what actually worked was moving the `index.cjs` file out of the `dist` to the same level as the `package.json` file and renaming it to `index.js`.

**Comment by alessandrocapra** [comment]
Also experiencing the same issue (just tried to update to latest), reverting to v13 for the moment until it's solved.

**Comment by ph-fritsche** [comment]
It seems that the current export - although it shouldn't - does still cause problems in some environments.

Would you please check out this
[alternative build of `v14.2.3`](https://pkg.csb.dev/testing-library/user-event/commit/5a1941e1/@testing-library/user-event/_pkg.tgz)
and report per reaction (:tada: = works, :confused: = does not work) on this comment if it works in your environment?

```
# yarn 1
yarn add https://pkg.csb.dev/testing-library/user-event/commit/5a1941e1/@testing-library/user-event
# yarn 2, 3
yarn add @testing-library/user-event@https://pkg.csb.dev/testing-library/user-event/commit/5a1941e1/@testing-library/user-event/_pkg.tgz
# npm
npm i https://pkg.csb.dev/testing-library/user-event/commit/5a1941e1/@testing-library/user-event
```

@Tommoore96
@laurmurclar @cwgw @creimers @wencel @k-sav @bijay-ps @JohnKearney2020 @FiveTies @jahumes @cblaine @headquarters @Joroze @AdamMescher @dimadk24 @litzebauer @Joblyn @suellenx @baNROne @MFukazawa @cedricmatalog @marcusvalverde @kokiy @johnshift @sbland @miphe
@mattxyzeth @capndave @sherodtaylor @strmer15 @JimLin94 @DominicTylor @indgomez @alessandrocapra

**Comment by KutanaDev** [comment]
The alternative build package changed the error to  TypeError: target.ownerDocument.createRange is not a function

**Comment by ph-fritsche** [comment]
@KutanaDev See https://github.com/testing-library/user-event/issues/902#issuecomment-1092886633

**Comment by ramonaspence** [comment]
I had the same error.

@testing-library/user-event version 14.3


Tried this test just to get it up and running:
```
test('inputing username updates state', () => {
        const user = userEvent.setup()
        render(<Login />);
        
        user.type(screen.getByPlaceholderText(/username/i),
            {target: {value: 'Text'}});
        expect(screen.getByDisplayValue(/Text/)).
        toBeInTheDocument()
    });
```

My error:
`_userEvent.default.setup is not a function`





> This version seems to have solved it.

I don't want to react to the comment since I'm not any of the people tagged.

**Comment by melan0802** [comment]
I got same problem, here is my situation:

1. `typeof userEvent` = `string`; `userEvent` = `index.cjs`;
2. In `jest.config.transform` I got `"^(?!.*\\.(js|jsx|css|json)$)": "<rootDir>/config/jest/fileTransform.js"`
3. fileTransform.js:

```
'use strict';

const path = require('path');

// This is a custom Jest transformer turning file imports into filenames.
// http://facebook.github.io/jest/docs/en/webpack.html

module.exports = {
  process(src, filename) {
    return `module.exports = ${JSON.stringify(path.basename(filename))};`;
  },
};
```

It's clearly `.cjs`/`.mjs` file was trasformed to it's filename, so I fix this by adding mjs and cjs into `"^(?!.*\\.(mjs|cjs|js|jsx|css|json)$)"`.

Maybe most problems which package is `index.js` were caused by `jest.config.transform`.

**Comment by edmundsj** [comment]
I am encountering the same exact issue on 14.4.3.

**Comment by NicolasBonzini** [comment]
> I just had to update to the latest version: `npm install @testing-library/user-event@latest`
This works for me.Thanks!

**Comment by MuKhAlt** [comment]
> > I just had to update to the latest version: `npm install @testing-library/user-event@latest`
> > This works for me.Thanks!
This solved it for me, thank you!

**Comment by jtomaszewski** [comment]
In my case it's even different, it seems that the only following version is working:

```
import userEvent from "@testing-library/user-event";

const user = userEvent.default.setup();
```

FYI I'm using typescript 5.1.6 with `moduleResolution: "nodenext"` and esm modules.

**Comment by stefannibrasil** [comment]
Here's what worked for me:

```
import React from 'react'
import {render, screen} from '@testing-library/react'
import userEvent from "@testing-library/user-event"
import {FavoriteNumber} from '../favorite-number'

describe('when the number input is invalid', () => {
  test('displays an error message', () => {
   // no setup needed
    render(<FavoriteNumber />)
    const input = screen.getByLabelText(/favorite number/i)

    userEvent.type(input, '10') // <----- calling userEvent.type()

    expect(screen.getByRole('alert')).toHaveTextContent(
      /the number is invalid/i,
    )
  })
})
```

These are my dependencies:

```
"dependencies": {
    "@reach/router": "^1.3.4",
    "@testing-library/dom": "^7.28.1",
    "@testing-library/jest-dom": "^5.11.6",
    "@testing-library/react": "^11.2.2",
    "@testing-library/react-hooks": "^3.4.2",
    "@testing-library/user-event": "^12.4.0",
    "history": "^5.0.0",
    "jest": "^26.6.3",
    "jest-axe": "^4.1.0",
    "kcd-scripts": "^7.5.1",
    "msw": "^0.24.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-redux": "^7.2.2",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-test-renderer": "^17.0.1",
    "react-transition-group": "^4.4.1",
    "redux": "^4.0.5",
    "test-data-bot": "^0.8.0",
    "whatwg-fetch": "^3.5.0"
  },
```

**Comment by fayez-nazzal** [comment]
I had a migration from cjs to esm, userEvent started didn't work anymore. A solution worked well for me is to add this to `setupTests.ts`:

```ts
import userEvent from'@testing-library/user-event';

jest.unstable_mockModule('@testing-library/user-event', () => ({
  default: userEvent.default,
}));
```

Then it worked normally without any more changes.

**Comment by hardingjam** [comment]
> In my case it's even different, it seems that the only following version is working:
> 
> ```
> import userEvent from "@testing-library/user-event";
> 
> const user = userEvent.default.setup();
> ```
> 
> FYI I'm using typescript 5.1.6 with `moduleResolution: "nodenext"` and esm modules.

I was able to solve this problem by updating tsconfig.json

I had used @sveltejs/package to create my app, which by default had the following settings:

```
		"module": "NodeNext",
		"moduleResolution": "NodeNext",
```

moduleResolution allows you to "Specify how TypeScript looks up a file from a given module specifier." Changing the above settings to:

```
		"module": "es2015",
		"moduleResolution": "bundler",
```

Solved the problem
