### ISSUE TITLE
Keyboard arrows navigation not causing `input[type=radio]` to change focus

### ISSUE THREAD

**Issue by mwojslaw** [testing-library/user-event#843]
- `@testing-library/user-event` version: 13.5.0

- Testing Framework and version: `jest` -  `v27.4.7`, `@testing-library/jest-dom` - `v5.16.1`,  
  
- DOM Environment: `jsdom` - `v19.0.0`
  

Relevant code or config

```javascript
it('radio and keyboard navigation', async () => {
  render(
    <>
      <input name="test" aria-label="1" type="radio" />
      <input name="test" aria-label="2" type="radio" />
    </>
  );
  userEvent.tab();
  
  // Here we're fine
  expect(screen.getByLabelText('1')).toHaveFocus();
  
  userEvent.keyboard('{arrowdown}');
  
  // Here we're not
  expect(screen.getByLabelText('2')).toHaveFocus();
});
```

What you did:

Trigger keyboard navigation on input type radio.

What happened:

- Focus is not changing accordingly. 
- `onchange` event is not triggered as well.

**Comment by a7sc11u** [comment]
Hey @mwojslaw, I'm having the exact same issue and ran out of threads to follow. Did you manage to work around it somehow?

**Comment by mwojslaw** [comment]
Not really, I skipped the test for now

**Comment by kboedges** [comment]
Having this issue as well, thought `userEvent.tab()` gives focus to elements just as expected.

**Comment by kboedges** [comment]
What do you mean by default behavior?

**Comment by ph-fritsche** [comment]
@kboedges 
When a [trusted](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted) event is dispatched as result of a user interaction and no event handler [prevents it](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault), the browser implements default behavior for some events, e.g. inserting a character into the DOM at the cursor/selection on a `keypress`.
These events can not be dispatched programmatically, so this library dispatches look-alike events and implements the default behavior a browser usually implements on the trusted equivalent.
For `keydown` events for arrow keys the default behavior on radio buttons - changing focus in the radio group - is not yet implemented.

**Comment by JRJurman** [comment]
@ph-fritsche can you clarify - is this a change that is required in `user-event` and not `jsdom`? Can you point to examples in this repository where additional behaviors (such as changing focus) are implemented for a specific component? I'd be potentially interested in making a PR if there was a clear example of how this is done in similar places.

**Comment by ph-fritsche** [comment]
@JRJurman Default behavior on events is reimplemented in https://github.com/testing-library/user-event/tree/main/src/event/behavior
Focus can also be changed per pointer not being the result of an event - see https://github.com/testing-library/user-event/blob/ee062e762f9ac185d982dbf990387e97e05b3c9d/src/pointer/pointerPress.ts#L254-L327
