### ISSUE TITLE
Events ignore disabled property in fieldset

### ISSUE THREAD

**Issue by markwoon** [testing-library/user-event#844]
- `@testing-library/user-event` version: 13.5.0
- Testing Framework and version: jest 27.4.7
- DOM Environment: jsdom (version unknown)
  
- node version: 16.13.2

What you did:  test input checkbox in a disabled fieldset

What happened: checkbox is modified even though fieldset is disabled

Reproduction repository: https://codesandbox.io/s/busy-sky-u1thc

It works in the browser, but fails when tested with testing-library. 

Testing-library understands that the checkbox is disabled, but userEvent appears to ignore it.

It looks like #96 resolved it for disabled checkboxes but didn't take fieldsets into account.

**Comment by ph-fritsche** [comment]
Thanks for the report.

I fixed the reproduction to actually showcase the problem in browser and test:
https://codesandbox.io/s/jolly-keldysh-fidi9?file=/src/App.test.js

A fix should be applied here:
https://github.com/testing-library/user-event/blob/beta/src/utils/misc/isDisabled.ts
`element.closest(':disabled') === element` works in the browser but not in Jsdom.

**Comment by ph-fritsche** [comment]
@all-contributors add @markwoon bug
