### ISSUE TITLE
Discrepancies when using `Alt` and `Control` in keyboard tests

### ISSUE THREAD

**Issue by jon301** [testing-library/user-event#845]
- `@testing-library/user-event` version: 14.0.0-beta.8
- `jest` version: 27.4.7

What you did:

Trying to use `user-event@14.0.0-beta.8` to simulate a "select all" keyboard behavior.
i.e. In my case, any special key (control, meta, alt, shift) + any other key is considered "select all"

What happened:

<img width="606" alt="CleanShot 2022-01-28 at 08 52 28@2x" src="https://user-images.githubusercontent.com/122108/151508233-fcc25fe6-b2b0-4935-ac54-a5a09385dc11.png">

Reproduction repository:

https://codesandbox.io/s/wispy-bird-d2d1j?file=/src/App.test.tsx

Problem description:

`Alt` and `Control` does not seem to behave like `Shift` and `Meta`

**Comment by ph-fritsche** [comment]
The browser does not dispatch any `keypress` event while `Control` or `Alt` is pressed.
Therefore `onKeyPress` not being called is expected.

For `Meta` the behavior seem to be inconsistent between different browsers and operating systems.
Therefore we currently don't implement any special behavior for this.

**Comment by jon301** [comment]
Thanks for your reply
I've done some manual tests, and it seems `Shift` does not even dispatch a `keypress` either in the browser. Not sure why the test passes 🤔

Anyway, I've used `onKeyUp` and it works better 👍 Thanks!

**Comment by jon301** [comment]
Also, thank you for this wonderful library and congrats for this release ❤️
I've not been able to test this specific use case with the previous version and now it's pretty flawless 🙏

**Comment by ph-fritsche** [comment]
> it seems `Shift` does not even dispatch a `keypress` either in the browser. Not sure why the test passes thinking

The `a` in `{Shift>}a` triggers the `keypress`. It wouldn't in `{Control>}{Shift>}a`.
