### ISSUE TITLE
SyntaxError: Named export 'createEvent' not found

### ISSUE THREAD

**Issue by paparent** [testing-library/user-event#853]
- `@testing-library/user-event` version: 14.0.0-beta.11
- Testing Framework and version: `@testing-library/vue` version: 6.5.1, `vitest` version 0.3.5
- DOM Environment: `jsdom` version 19.0.0

Hi!

I tried to use migrate my test to `user-event` instead of the `fireEvent`  and I get the following message when I run the test:

```
SyntaxError: Named export 'createEvent' not found. The requested module '@testing-library/dom' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@testing-library/dom';
const { createEvent: createEventBase } = pkg;
```

**Comment by ph-fritsche** [comment]
Could you create a reproduction example please?

We need to make sure this is not a misconfiguration in your environment.
The import works just fine in node locally and on Stackblitz:
https://stackblitz.com/edit/node-ndptdu?file=index.mjs

**Comment by paparent** [comment]
@ph-fritsche  sure! here it is: https://github.com/paparent/reproductions/tree/main/vue-test-user-event

While installing I got this too:

```
❯ pnpm add -D @testing-library/vue @testing-library/user-event@^14.0.0-beta
Packages: +29
+++++++++++++++++++++++++++++
Progress: resolved 233, reused 202, downloaded 12, added 29, done

devDependencies:
+ @testing-library/user-event 14.0.0-beta.11
+ @testing-library/vue 6.5.1

 WARN  Issues with peer dependencies found
.
├─┬ @testing-library/vue
│ └── ✕ missing peer @vue/compiler-sfc@">= 3"
└─┬ @testing-library/user-event
  └── ✕ missing peer @testing-library/dom@>=7.21.4
```

**Comment by dholde** [comment]
Same issue here using typescript with versions

- `@testing-library/user-event` 14.2.1
- `@testing-library/vue` 6.4.2
- `vitest` 0.9.4
- `vite` 2.9.9
- `jsdom` 19.0.0

**Comment by ph-fritsche** [comment]
> https://github.com/paparent/reproductions/tree/main/vue-test-user-event

On: mcr.microsoft.com/vscode/devcontainers/typescript-node:0-16
```
npm i -g pnpm
pnpm i
pnpm test:unit
```

No error. This looks like an issue with the environment.

> ```
>  WARN  Issues with peer dependencies found
> .
> ├─┬ @testing-library/vue
> │ └── ✕ missing peer @vue/compiler-sfc@">= 3"
> └─┬ @testing-library/user-event
>   └── ✕ missing peer @testing-library/dom@>=7.21.4
> ```

`@testing-library/user-event` relies on `@testing-library/dom` which is installed as dependency of `@testing-library/vue`.

**Comment by paparent** [comment]
@ph-fritsche  I just upgraded the dependencies of the project and now everything works!

Thanks!
