### ISSUE TITLE
Upgrading from 13.5.0 to 14.0.0-beta.11 results in userEvent.click failure

### ISSUE THREAD

**Issue by BillWadley** [testing-library/user-event#864]
- `@testing-library/user-event` version: ^14.0.0-beta.11

- Testing Framework and version: @testing-library/react: ^12.1.3
  
- DOM Environment: testing-library/jest-dom: ^5.16.2
   node v16.13.2 via "CI=true npm test", npm v8.1.2

I have created a new create-react-app and have only added the TestOne.test.js file.

package.json:
```json
{
  "name": "event-test-1",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.0",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@testing-library/react": "^12.1.3",
    "@testing-library/user-event": "^14.0.0-beta.11"
  }
}
```

src/TestOne.test.js (straight from the [docs](https://testing-library.com/docs/ecosystem-user-event/#clickelement-eventinit-options))
```javascript
import React from 'react'
import {render, screen} from '@testing-library/react'
import userEvent from '@testing-library/user-event'

test('click', () => {
  render(
    <div>
      <label htmlFor="checkbox">Check</label>
      <input id="checkbox" type="checkbox" />
    </div>,
  )

  userEvent.click(screen.getByText('Check'))
  expect(screen.getByLabelText('Check')).toBeChecked()
})
```

I ran the command:
```
CI=true npm test
```

and received this error:

```
> event-test-1@0.1.0 test
> react-scripts test

FAIL src/TestOne.test.js
  ● click

    expect(element).toBeChecked()

    Received element is not checked:
      <input id="checkbox" type="checkbox" />

      13 |
      14 |   userEvent.click(screen.getByText('Check'))
    > 15 |   expect(screen.getByLabelText('Check')).toBeChecked()
         |                                          ^
      16 | })
      17 |

      at Object.<anonymous> (src/TestOne.test.js:15:42)

PASS src/App.test.js

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        1.009 s
Ran all test suites.
```

The userEvent.click method is not functioning.

Suggested solution:

If I edit my package.json file and change
```
"@testing-library/user-event": "^14.0.0-beta"
```
to
```
"@testing-library/user-event": "^13.5.0"
```

then run

```
npm update; CI=true npm test
```

I get this result:

```
> event-test-1@0.1.0 test
> react-scripts test

PASS src/TestOne.test.js
PASS src/App.test.js

Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        1.009 s
Ran all test suites.
```

I changed the library version from "^13.5.0" to "14.0.0-**alpha**.1" and received the error again.

Thank you!

**Comment by ph-fritsche** [comment]
All APIs in version 14 are asynchronous. You should `await` it.

```jsx
test('click', async () => {
    render(
        <div>
            <label htmlFor="checkbox">Check</label>
            <input id="checkbox" type="checkbox" />
        </div>,
    )

    await userEvent.click(screen.getByText('Check'))
    expect(screen.getByLabelText('Check')).toBeChecked()
})
```

Does this fix the problem for you?

**Comment by SaranyaSKumar226** [comment]
Hi, I am using user-event V14.4.3 and made all user action related tests as asynchronous  by adding the async and await. The tests are running successfully individually. But if I run all test suits together then it is throwing "Network Error" intermittently for some test script as below. I am not making any axios call in the related area.

Network Error
      at createError (node_modules/axios/lib/core/createError.js:16:15)
      at XMLHttpRequest.handleError (node_modules/axios/lib/adapters/xhr.js:99:14)
      at XMLHttpRequest.invokeTheCallbackFunction (node_modules/jsdom/lib/jsdom/living/generated/EventHandlerNonNull.js:18:28)
      at XMLHttpRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:35:32)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at XMLHttpRequestImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
      at requestErrorSteps (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:131:3)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:60:3)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
      at ClientRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14) 

My config is :
"@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^14.4.3",

Anyone please help me to resolve this issue.

**Comment by Illutax** [comment]
Hint for fellow strugglers: when using user-event in **Angular** try using fakeAsync *without* async and then call tick() after functions which should be awaited.

```ts
import { discardPeriodicTasks, fakeAsync, TestBed, tick } from '@angular/core/testing';
import { MockRender } from 'ng-mocks';

  it('should filter search results', fakeAsync(() => {
    const fixture = MockRender(AppComponent);

    const input = screen.getByLabelText('search');
    userEvent.type(input, '1');
    tick();
    fixture.detectChanges();

    const options = screen.getAllByRole('option');

    expect(options).toHaveLength(1);
    expect(options[0]).toHaveTextContent('TEST-1 Entry 1');
    discardPeriodicTasks();
  }));

```

And sometimes you have to call fixture.detectChanges() when you want your UI to react to the changes.
