### ISSUE TITLE
Published documentation is for a beta release, not a current release

### ISSUE THREAD

**Issue by ThisIsMissEm** [testing-library/user-event#865]
- `@testing-library/user-event` version: 13.x

- Testing Framework and version: n/a
  
- DOM Environment:
  

What you did:

I went to read the documentation whilst trying to improve some tests, and started receiving errors about `userEvent.setup` not being defined. 

What happened:

I was confused, as the docs said this was a thing. I then realised that it's not actually a feature of 13.x or 12.x, but actually of the 14.x beta.

Problem description:

Documentation is for an beta version of the library, not the current stable version.

Suggested solution:

Publish the stable documentation at https://testing-library.com/docs/user-event/ and use something like Vercel for publishing the preview documentation on branches or tags.

**Comment by ph-fritsche** [comment]
The introductory paragraphs of https://testing-library.com/docs/user-event/intro/:
> [`user-event`](https://github.com/testing-library/user-event) is a companion library for Testing Library that simulates user interactions by
dispatching the events that would happen if the interaction took place in a browser.
> > These docs describe `user-event@14.0.0-beta`.
This is still a pre-release and might be subject to breaking changes
if they should be deemed necessary in the light of feedback we receive for this version.
All planned breaking changes are already implemented though.  
If you are starting or actively working on a project,
we recommend to use this pre-release, as it includes important bug fixes and new features.  
You can find the docs for `user-event@13.5.0` [here](../ecosystem-user-event.mdx).
