### ISSUE TITLE
Link https://github.com/testing-library/user-event/blob/main/README.md#keyboardtext-options is broken

### ISSUE THREAD

**Issue by joshunger** [testing-library/user-event#876]
### Reproduction example

N/A

### Prerequisites

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### User-event version

13.5.0

### Environment

Testing Library framework: 

JS framework: 

Test environment: 

DOM implementation: 

### Additional context

The link specified on https://github.com/testing-library/user-event/blob/e2a5f434b6e8b0ec0badddec52b54957b6f3320a/src/utils/keyDef/readNextDescriptor.ts#L136 doesn't work for me. I was going to submit a PR but I don't know the correct URL?

**Comment by ph-fritsche** [comment]
The input format is described in 
https://testing-library.com/docs/user-event/keyboard for `keyboard()`
and
https://testing-library.com/docs/user-event/pointer#pressing-a-button-or-touching-the-screen for `pointer()`.

**Comment by joshunger** [comment]
https://github.com/testing-library/user-event/pull/877

**Comment by ph-fritsche** [comment]
@all-contributors add @joshunger bug
