### ISSUE TITLE
user-event unable to clear or type in beta 13

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [testing-library/user-event#878]
- `@testing-library/dom` version: 8.11.3
- Testing Framework and version: jest@27  @testing-library/user-event@14.0.0-beta.13
- DOM Environment: jsdom

### Relevant code or config:

```js
const field = getAllByTestId(<testid>);
await userEvent.clear(field);
// field is not clear
await userEvent.type(field, 'dummyText');
// field has still its initial value
```

### What you did:

Loaded a form with initial values and trying to clear the field before typing in it gets not cleared and I also cannot input anything

### What happened:

Test failed because value of the field was not as expected

**Comment by andrealeardini** [comment]
I have the same problem. It seems that userEvent works with a different dom.
https://codesandbox.io/s/jest-dom-userevent-with-static-html-ucwwbk?file=/test/index.spec.js

**Comment by ph-fritsche** [comment]
> I have the same problem. It seems that userEvent works with a different dom. https://codesandbox.io/s/jest-dom-userevent-with-static-html-ucwwbk?file=/test/index.spec.js

`<input/>` does not have `textContent`. Works as expected
https://codesandbox.io/s/jest-dom-userevent-with-static-html-forked-8fl70t

**Comment by ph-fritsche** [comment]
> ```js
> const field = getAllByTestId(<testid>);
> await userEvent.clear(field);
> ```

`userEvent.clear` expects an `Element` as first parameter. You provide an `Array`.

**Comment by sschneider-ihre-pvs** [comment]
here you go updated the example

**Comment by andrealeardini** [comment]
Thanks, I spent a lot of time figuring out where I was wrong, I thought I didn't configure it right and I was finally testing the wrong property! I will take this into account for the next tests.

**Comment by ph-fritsche** [comment]
> here you go updated the example

@sschneider-ihre-pvs 
The issue still doesn't include a reproduction example. Please have a look at our [bug report template](https://github.com/testing-library/user-event/issues/new?assignees=&labels=needs+assessment%2Cbug&template=bug_report.yml).
