### ISSUE TITLE
userEvent.click does not wait for dispatch event

### ISSUE THREAD

**Issue by Gigiz** [testing-library/user-event#899]
### Reproduction example

https://codesandbox.io/s/holy-platform-ec8sjd

### Prerequisites

After updating to the latest version, I have seen fail all test that use the `userEvent.click` method

### Expected behavior

This is the same example where I used the previous version of `user-event` library [codesandbox](https://codesandbox.io/s/angry-ramanujan-ljgkmv)

It was not necessary to use the `waitFor` or `fireEvent`

### Actual behavior

Now this test fails.
```js
 userEvent.click(leftArrowIcon)
 expect(onPageChange).toHaveBeenCalledTimes(1))
```

If I use `fireEvent.click` instead, the test passes. Also if I use `waitFor(() => expect())`

### User-event version

14.0.3

**Comment by ph-fritsche** [comment]
Fixed the test: https://codesandbox.io/s/blazing-hill-s1tvbf?file=/src/Button.test.js

See https://github.com/testing-library/user-event/releases/tag/v14.0.0
> ### ⚠ BREAKING CHANGES
> * **APIs always return a Promise.**

I recommend [@typescript-eslint/no-floating-promises`](https://typescript-eslint.io/rules/no-floating-promises).

Also see https://testing-library.com/docs/user-event/intro/#writing-tests-with-userevent

**Comment by Gigiz** [comment]
Thanks a lot!!! 👯
