### ISSUE TITLE
TypeScript: Incorrect type for `userEvent.click` parameters

### ISSUE THREAD

**Issue by Aerophite** [testing-library/user-event#900]
### Reproduction example

https://codesandbox.io/s/hardcore-hofstadter-esj1lm?file=/src/App.test.tsx

### Prerequisites

1. Have an application up and running using `testing-libary/user-event`
2. Try to click on an element with the meta key pressed
    2a. Using the response from `userEvent.setup() 

    ```
    render(<App />);
    const user = userEvent.setup();
    await user.click(screen.getByRole('textbox'), { keyboardState: { modifiers: { Meta: true } } });
    ```

    2b. Using `userEvent.click` directly

    ```
    render(<App />);
    await userEvent.click(screen.getByRole('textbox'), { keyboardState: { modifiers: { Meta: true } } });
    ```

### Expected behavior

In both scenarios, I should be able to send an optional `options` parameter that ultimately has a way to set any keyboard state modifiers that I _want_ set.

### Actual behavior

For 2a, I get a typing error saying there isn't even an options parameter on `user.click`
![image](https://user-images.githubusercontent.com/6826088/161315467-f41b7085-a6d5-4cc9-8175-f91cb898d608.png)

For 2b, I get a typing error saying that I have to send _every_ modifier instead of just the `Meta` one. I shouldn't have to send every modifier value just because I want to set one of them to `true`.
![image](https://user-images.githubusercontent.com/6826088/161315729-d50b8592-4e29-4baf-8e80-d5e4589b3551.png)

### User-event version

14.0.4

### Environment

Testing Library framework: `@testing-library/react@12.1.4`
JS framework: `react@17.0.2`
Test environment: `jest@27.4.5`
DOM implementation: `jsdom@16.7.0`

### Additional context

I am updating from v13 to v14 and this is something I noticed. If you ignore the TypeScript errors, the Meta key _is_ pressed and I haven't noticed any nasty side-effects yet so I don't think any functionality code actually had to change.

**Comment by ph-fritsche** [comment]
https://github.com/testing-library/user-event/blob/6d36828e22d0ab65d94178daadb131ec92bae676/src/keyboard/types.ts#L1-L4

This state is internal and we don't intend to support creating your own.
You should manipulate the state as described in https://testing-library.com/docs/user-event/setup#starting-a-session-per-setup .

**Comment by Aerophite** [comment]
Thank you! I did not see that.
