### ISSUE TITLE
userEvent.keyboard throws TypeError when using arrow keys

### ISSUE THREAD

**Issue by mattcarlotta** [testing-library/user-event#901]
- `@testing-library/dom` version:  8.12.0
- `@testing-library/user-event` version: 14.04
- `@testing-library/react` version: 13.0.0
- Testing Framework and version: `jest@27.5.1`
- DOM Environment: `@testing-library/jest-dom@5.16.3`
- Framework: `react/react-dom@18.0.0`
- Node version: 16.14.2

### Relevant code or config:

[jest.config.js](https://github.com/mattcarlotta/portfolio/blob/testing/jest.config.js)
[setupTest.ts](https://github.com/mattcarlotta/portfolio/blob/testing/src/utils/setupTests.ts)

### What you did:

Attempting to test user [arrow key](https://github.com/mattcarlotta/portfolio/blob/testing/src/components/Layout/ModalDialog/index.tsx#L116-L132) navigation within a modal: [ArrowRight](https://github.com/mattcarlotta/portfolio/blob/testing/src/components/Layout/ModalDialog/__tests__/ModalDialog.test.tsx#L149-L165) and [ArrowLeft](https://github.com/mattcarlotta/portfolio/blob/testing/src/components/Layout/ModalDialog/__tests__/ModalDialog.test.tsx#L167-L183)

### What happened:

TypeErrors:
[ArrowRight](https://github.com/mattcarlotta/portfolio/runs/5806804305?check_suite_focus=true#step:9:14)
[ArrowLeft](https://github.com/mattcarlotta/portfolio/runs/5806804305?check_suite_focus=true#step:9:42)

### Reproduction:

[testing branch (failing)](https://github.com/mattcarlotta/portfolio/tree/testing)

### Problem description:

Appears that arrow keys aren't mapped properly. Downgrading to [React 17.0.2](https://github.com/mattcarlotta/portfolio/blob/development/package.json#L35-L36), [Testing Library User Event 13.0.5](https://github.com/mattcarlotta/portfolio/blob/development/package.json#L45) and [Testing Library React 12.1.4](https://github.com/mattcarlotta/portfolio/blob/development/package.json#L44) works as [expected](https://github.com/mattcarlotta/portfolio/runs/5806617393?check_suite_focus=true#step:9:7) on my [development branch](https://github.com/mattcarlotta/portfolio/tree/development).

**Comment by ph-fritsche** [comment]
The error is caused by a `Selection` with `rangeCount === 0`.
Any interaction that moves focus outside of elements with own selection context (`<input>`, `<textarea>`) sets the `Selection` to one `Range`. So per user interaction there is no focus on such an Element without a Selection.
We probably should still guard against this [here](https://github.com/testing-library/user-event/blob/6d36828e22d0ab65d94178daadb131ec92bae676/src/utils/focus/selection.ts#L221-L227).

If you replace [your `fireEvent.click`](https://github.com/mattcarlotta/portfolio/blob/7311c4a71276527ddd45b0451197827cd120ef13/src/components/Layout/ModalDialog/__tests__/ModalDialog.test.tsx#L152) with `await user.click` the error will be gone.

**Comment by pascalduez** [comment]
Hi,

the issue can be reproduced simply by:
```jsx
const user = userEvent.setup();

render(
  <>
    <label htmlFor="one">One</label>
    <input type="radio" name="test" id="one" />
    <label htmlFor="two">Two</label>
    <input type="radio" name="test" id="two" />{' '}
  </>
);

// TypeError: Cannot read property 'nodeType' of null
await user.keyboard('[ArrowRight]');
```

```json
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^12.1.4",
    "@testing-library/user-event": "^14.1.1",
    "jest": "^28.1.0",
    "jest-environment-jsdom": "^28.1.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
```

Real world test
```jsx
const user = userEvent.setup();

render(
  <>
    <label htmlFor="one">One</label>
    <input type="radio" name="test" id="one" />
    <label htmlFor="two">Two</label>
    <input type="radio" name="test" id="two" />{' '}
  </>
);

await user.tab();

expect(screen.getByRole('radio', { name: 'One' })).toHaveFocus();
expect(screen.getByRole('radio', { name: 'One' })).not.toBeChecked();

await user.keyboard('[Space]');

expect(screen.getByRole('radio', { name: 'One' })).toBeChecked();

// ¯\_(ツ)_/¯
// TypeError: Cannot read property 'nodeType' of null
await user.keyboard('[ArrowRight]');

expect(screen.getByRole('radio', { name: 'Two' })).toHaveFocus();
expect(screen.getByRole('radio', { name: 'Two' })).toBeChecked();
```

**Comment by ph-fritsche** [comment]
@all-contributors add @mattcarlotta bug
