### ISSUE TITLE
clear userEvent fails on textfield with defined maxLength which is filled max length content after upgrade from v13 to v14.0.4

### ISSUE THREAD

**Issue by SchmitzChristian** [testing-library/user-event#908]
### Reproduction example

https://codesandbox.io/s/userevent-fail-if-text-field-content-is-max-length-at-clear-event-rhi8si?file=/index.html

### Prerequisites

1. define a textfield with max length
2. fill it with max length content
3. try to clear it in test -> fails on clear, content is still in the textfield

### Expected behavior

userEvent also works on textfields with max length content

### Actual behavior

clear userEvent fails on textfields with filled max length content

### User-event version

14.0.4

**Comment by ph-fritsche** [comment]
@all-contributors add @SchmitzChristian bug
