### ISSUE TITLE
userEvent.type - issue when using {Alt>}{Enter}{/Alt}

### ISSUE THREAD

**Issue by xDisfigure** [testing-library/user-event#912]
### Reproduction example

https://codesandbox.io/s/happy-ritchie-tq2fbg?file=/src/App.test.tsx

edit: https://codesandbox.io/s/clever-sea-ocux0n?file=/src/App.js

### Prerequisites

Have a textarea which handles new line by holding "alt" and pressing "enter"

### Expected behavior

In the test, for the second scenario (alt + enter) I would expect to see the new line added to the textarea value.

```ts
const sentence1 = 'here im the first sentence.';
const sentence2 = 'i should be after a new line.';
await userEvent.type(input, `${sentence1}{Alt>}{Enter}{/Alt}${sentence2}`)
expect(input).toHaveValue(`${sentence1}\n${sentence2}`) // it should not fail
```

Expected text result
```
here im the first sentence.
i should be after a new line.
```

### Actual behavior

To make a newline inside the textarea you should be able to manually :

1. Hold "shift" and then press "enter"
2. Hold "alt" and then press "enter"

Now if you run the test suites you can see that the test asserting the second scenario (alt+enter) will fail.

```ts
const sentence1 = 'here im the first sentence.';
const sentence2 = 'i should be after a new line.';
await userEvent.type(input, `${sentence1}{Alt>}{Enter}{/Alt}${sentence2}`)
expect(input).toHaveValue(`${sentence1}\n${sentence2}`) // this fails
```

The new line is not appended. Im getting the following text as the textarea value: 
```
here im the first sentence.i should be after a new line.
```

### User-event version

14.0.4

### Environment

Testing Library framework: `@testing-library/react@13.0.0`

JS framework: `react@18.0.0`
Test environment:  `jest@27.5.1`
DOM implementation: `jsdom@16.0.7`

### Additional context

The test was working on user-event@13.x.x, it seems to fail since we migrate to the 14.0.4

**Comment by ph-fritsche** [comment]
In which browser and OS does `[Alt]+[Enter]` produce a character input?

**Comment by xDisfigure** [comment]
> In which browser and OS does `[Alt]+[Enter]` produce a character input?

Natively no one, we mimic slack behavior on this. 

If you check the codesandbox you will see that the textarea have a custom onChange + a custom onKeyDown.
The problem is not in the browser but inside the test. I dont get your question

**Comment by ph-fritsche** [comment]
Sorry, I misunderstood your report.

The codesandbox fails to install some dependency. I've created a new one:
https://codesandbox.io/s/clever-sea-ocux0n?file=/src/App.js

This looks to be a problem with the UI selection not being reset when the value is updated.

**Comment by ph-fritsche** [comment]
@all-contributors add @xDisfigure bug

**Comment by xDisfigure** [comment]
> 
No problemo! :) 

Sorry for the inconvenience with the codesandbox it should have worked. 
Anyway, thanks a lot for creating a new one and taking a look at this issue, really appreciated 🙏
