### ISSUE TITLE
Upload does not work for non accepted files types

### ISSUE THREAD

**Issue by karolis-cekaitis** [testing-library/user-event#913]
### Reproduction example

https://codesandbox.io/s/compassionate-thunder-7dgq11?file=/src/App.test.js

### Prerequisites

1. render  `<input type="file" accept=".xlsx" onChange={handleFileChange} />`
2. try uploading file that is not one of the accepted types

### Expected behavior

`onChange` is called

### Actual behavior

`onChange` is not called

### User-event version

14.0.4

### Additional context

It's still easy to bypass browsers accepted file types by user. So I want to test if error returned by back-end (mocked with MSW)  is shown.
![image](https://user-images.githubusercontent.com/89905443/162394588-f62b1e05-13f8-4ba5-b97e-71b9260bea14.png)

found this #421 where people seemed to agree that allowing uploading all types is way to go.

And this used to work with v13: https://codesandbox.io/s/nameless-platform-qnw290?file=/src/App.test.js

Seems upload [used to have options](https://github.com/testing-library/user-event/blob/5d946d51d643f0ef7e7730fa527b7ca96e330907/src/upload.ts#L20), where `applyAccept` was defaulting  to `false`. In changelog it's only mentioned that options was removed, but not that default has changed (and contradicts browser behavior)

**Comment by karolis-cekaitis** [comment]
Ok, found solution: `.setup({applyAccept: false})` https://codesandbox.io/s/priceless-night-g054or?file=/src/App.test.js:391-419

I think this could have been mentioned in changelog. And say it was moved to setup instead saying that this was removed.

**Comment by ph-fritsche** [comment]
Thanks for the report.

Change happened here: [#790 / 1d52ee34](https://github.com/testing-library/user-event/pull/790/commits/1d52ee34b93f8b4cb7cc666c16ab32b77e1b90de#diff-debe4a612b76758f661a09262c5f26971885e3843b03583c1b5babff1cce0767)
Changing the default was not intended. I'll add it to the changelog.

**Comment by ph-fritsche** [comment]
@all-contributors add @karolis-cekaitis bug,docs

**Comment by ph-fritsche** [comment]
https://github.com/all-contributors add @karolis-cekaitis bug,doc

**Comment by ph-fritsche** [comment]
@all-contributors add @karolis-cekaitis bug,doc

**Comment by ph-fritsche** [comment]
https://github.com/all-contributors add @karolis-cekaitis bug, doc

**Comment by ph-fritsche** [comment]
@all-contributors add @karolis-cekaitis bug, doc

**Comment by karolis-cekaitis** [comment]
> Thanks for the report.
> 
> Change happened here: [#790 / 1d52ee34](https://github.com/testing-library/user-event/pull/790/commits/1d52ee34b93f8b4cb7cc666c16ab32b77e1b90de#diff-debe4a612b76758f661a09262c5f26971885e3843b03583c1b5babff1cce0767) Changing the default was not intended. I'll add it to the changelog.

If changing default was not intended, maybe it should be reset to false? It makes more sense as that's how browser threats it. It does not do filtering of what user selected.

**Comment by ph-fritsche** [comment]
Intended or not. Reverting it would be a breaking change.

It's not *inherently wrong* (aka a bug) to apply accept. It's still the default behavior of file selectors to show only those files matching the `accept` attribute.
In (most?) browsers the user can just override the selection to "any file", but the user also can manipulate browser behavior in many other ways. So...

It's not worth a major version bump.
