### ISSUE TITLE
Cannot use clear() on editable custom elements in v14

### ISSUE THREAD

**Issue by MattSidor** [testing-library/user-event#925]
### Reproduction example

https://github.com/MattSidor/user-event-custom-element

### Prerequisites

1. Render a custom element that allows editable text such as [@polymer/paper-input](https://www.webcomponents.org/element/@polymer/paper-input) (`<paper-input>`)
2. Write a test that invokes [`clear()` utility function](https://testing-library.com/docs/user-event/utility#clear) on custom element

### Expected behavior

`clear()` works on custom elements with editable text without throwing errors, as it did in version 13.

### Actual behavior

Error thrown: `clear() is only supported on editable elements`

### User-event version

14.1.0

### Environment

Testing Library framework: `@testing-library/react@13.0.1`
JS framework: `react@18.0.0`
Test environment: `jest@26.6.0`
DOM implementation: `jsdom@16.7.0`

### Additional context

A solution may be to add a check in [utils/edit/isEditable.ts](https://github.com/testing-library/user-event/blob/f209a6f863c3a5a85388222ed0e52e3c65af6de8/src/utils/edit/isEditable.ts) for editable elements within [`Element.shadowRoot`](https://developer.mozilla.org/en-US/docs/Web/API/Element/shadowRoot).

I could not get tests with custom elements to load correctly in Codesandbox, so please clone the Github repo linked above and run locally.

**Comment by ph-fritsche** [comment]
The element `<paper-input data-testid="paper-input"/>` which you query is not editable.
If you focus it in the browser, the menu items `Select All` and `Delete` are disabled.

**Comment by ph-fritsche** [comment]
The `clear()` API was redesigned. #778 explains the reasoning.

If [the v13 `clear()` API](https://github.com/testing-library/user-event/blob/v13.5.0/src/clear.ts) worked (or better: seemed to work, as the behavior doesn't really make sense in terms of simulating user interaction,) on that element, this was not even intended and the check to throw an error for unsupported elements just failed.

Have you tried supplying an editable element in the shadow DOM ?

**Comment by MattSidor** [comment]
Not yet. I assume that will work if I query within `shadowRoot` for the specific element which is nested in the shadow DOM. That is the workaround I would need to implement in all my tests with `clear()` right now.

If I'm able to call `type()` on the same custom element, and that works, I had assumed `clear()` would also work on it. Was my assumption not realistic?

> the behavior doesn't really make sense in terms of simulating user interaction

Can you please elaborate on this point?

**Comment by ph-fritsche** [comment]
This library promises to simulate user interaction. The behavior of the v13 `clear()` API (see the issue I linked above) can not be performed by a real user. No true confidence is gained by applying it because the API yielding the expected result does not mean that a user can follow that path and reach that result.
