### ISSUE TITLE
userEvent.pointer does not set the button and buttons properties

### ISSUE THREAD

**Issue by alkstal** [testing-library/user-event#926]
### Reproduction example

https://codesandbox.io/s/misty-haze-n45bf4?file=/src/App.js

### Prerequisites

1. `<button>Touch me</button>`
2.
```
document.querySelector('button').addEventListener('pointerup', (e) => {
    console.log(e.button)
})
```
3.
```
await user.pointer({
    tags: '[MouseLeft]',
    target: document.querySelector('button'),
})
```

### Expected behavior

`PointerEvent` sets `event.button` and `event.buttons` to allow us to figure out which button was used.

https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events#determining_button_states

As an example, if the left mouse button was used, the `pointerup` event `event.button` is `0`.

### Actual behavior

The `PointerEvent` created by `userEvent.pointer()` does not assign `event.button` or `event.buttons`, so both are `undefined` in a event handler.

This means event handlers using these properties don't work under test.

### User-event version

14.0.4

### Environment

Testing Library framework: 

JS framework: 

Test environment: 

DOM implementation:

**Comment by ph-fritsche** [comment]
Thanks for the report. :heart: 

We add the `button` to the `PointerEventInit` here:
https://github.com/testing-library/user-event/blob/ef826a43f77ff69670e50045bd29a0327c2d48be/src/pointer/firePointerEvents.ts#L35

This is an issue with the environment not implementing `PointerEvent`. This results in the event constructor being just `Event` which discards the properties from `MouseEventInit`/`PointerEventInit`.
https://github.com/testing-library/dom-testing-library/blob/11fc7731e5081fd0994bf2da84d688fdb592eda7/src/events.js#L50

We already apply a workaround for coordinates and other properties here and should maybe add `button` or (partially) replace it with the workaround below:
https://github.com/testing-library/user-event/blob/ef826a43f77ff69670e50045bd29a0327c2d48be/src/event/createEvent.ts#L40-L45

The following workaround fixes the issue:
```js
if (!window.PointerEvent) {
  window.PointerEvent = window.MouseEvent
}
```
https://codesandbox.io/s/dreamy-firefly-xf3zke?file=/src/App.test.js:45-117

**Comment by alkstal** [comment]
Thanks for the explanation and the suggested workaround!

**Comment by ph-fritsche** [comment]
@all-contributors add @alkstal bug
