### ISSUE TITLE
userEvent.type does not fire change event

### ISSUE THREAD

**Issue by vvscode** [testing-library/user-event#930]
### Reproduction example

https://codesandbox.io/s/pensive-rgb-tcxije?file=/src/App.test.js

### Prerequisites

1. Render input and submit for onChange handler
2. type
3. check if handler was called

### Expected behavior

`onChange` event handler should be called

### Actual behavior

`onChange` is not called

### User-event version

14.1.0

### Environment

Testing Library framework: `"@testing-library/react": "13.0.1"`

JS framework: `"react": "18.0.0",`

DOM implementation: 

### Additional context

Related issue: https://github.com/testing-library/user-event/issues/519

P.S. similar case with `.click()`

**Comment by vvscode** [comment]
it doesn't call `onInput` as well

**Comment by vvscode** [comment]
Ok, I missed the update that API become async
we can close

**Comment by erickbelfy** [comment]
Im having the same issue, with a given form:

 <div
                    class="MuiBox-root MuiBox-root-10 makeStyles-formField-8"
                  >
                    <div
                      class="MuiBox-root MuiBox-root-11"
                    >
                      <label
                        class="makeStyles-root-12 makeStyles-root-13 makeStyles-formFieldLabelRoot-9"
                        for="Account name"
                      >
                        Account name
                      </label>
                      <div
                        class="MuiBox-root MuiBox-root-14"
                      >
                        <div
                          class="MuiInputBase-root OSSTextInput-statusPrimary-15 MuiInputBase-fullWidth Mui-focused"
                        >
                          <input
                            aria-describedby="Account name--helperText"
                            autocomplete="off"
                            class="MuiInputBase-input"
                            data-testid="accountNameField"
                            id="Account name"
                            maxlength="255"
                            name="accountName"
                            placeholder="Ex: Acme Inc."
                            type="text"
                            value=""
                          />
                        </div>
                      </div>
                    </div>
doing the following test:

import { render, fireEvent, screen, within, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import React from 'react';

const user = userEvent.setup();
render(getComponent(props));
const accountName = screen.getByTestId('accountNameField');
await user.type(accountName, 'foo');
    await waitFor(() => {
      expect(screen.getByTestId('accountNameField')).toHaveText('foo');
    });
is not working properly even though I'm using the debug utility function to make sure that the node is present, it returns the correct node, but the input is not filled by a value.

I'm currently using userEvent @latest

**Comment by franjpr** [comment]
> Im having the same issue, with a given form:
> 
> ```
>  <div
>                     class="MuiBox-root MuiBox-root-10 makeStyles-formField-8"
>                   >
>                     <div
>                       class="MuiBox-root MuiBox-root-11"
>                     >
>                       <label
>                         class="makeStyles-root-12 makeStyles-root-13 makeStyles-formFieldLabelRoot-9"
>                         for="Account name"
>                       >
>                         Account name
>                       </label>
>                       <div
>                         class="MuiBox-root MuiBox-root-14"
>                       >
>                         <div
>                           class="MuiInputBase-root OSSTextInput-statusPrimary-15 MuiInputBase-fullWidth Mui-focused"
>                         >
>                           <input
>                             aria-describedby="Account name--helperText"
>                             autocomplete="off"
>                             class="MuiInputBase-input"
>                             data-testid="accountNameField"
>                             id="Account name"
>                             maxlength="255"
>                             name="accountName"
>                             placeholder="Ex: Acme Inc."
>                             type="text"
>                             value=""
>                           />
>                         </div>
>                       </div>
>                     </div>
> ```
> 
> doing the following test:
> 
> ```
> import { render, fireEvent, screen, within, waitFor } from '@testing-library/react';
> import userEvent from '@testing-library/user-event';
> import React from 'react';
> 
> const user = userEvent.setup();
> render(getComponent(props));
> const accountName = screen.getByTestId('accountNameField');
> await user.type(accountName, 'foo');
>     await waitFor(() => {
>       expect(screen.getByTestId('accountNameField')).toHaveText('foo');
>     });
> ```
> 
> is not working properly even though I'm using the `debug` utility function to make sure that the node is present, it returns the correct node, but the input is not filled by a value.
> 
> I'm currently using userEvent v14.1.1

I have something similar to this. As far as I know, this does trigger `onInput` event when the "user" types because it simulates the `mouseOver`, `click`, `focusIn` and then `onInput` fires on each keypress but you must have in mind that `onChange` only triggers when the selected element loses focus. So I tried to call `user.click(element.parentElement)` and it did fired `onChange` event then. But I'm not sure if this is the correct way to do it or maybe we need to pass an extra option to the `.type` fn

**Comment by cmolina** [comment]
I have the same problem described by @erickbelfy; only one test behaves like this.

My current workaround is to call `type` twice.
