### ISSUE TITLE
Mock function not getting called when using userEvent.click()

### ISSUE THREAD

**Issue by ishaanb5** [testing-library/user-event#937]
### Reproduction example

https://codesandbox.io/s/autumn-morning-807f7c?file=/src/App.js

### Prerequisites

1. Render a React component with <button> that receives event handler for that button as a prop.
2. Click on the button.

### Expected behavior

the handler function should be called and test for the same should pass

### Actual behavior

The test for checking if the handler function was called is failing.

### User-event version

14.1.1

### Environment

Testing Library framework: @testing-library/react@^13.1.1
JS framework:  react@18.0.0
Was using create-react-app locally but able to replicate in mentioned sandbox as well.

### Additional context

The test passes if the package version is changed from 14.1.1 to 13.5.0

**Comment by ph-fritsche** [comment]
> ## [14.0.0](https://github.com/testing-library/user-event/compare/v13.5.0...v14.0.0) (2022-03-29)
>
> ### ⚠ BREAKING CHANGES
>
> * **APIs always return a Promise.**

https://testing-library.com/docs/user-event/intro/#writing-tests-with-userevent
