### ISSUE TITLE
Unexpected meta key behavior for userEvent.type()

### ISSUE THREAD

**Issue by bvaughn** [testing-library/user-event#939]
### Reproduction example

https://codesandbox.io/s/tender-leavitt-k3tzoy

### Prerequisites

Write an app with a keydown handler like so:
```js
function onKeyDown(event) {
  switch (event.key) {
    case "f":
    case "F":
      if (event.metaKey) {
        // ...
      }
      break;
  }
}
```

Write a test that simulates the user typing CMD+F (for find-in-page):
```js
const input = await findByPlaceholderText("Some placeholder text");
await userEvent.type(input, "{meta}f");
```

### Expected behavior

Documentation says:
> **A note about modifiers:** Modifier keys (`{shift}`, `{ctrl}`, `{alt}`, `{meta}`) will activate their corresponding event modifiers for the duration of type command or until they are closed (via `{/shift}`, `{/ctrl}`, etc.).

I would expect `{meta}f` to trigger to "keydown" events with...
* event.key = "Meta", event.metaKey === true
* event.key = "f", event.metaKey === true

### Actual behavior

I am seeing two "keydown" events but with...
* event.key = "Meta", event.metaKey === true
* event.key = "f", event.metaKey === false

### User-event version

14.1.0

### Environment

Testing Library framework: 

JS framework: 

Test environment: 

DOM implementation: 

### Additional context

Note that the Code Sandboxes I linked to above fails, but the two templates linked from the template also fail (without any modifications) with the following error:
> The provided value is not of type 'Element'.

Hopefully the code I wrote is enough to convey the point. Apologies if I'm misunderstanding something about the API or the expected behavior.

**Comment by bvaughn** [comment]
Just reading through the changelog and noticed the 14.0 release mentioning `{Meta>}`

**Comment by ph-fritsche** [comment]
![image](https://user-images.githubusercontent.com/39068198/164936401-2d0257e3-d598-4d04-99f1-60f066838419.png)

**Comment by bvaughn** [comment]
D'oh! On the one hand it's a little embarrassing that I didn't notice that.

On the other hand, I just ended up there by using the site search feature ("userevent.type" + enter to open the first result). Kind of easy to overlook the header in that case because the page auto-scrolls to the example section midway down.

Either way– all sorted out here. Thanks!
