### ISSUE TITLE
File upload fails in happy-dom

### ISSUE THREAD

**Issue by DGollings** [testing-library/user-event#940]
### Reproduction example

https://codesandbox.io/s/wonderful-shadow-zqehu0

### Prerequisites

Open a new terminal `npx vitest`

### Expected behavior

Test passes

### Actual behavior

Test fails - but edit [vite.config.ts](https://codesandbox.io/s/wonderful-shadow-zqehu0?file=/vite.config.ts) to `jsdom` and it'll pass

### User-event version

14.1.1

### Environment

Testing Library framework: 

JS framework: 

Test environment: 

DOM implementation: 

### Additional context

Not sure if this has anything to do with user-event, but it might be related to https://github.com/testing-library/vue-testing-library/issues/267 ? I seem to run into all kinds of minor/weird issues using this 'stack'

**Comment by ph-fritsche** [comment]
The environment doesn't implement `FileList`. Workaround:
```js
class FileList {
  readonly length: 0;
  readonly item: (index: number) => undefined;
  readonly [Symbol.iterator] = function* next() {};
}
Object.defineProperty(globalThis, "FileList", {
  configurable: true,
  enumerable: false,
  get: () => FileList
});
```

The environment also incorrectly implements `HTMLInputElement.files` as writable property `{ value: [], writable: true, enumerable: true, configurable: true }` on the element. Workaround (after the element is created):
```js
  Object.defineProperty(input, "files", {
    configurable: true,
    enumerable: false,
    get: () => new FileList()
  });
```

This is not a bug with `user-event`, but we might make our implementation more robust for such environments. Let's keep the issue open.

**Comment by DGollings** [comment]
Hi Philipp,

Thanks, can confirm the workarounds work. 

For my education/amusement, what does 'this environment' mean? All of it (Vue 3+Vite+Vitest+happy-dom)? Or specifically `happy-dom`? Because I'd be quite surprised to hear I'm the only person 'uploading' 'files' with happy-dom :)

Either way, thanks

**Comment by ph-fritsche** [comment]
From the `user-event` perspective "the environment" is everything that is neither your component, your test code, nor brought by `user-event`. In your stack it's specifically `happy-dom` that is responsible for implementing the DOM and it doesn't implement `FileList` and `HTMLInputElement.files` correctly.

**Comment by ph-fritsche** [comment]
@all-contributors add @DGollings bug
