### ISSUE TITLE
Pointer events are not triggered correctly in parent elements

### ISSUE THREAD

**Issue by Parnswir** [testing-library/user-event#957]
### Reproduction example

https://codesandbox.io/s/cool-leftpad-3djsvy?file=/README.md

### Prerequisites

1. Render a container element and a child element (`<div id="container"><div id="child">Content</div></div>`)
2. Use `await userEvent.hover(screen.getByText("Content"));` to trigger a `pointerenter` event

### Expected behavior

The container element should also get the pointer event.

### Actual behavior

The container element does not get an event.

### User-event version

14.1.1

### Environment

    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^14.0.0",
    "babel-jest": "^27.4.5",
    "jest": "^28.0.3"

See https://github.com/Parnswir/user-event-14-hover-reproduction for working example with v13.5 (https://github.com/Parnswir/user-event-14-hover-reproduction/commit/9d64c4cc925cbe89bbd0aebc00226f8b578284e0) and broken example with v14 (https://github.com/Parnswir/user-event-14-hover-reproduction/commit/3a24bf0caecb501f96c356a37e216ea1fb1154c0)

### Additional context

Originally discussed in https://github.com/testing-library/user-event/discussions/944

cc: @ph-fritsche

**Comment by ph-fritsche** [comment]
@all-contributors add @Parnswir bug
