### ISSUE TITLE
User events causes timeout when Jest fake timers are active

### ISSUE THREAD

**Issue by wkillerud** [testing-library/user-event#959]
### Reproduction example

https://github.com/wkillerud/wait-setup-repro

### Prerequisites

I wanted to demo that reverting a previous change in `@testing-library/user-event` inside `node_modules` fixes this particular issue. Hope a repo works instead of a CodeSandbox 🙏

To reproduce:

- npm install
- npm test

Jest fails because of a timeout.

- Comment out the call to `userEvent.click()` and see the tests run.
- Uncomment `userEvent.click()`
- Comment out the fake timer and see the test run.

Test passes.

- Uncomment so the fake timer becomes active again
- Comment out the call to `wait()` in setup in node_modules:

```patch
diff --git a/node_modules/@testing-library/user-event/dist/index.cjs b/node_modules/@testing-library/user-event/dist/index.cjs
index f69faf8..a50cb3d 100644
--- a/node_modules/@testing-library/user-event/dist/index.cjs
+++ b/node_modules/@testing-library/user-event/dist/index.cjs
@ -2898,7 +2898,7 @@ function wrapAndBindImpl(instance, impl) {
   function method(...args) {
     setLevelRef(instance[Config], 1 /* Call */);
     return wrapAsync(() => impl.apply(instance, args).then(async (ret) => {
-      await wait(instance[Config]);
+      //await wait(instance[Config]);
       return ret;
     }));
   }
```

Test passes.

### Expected behavior

My expectation is that using fake timers should not have an impact on the user events.

### Actual behavior

Between 14.1.1 and 14.2.0, [a call to `wait` was introduced in setup](https://github.com/testing-library/user-event/commit/6f55feebffcb331f627c8467b856723d90e06896) that made `click()` time out when using Jest fake timers. I suspect this affects every method.

### User-event version

14.2.0

### Environment

Testing Library framework: `@testing-library/react@13.2.0`

JS framework: `react@18.1.0`

Test environment: `jest@28.1.0`

DOM implementation: `jest-environment-jsdom@28.1.0` -> `jsdom@19.0.0`

https://github.com/wkillerud/wait-setup-repro/blob/main/package.json

### Additional context

- [`wait` uses `setTimeout`](https://github.com/testing-library/user-event/blob/ee062e762f9ac185d982dbf990387e97e05b3c9d/src/utils/misc/wait.ts#L9) internally, which Jest probably tampers with when using fake timers. 
- Maybe related to [this commit as well](https://github.com/testing-library/user-event/commit/9913798d1e60755f1bf2e6f3caecf5600a9a7c69#diff-5159b629f57d69cd901579f012c5a9c5733705298be4c382fdfd8348a00114c0)?

**Comment by wkillerud** [comment]
Some more context:

- When I logged the output in setup, delay was set to `0` and not `undefined`. 
- `wait` returns early if `typeof delay !== 'number'`

Maybe `delay: 0` is the source of the bug? Or maybe a fix can be to check if `delay === 0` and then skip `setTimeout` alltogether?

```js
export function wait(config: Config) {
  const delay = config.delay
  if (typeof delay !== 'number') {
    return
  }
  return Promise.all([
    new Promise<void>(resolve => config.delay === 0 ? resolve() : globalThis.setTimeout(() => resolve(), delay)),
    config.advanceTimers(delay),
  ])
}
```

**Comment by ph-fritsche** [comment]
[Delay](https://testing-library.com/docs/user-event/options/#delay)ing the code per default is intentional.

> This moves the next changes at least to the next macro task and allows other (asynchronous) code to run between events.

If you are certain that there are no asynchronous state updates in your components, you can turn this off per `{delay: null}`.

> Using the methods on the instances returned by userEvent.setup() is recommended.

A `setup` method that is called in multiple/all tests and applies defaults ensures the correct setup for your environment and results in readable tests in which subsequent statements continue to act on the same input device state.

```js
import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'

function setup(jsx) {
  return {
    user: userEvent.setup({
      advanceTimers: jest.advanceTimersByTime,
    }),
    ...render(jsx)
  }
}

test('do something', async () => {
  const { user } = setup(<MyComponent/>)

  await user.keyboard('{Shift>}')
  await user.click(screen.getByText("Hello, world!")) // shiftKey: true
 
  expect(screen.getByText('Welcome, stranger!')).toBeVisible()
})
```
