### ISSUE TITLE
Writing to `HTMLSelectElement.value` throws TypeError

### ISSUE THREAD

**Issue by jessharrell** [testing-library/user-event#961]
### Reproduction example

https://github.com/jessharrell/angular13-dropdown-testing

### Prerequisites

1. Render an Angular component with a Select
2. use user-event to select an option
3. failure occurs on destruction of component (which happens by default in angular 13)

### Expected behavior

No exception is thrown.

### Actual behavior

TypeError: 'set' on proxy: trap returned falsish for property 'value'
at DefaultDomRenderer2.setProperty (node_modules/@angular/platform->browser/fesm2020/platform-browser.mjs:642:12)
at BaseAnimationRenderer.setProperty (node_modules/@angular/platform-browser/fesm2020/animations.mjs:292:27)
at SelectControlValueAccessor.setProperty (node_modules/@angular/forms/fesm2020/forms.mjs:49:24)
at SelectControlValueAccessor.writeValue (node_modules/@angular/forms/fesm2020/forms.mjs:6065:14)
at NgSelectOption.ngOnDestroy (node_modules/@angular/forms/fesm2020/forms.mjs:6155:26)

### User-event version

14.2.0

### Environment

Testing Library framework: testing-library/angular@11.0.4,
JS framework: Angular@13.3.8
Test environment: jest@28.1.0
DOM implementation: Jsdom

### Additional context

Initially filed issue with angular forms. They believe this exception is due to the way user-event is setting the value property on the HTMLSelectElement. Please see [issue](https://github.com/angular/angular/issues/46071) for more details.

**Comment by ph-fritsche** [comment]
Thanks for reporting this. :heart: 

The property descriptor has a setter. So a write on the property should not fail.

Adding any setter for `value` on the `HTMLSelectElement` results in that error. This is specific to Jsdom and the object it returns for `document.createElement('select')`.
Note that the same does neither fail in the browser nor on other elements in Jsdom.

Also that setter causing the error is never executed. So nothing that could be fixed there.
https://codesandbox.io/s/elastic-leaf-v8mxg3?file=/src/App.test.js

I guess the object we're dealing with is a `Proxy` that Jsdom returns for `document.createElement('select')` and the error happens in the handlers on that Proxy.
You should raise this issue with Jsdom. They probably can tell if this is a bug or if they deliberately prevent adding a `value` setter on this specific element.

**Comment by dzonatan** [comment]
Are there any known workarounds for this?

**Comment by dzonatan** [comment]
thank you @ph-fritsche 🙏🏻

**Comment by ph-fritsche** [comment]
@all-contributors add @jessharrell bug
