### ISSUE TITLE
`userEvent #type` doesn't seem to fire onKeyUp events with the correct keyCode

### ISSUE THREAD

**Issue by stephenpassero** [testing-library/user-event#963]
### Reproduction example

https://codesandbox.io/s/rtl-onkeyup-reproduction-case-mvuxv7?file=/src/App.js

### Prerequisites

Necessary snippets from reproduction example:

```js
// App.js
import "./styles.css";

export default function App({ onKeyUp }) {
  return <input onKeyUp={(e) => onKeyUp(e)} data-testid="test-input" />;
}


// App.test.js
describe("App", () => {
  it("calls onKeyUp events with the correct keyCode using #type", async () => {
    const onKeyUp = jest.fn();
    render(<App onKeyUp={onKeyUp} />);

    const input = screen.getByTestId("test-input");
    await userEvent.type(input, "123{enter}");

    // Find each event (see actual sandbox for details)

    // All of these receive 0, instead of the correct keycode
    expect(event1.keyCode).toEqual(49);
    expect(event2.keyCode).toEqual(50);
    expect(event3.keyCode).toEqual(51);
    // Enter key
    expect(event4.keyCode).toEqual(14);
  });
});
```

### Expected behavior

I expect that when using `userEvent #type` on a input, an `onKeyUp` event is fired with a different `keyCode` for each letter/key. However, it seems that the `keyCode` is always `0`, regardless of which key was actually pressed (see reproduction case)

### Actual behavior

Instead, it seems like the event fired always has a `keyCode` of `0`

### User-event version

`14.2.0`

### Environment

Testing Library framework: `@testing-library/react@13.2.0`
JS framework: `react@18.0.0`
Test environment: `jest@28.1.0`
DOM implementation: Not quite sure... I'm just using Jest, which I think ships with Jsdom

**Comment by ph-fritsche** [comment]
>[`KeyboardEvent.keyCode`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) is deprecated. You should use [`KeyboardEvent.code`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) instead.

>We removed support for deprecated features, as we neither want to maintain features that nobody should use, nor want to encourage their usage.

https://github.com/testing-library/user-event/issues/842
