### ISSUE TITLE
Module '"@testing-library/user-event"' has no exported member 'specialChars'

### ISSUE THREAD

**Issue by dsdenes** [testing-library/user-event#976]
### Reproduction example

https://codesandbox.io/s/cool-worker-gecijh?file=/src/App.tsx

### Prerequisites

1: Install @testing-library/user-events
2: Try to import based on the documentation: 
```
import userEvent, { specialChars } from "@testing-library/user-event";
```
https://testing-library.com/docs/ecosystem-user-event/#special-characters

### Expected behavior

Should expose `speciaChars`

### Actual behavior

Doesn't expose `speciaChars`

### User-event version

14.2.1

### Environment

Testing Library framework: 

JS framework: 

Test environment: 

DOM implementation:

**Comment by ph-fritsche** [comment]
![image](https://user-images.githubusercontent.com/39068198/175036638-b2c9c8bd-7516-410a-a086-e09db5cb4018.png)

**Comment by dsdenes** [comment]
Dear @ph-fritsche,

Thank you for taking time to investigate this bug.

My installed version is 14.2.1 as it's visible in the example. Do I oversee something?

Denes

**Comment by ph-fritsche** [comment]
The docs you mentioned above are for `user-event@13`.
There is no `specialChars` export in `user-event@14`.

**Comment by dsdenes** [comment]
gotit thank you!
