### ISSUE TITLE
UserEvent keyboard() not triggering key event for {Enter} 

### ISSUE THREAD

**Issue by daniel-hoang** [testing-library/user-event#980]
### Reproduction example

https://codesandbox.io/s/determined-zhukovsky-k7zueb?file=/src/index.test.js

### Prerequisites

1. Render input element and listen/handle Enter keydown event
2. handle the Enter keydown event by assigning the input value to the output text content
3. just focus on the input element and execute keyboard(test{Enter})

### Expected behavior

The test expect the output's content to have 'test' string

### Actual behavior

- With user-event version 13.5.0, the above expectation does happen
- With user-event version 14.2.1 (latest release), the above expectation does not happen

### User-event version

14.2.1

### Environment

Testing Library framework: 

JS framework: 

Test environment: 

DOM implementation: 

### Additional context

NOTE that when switching the user-event version, we need to refresh the Browser tab for this version change to take effect.

**Comment by daniel-hoang** [comment]
Also found similar issue from stackoverflow:
https://stackoverflow.com/questions/72273734/test-with-userevent-keyboard-does-not-pass-however-it-works-in-the-browser
and his codesandbox example also shows the issue if we change:
- line 17 to: await userEvent.keyboard("testquery{enter}");
- and comment out line 20: // expect(inputEl).toHaveValue("testquery");

**Comment by ph-fritsche** [comment]
In Codesandbox you need to use `const user = userEvent.setup({ document });` because the global `document` is shadowed in the test suite: `document !== globalThis.document`.
