### ISSUE TITLE
`type` regression when used with `setRangeText`

### ISSUE THREAD

**Issue by dzonatan** [testing-library/user-event#981]
### Reproduction example

https://codesandbox.io/s/repro-userevent-setrangetext-v14-efm7wv

### Prerequisites

Type `12,34` in the input field.

### Expected behavior

A comma (`,`) gets automatically replaced with the dot (`.`) both in the browser and tests.
i.e. the final input value is expected to be `12.34`.

### Actual behavior

final value in the browser: `12.34`
final value in the tests: `1234`

### User-event version

14.2.1

### Additional context

This was working in v13: https://codesandbox.io/s/repro-userevent-setrangetext-v13-0wl91f?file=/src/App.test.js

**Comment by ph-fritsche** [comment]
Thanks for the report :heart:

**Comment by ph-fritsche** [comment]
In case anyone stumbles over this later:
Note that Jsdom doesn't implement the fourth property `selectMode` properly for `'end'` and `'select'`. See https://github.com/jsdom/jsdom/issues/2601
