### ISSUE TITLE
`jest.spyOn()` does not work with `type()` in some cases

### ISSUE THREAD

**Issue by dnt1996** [testing-library/user-event#986]
### Reproduction example

https://codesandbox.io/s/boring-mountain-pjvlih?file=/src/App.test.ts

### User-event version

14.2.1

**Comment by dnt1996** [comment]
I guess this code is the cause
https://github.com/testing-library/user-event/blob/0a3fe4f46145c31821161eac4fa977dd943d1b59/src/document/selection.ts#L26-L85

**Comment by ph-fritsche** [comment]
Thanks for the report :heart:

**Comment by ph-fritsche** [comment]
@all-contributors add @dnt1996 bug
